### ISSUE TITLE
Redirect immediately to entry page when navigating for an exact entry in the globalsearch box

### ISSUE THREAD

**Issue by AgFlore** [VocaDB/vocadb#1009]
**Is your feature request related to a problem? Please describe.**
You meet auto-complete tips when you search using the top globalsearch box. You click on the autocomplete tip (which is usually exact where you want to go) and the page submits your query. 

And as i may recall (probably before we are migrated to react?), if you clicked on the autocomplete tip and there's a unique result for your query, you would be redirected immediately to that entry.

But recently that's gone, one always bumps into the search page first, and the user would need to click himself into the entry he wants. Can we somehow bring the old fashion back?

**Comment by ycanardeau** [comment]
> And as i may recall (probably before we are migrated to react?)

Yes, I haven't implemented this feature on the future branch (React) yet. We used the [`SearchController.TryRedirect`](https://github.com/VocaDB/vocadb/pull/939/files#diff-e25e7a89d7ced8548b1cfdfb66035a7dad9268997e75f0da4daa1ae1056332a6L203) method on the server side, but now we need to do the same thing in the [`HomeController.GlobalSearch`](https://github.com/VocaDB/vocadb/blob/44b362b57271b7912b7ff578f47b0c4845e8fd38/VocaDbWeb/Controllers/HomeController.cs#L56) method or on the client side.
