### ISSUE TITLE
VocaDB wiki unavailable

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1015]
Currently, the VocaDB wiki is unaccessible ("Server Error in '/' Application.")

https://wiki.vocadb.net/

**Comment by ycanardeau** [comment]
@Shiroizu works for me now

**Comment by ycanardeau** [comment]
It works for me now.

**Comment by andreoda** [comment]
Sadly not:
![grafik](https://user-images.githubusercontent.com/52045122/139512866-5e80f25d-07e0-419d-9491-a29ad02d381e.png)

**Comment by ycanardeau** [comment]
I forgot to copy and paste `appsettings.json` into the `publish` folder. If you're still experiencing this issue, clear your cookies and sign in again.

**Comment by andreoda** [comment]
that worked, thank you!

**Comment by ycanardeau** [comment]
Welcome :)

**Comment by riipah** [comment]
I was also getting this error. Tried incognito window and it worked. Then tried logging out of VocaDB and it didn't work (login cookie settings have changed?). Cleared cookies for VocaDB, logged back in, and now it seems to be working.
