### ISSUE TITLE
Prevent "flickering" when switching between pages

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#1022]
We have several options.
1. Change the website design so that nobody will notice the "flickering".
2. Cache API responses (with [axios-cache-adapter](https://github.com/RasCarlito/axios-cache-adapter) or [React Query](https://github.com/tannerlinsley/react-query)).
3. Display a temporary placeholder (something like Material UI's [skeleton](https://mui.com/components/skeleton/) or Fluent UI's [shimmer](https://developer.microsoft.com/en-us/fluentui#/controls/web/shimmer)).
4. Use [React Location](https://github.com/tannerlinsley/react-location) instead of [React Router](https://github.com/remix-run/react-router).
5. Give up on client-side rendering and use server-side rendering instead.
6. Give up on React.
7. Do nothing.
8. Move the state out of a component.

Apparently, Discord uses options 1 and 2.

**Comment by romanrm** [comment]
I never noticed any flickering before, but recently on loading the Song (maybe others) page, it briefly displays "technical" titles for every UI element, before changing them to normal ones. Is this what you mean in this bug report? Thanks

**Comment by ycanardeau** [comment]
> it briefly displays "technical" titles for every UI element, before changing them to normal ones. Is this what you mean in this bug report?

No, that's not what I mean, and it's a different issue than this one. A simple solution for this would be to cache and load localization resources from local storage.

For example, visit a song details page, and then click on an arbitrary tag on the tags section in the basic info tab. The song details page will be cleared, and then the tag details page will be rendered. If this happens within a very short time, you'll experience flickering.

But since you've never noticed flickering before, it might not be that problematic.

**Comment by riipah** [comment]
>No, that's not what I mean, and it's a different issue than this one.

Is there are separate issue about that already? Because I have noticed the translations issue, and it's a bit annoying.

**Comment by ycanardeau** [comment]
No, there is no issue for that yet. I've tried the caching approach, but it didn't work.

**Comment by riipah** [comment]
I think that even if the fields were empty, that would be better than showing the "placeholder" translation IDs. Because some of the placeholders are longer than actual translations, which causes jumping.

**Comment by ycanardeau** [comment]
> Or just hide the content until translations are loaded? That how many websites work.

Hiding the content until translations are loaded has some UX problems in my opinion (try https://www.tesla.com/). Personally I'd go with the current implementation, or your first suggestion.

**Comment by riipah** [comment]
Perhaps the issue will be less noticeable once all pages are converted to React. For example I visit the editing history page quite often, and that page is not (?) yet React. So when you come back from that page, all the caches are cleared and those placeholder titles appear again. But once the history page is React as well, it should not happen.

**Comment by ycanardeau** [comment]
> For example I visit the editing history page quite often, and that page is not (?) yet React.

Yeah, like you said, this happens when a page transition is triggered, which always happens when you move from non-React to React pages. By the way, you can tell whether or not a page is converted to React by seeing the show random page button. 

![image](https://user-images.githubusercontent.com/51428094/162610834-ec7b4487-5ec7-4f26-b9d9-4861e0d24368.png)

**Comment by riipah** [comment]
And here I was just using React Dev tools 😄

**Comment by ycanardeau** [comment]
Me too 😄

**Comment by riipah** [comment]
Actually, I think the most common reason for clearing cache might be using the top search bar. That one causes full page refresh, right?

**Comment by ycanardeau** [comment]
> That one causes full page refresh, right?

Yes, but we could do that on the client side.

**Comment by ycanardeau** [comment]
Regarding to the original issue, starting from React 18, the [new transition APIs](https://reactjs.org/docs/react-api.html#transitions) are available. We can try them after https://stackoverflow.com/questions/71817106/type-children-element-has-no-properties-in-common-with-type-intrinsicat has been fixed.
