### ISSUE TITLE
Renaming the "animator" artist type & artist role

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1026]
[Mentioned](https://discord.com/channels/309072240639737866/666326527197315091/910687053954572328)

The "animator"-role and the corresponding "Animation producer" -artist type are used with:

1) MMD animators 
2) PV/Video creators
3) Film-makers
4) More (?)

There have been proposals for changing these terms to be more accurate with the different use cases (no final suggestions yet). "Video Editor", "Video Creator", or something else.

**Comment by andreoda** [comment]
I think it might be better to have 2 roles: animator and video editor:
- https://en.wikipedia.org/wiki/Animator
- https://en.wikipedia.org/wiki/Video_editor

They are distinctively different, I am currently studying film-making and animation in university.

Animators = 3d animation (e.g. MMD)/2d animation
Video editors = cutting videos/editing videos/"decorating" videos (VFX)

**Comment by Shiroizu** [comment]
Splitting the artist types would bring some informational value, but ultimately I think it might be not feasible for a few reasons:

1) It's common for PVs to include a little bit of animation, meaning that the video artist would be credited for both roles anyways.
2) 10's of thousands of entries would need to be fixed.
3) Most importantly, VocaDB hasn't generally been too infromative with the roles. If the animator role needs to be splitted, the same can be argued for the other roles as well (Instrumentalist --> Pianist, Guitarist, + | Composer --> Track, Melody, + | Lyricist --> Lyrics, Translation | Illustrator --> Illustrator, Painting, Photographer, etc).

Instead, to distinguish between the different "sub-artist-types", I think the best option would be using the tags. For example there exists a [photographer -tag](https://vocadb.net/T/334/photographer) for illustrators.

**Comment by ycanardeau** [comment]
If we haven't yet got a consensus on what to do about this issue, I'll convert it to a GitHub discussion.

**Comment by FranGamer1892** [comment]
I agree with @Shiroizu, but then I am not sure which name would fit the best. "Video Editor" seems to exclude things such as animation, and "Video Creator", although more fitting, doesn't sit right with me.

**Comment by FranGamer1892** [comment]
Other suggested names were "PV Maker" or "Video Producer". Same as with "Video Creator", they seem fundamentally okay but they don't fully add up in my head.

**Comment by FranGamer1892** [comment]
Maybe "PV Maker" is a better option since it does seem to include animation more than the others.
