### ISSUE TITLE
Error merging tags

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#1035]
Getting an error screen when trying to merge tags (https://vocadb.net/T/3127/utau-cv-vc to https://vocadb.net/T/4954/utau-cvvc).

Only reproducible when merging a normal tag to another normal tag or a dummy tag created at the beta test site; merging dummy tags to any kind of tags works fine.

**Comment by ycanardeau** [comment]
@kateabr I think this issue has been fixed now. (I've tested it on the beta site.) Can you please check if

- all comments that belonged to the source tag are moved to the target tag
- comments on the target tag are sorted by creation date in a descending order
- deleted comments are not visible both on source and target tags

?

**Comment by kateabr** [comment]
@ycanardeau All works for me on the beta site, too. Is it safe to merge the tags at the actual site now?

**Comment by ycanardeau** [comment]
@kateabr Thanks for testing it! I haven't deployed the changes yet, so you still cannot merge the tags.

**Comment by ycanardeau** [comment]
@kateabr I've deployed changes to the main site, so you can now merge the tags.
