### ISSUE TITLE
"Mostly uses" section should not calculate all artist data

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1036]
For example, if someone is only marked as "vocal data provider" in a song entry, the marked synth on that entry should not be calculated into the "mostly uses" section of said vocal data provider's entry page.

Artist types that make sense:
- Arranger
- Composer
- Voice Manipulator

Artist types that do not make sense:
- Animator (maybe/mostly animates character xyz)
- Distributor
- Illustrator (maybe/mostly draws character xyz)
- Instrumentalist
- Lyricist
- Mastering
- Mixer
- Other
- Publisher
- Vocal data provider
- Vocalist

____

Reason for opening this issue: recent report by https://vocadb.net/Ar/82490

**Comment by CatgirlFrostmoon** [comment]
Would it be also possible to give priority to vocal synths _not_ marked as support?
