### ISSUE TITLE
Preferred display language option not working when not logged in

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#1037]
1. Visit VocaDB when not logged in
2. Open "account" menu, choose "English" (or whatever else) under "Preferred display language"

Expected result:
All titles are displayed in English language setting. "English" is selected" under "Preferred display language".

Actual result:
Setting is not applied. Titles are displayed in original language and "Original" is still selected under "Preferred display language".

Possible reasons:
Cookie not set or not applied. When logged in, this sets user option. When not logged in, it sets a cookie.

OS and browser:
Windows 10, tested in Firefox and Microsoft Edge.

**Comment by ycanardeau** [comment]
Fixed by fc780b4. I'm not sure why it was broken. I guess something has changed after upgrading to .NET 6.
