### ISSUE TITLE
"Search YouTube" link disappeared from song pages

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#1039]
I do not see the "Search YouTube" link anymore, for songs which only have NND media.
E.g. https://vocadb.net/S/324587 https://vocadb.net/S/378128 etc.
What happened to it? I was using it all the time to add missing YouTube original uploads to new songs, it was very convenient.

**Comment by ycanardeau** [comment]
This was caused by #1038. The song details page has been converted to React, but I forgot to add the "Search YouTube" link.

**Comment by romanrm** [comment]
Thanks!
