### ISSUE TITLE
Date formats incosistent on the song details page

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#1040]
Song page: https://romanrm.hk/2022-01-12T165323Z-song.png
Album page: https://romanrm.hk/2022-01-12T165600Z-album.png

It looks weird to have two different date formats right next to each other on the Song page; the Album one seems to have it right.

I'm not sure if this has always been like this, or changed recently.

**Comment by ycanardeau** [comment]
The song details page uses moment's [`format`](https://momentjs.com/) function, while the album details page uses .NET's [`DateTime.ToUniversalTime`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.touniversaltime?view=net-6.0) method. This inconsistency will be fixed after the album details page has been converted to React.

**Comment by romanrm** [comment]
The Song page uses two different date formats now as shown on the screenshot. As you speak only of changing the album page, do you think the former doesn't need to be updated to use the same format in both lines, for consistency? Thanks

**Comment by ycanardeau** [comment]
Ah, now I understand what you mean. If I remember correctly, there is no straight way to use the same format in both lines, because the former just shows date, while the latter shows date + time. See https://momentjs.com/.

**Comment by riipah** [comment]
While refactoring this, might as well migrate the page away from momentjs (to something like dayjs). [Momentjs is deprecated](https://momentjs.com/docs/#/-project-status/).

**Comment by ycanardeau** [comment]
I didn't know that Moment.js is deprecated, thanks for your feedback!
