### ISSUE TITLE
Song details page: popups don't align with buttons anymore

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#1042]
It used to be that when you click "add to custom list" or "report an error", the popup would align under the button. This still works on TouhouDB, but on VocaDB the popups seem to be just centered.

1. Open any song page
2. Click "Report an error"

Expected: popup would align with the button.
Actual: popup is centered.

**Comment by ycanardeau** [comment]
See also https://github.com/VocaDB/vocadb/issues/1041#issuecomment-1012172936.

Do popups need to be aligned with buttons in the first place? In most of the websites I use, popup is just centered. And considering that we migrate to a newer UI library in the future (#851), it might be difficult to emulate this behavior.

**Comment by riipah** [comment]
It's a good usability feature, so you don't need to move your mouse so much. Click the button, then just move the mouse down a bit. Not mandatory, just nice to have.

**Comment by FinnRG** [comment]
Considering the upcoming migration to mantine, I''ll close this issue for now. Mantine doesn't really have a way to align modals in such a way. UX wise, users who want to edit quickly can still use the keboard navigation.
