### ISSUE TITLE
Navigating buttons disappearing when switching tab on albums

### ISSUE THREAD

**Issue by VirtualCaZuL** [VocaDB/vocadb#1050]
**Website**
VocaDB

**Describe the bug**
When listening an album, there are two buttons at the bottom to navigate between songs. If I switch to the lyrics tab and come back to the main page, the two buttons are gone.

**To Reproduce**
1) Go to any album page
2) Choose any song on that album
3) Go to the lyrics tab
4) Come back to the main page
5) The "navigation buttons" are gone

**Expected behavior**
These buttons should still be there

**Screenshots**
![unknown](https://user-images.githubusercontent.com/78354050/150638606-0e2c535b-5d85-4d30-bdb9-1e37f059a4d3.png)
![unknown](https://user-images.githubusercontent.com/78354050/150638609-1522c659-0c25-4713-94cb-159e5ee3bce6.png)
![unknown](https://user-images.githubusercontent.com/78354050/150638617-97d74f67-f909-4f8a-98c0-07cd72f7f5ce.png)

**Desktop :**
 - OS: Windows 10
 - Browser: Edge

**Comment by ycanardeau** [comment]
Fixed by b6b7a3a. It preserved the `albumId` query param even when switching between tabs.
