### ISSUE TITLE
Impossible to add tags to entries

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1060]
**Website**
VocaDB

**Describe the bug**
No longer possible to add tags to song entries

**To Reproduce**
1. Go to [...](https://vocadb.net/S/383382) (any song entry)
2. Click on 'Edit tags'
3. Type the tag "puppet" (or other tag names)
4. Hover mouse over visible tag
5. Tag disappears

**Comment by ycanardeau** [comment]
Please try hard refresh by pressing CTRL+F5.

**Comment by andreoda** [comment]
@ycanardeau Just tried that. Didn't fix the issue :(

**Comment by ycanardeau** [comment]
@andreoda Okay I understand now what you mean. As a workaround, I think you can use the add button instead.

**Comment by ycanardeau** [comment]
Caused by #1059 including `/bundles/shared/libs.js`, and fixed by b3d406a. I've re-implemented the `Carousel` component so that we don't need to include `bundles/shared/libs.js`.
