### ISSUE TITLE
Inconsistent JSON field name across endpoints

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#1069]
The PVs field at the activity entries endpoint is called "pVs" instead of "pvs":
https://vocadb.net/api/activityEntries?editEvent=Created&maxResults=1&getTotalCount=false&fields=Entry&entryFields=PVs

**Comment by ycanardeau** [comment]
Fixed by a46d7bb by setting the `Name` property of the `DataMemberAttribute`. Note that this is a breaking change.
