### ISSUE TITLE
"Preferred streaming service" setting not working correctly

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1071]
**Website**
VocaDB

**Describe the bug**
I set my preference to "YouTube" but when I open a song entry, it prioritizes the NND media.

![grafik](https://user-images.githubusercontent.com/52045122/154829999-7d66530e-ffb4-421b-9348-d8282c291d17.png)
![grafik](https://user-images.githubusercontent.com/52045122/154830013-bfc435cc-5beb-4f91-aefe-244d2ca6766b.png)

**Comment by ycanardeau** [comment]
Fixed by 6cdf269. The `preferredVideoService` field was missing from the serialized JSON.
