### ISSUE TITLE
Empty response to a request

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#1073]
The following request produces an empty response:
https://vocadb.net/api/activityEntries?since=2012-06-16T15%3A00%3A20&editEvent=Created&entryType=Song&maxResults=10&getTotalCount=true&fields=Entry&entryFields=PVs&lang=Default&sortRule=CreateDate

Seems to be reproducible only with this specific timestamp, `2012-06-16T15:00:20`: increasing it by a minute results in a normal response.

**Comment by kateabr** [comment]
Update: timestamp `2012-06-25T15:35:41` yields the same result

**Comment by ycanardeau** [comment]
This is a known issue. Let's say you created three entries: an album, an artist and a song. You now have three activity entries. But if the song has been deleted, then only two activity entries are returned.

See https://github.com/VocaDB/vocadb/pull/663#discussion_r536812459 and #684.
