### ISSUE TITLE
randomize feature scrambles playlist

### ISSUE THREAD

**Issue by szhublox** [VocaDB/vocadb#1082]
**Website**
VocaDB

**Describe the bug**
Playlist track titles blank or wrong

**To Reproduce**
vocadb.net
click show random page (wait for refresh)
change search type to Song
click search button (wait for refresh)
click playlist button

![Untitled](https://user-images.githubusercontent.com/91105156/157799314-70c67158-fe8a-4b18-bfe7-34a969ca8ad6.png)

**Comment by szhublox** [comment]
user error, sorry

**Comment by ycanardeau** [comment]
@szhublox Possible duplicate of #804.
