### ISSUE TITLE
Songs with only deleted primary media will not load

### ISSUE THREAD

**Issue by goomie** [VocaDB/vocadb#1088]
Since the last maintenance today, the VocaDB interface appears to crash in both Chrome and Firefox when attempting to load a song entry with only deleted media, even when the video is marked as unavailable and theoretically should not load.

**Examples**

Deleted Nicovideo crashes:
https://vocadb.net/S/196943

Deleted YouTube crashes:
https://vocadb.net/S/47506

Deleted Nicovideo is OK if there's a backup video:
https://vocadb.net/S/265993
https://vocadb.net/S/250825

Songs with no media are OK:
https://vocadb.net/S/172194

**Comment by andreoda** [comment]
I think we created the same issue at the same time. Lol

**Comment by goomie** [comment]
Looks like this is working properly now.
