### ISSUE TITLE
When a new user is removing entry information, show a notification about artist verification and contacting staff

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#1098]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- When a new user is removing entry information, show a notification about artist verification and contacting staff

**Describe alternatives you've considered**
?

**Additional context**
- Producers often sign up to VocaDB in order to remove information from their entry, and their accounts get locked when they are discovered. Such a notification (warning?) might improve the experiences of both producers and VocaDB staff.

**Comment by ycanardeau** [comment]
> show a notification about artist verification and contacting staff

Should we prevent the edit from being saved?

Would it be useful as well if a report was sent to Discord when a new user is removing entry information?

By the way, what exactly do you mean by "removing entry information"? (e.g. deleting artist links and/or external links; entering an empty description; etc.)

**Comment by szc126** [comment]
IIRC aliases and external links tend to be removed or defaced (replaced with placeholders like "a")? And I guess "new user" would be someone with less than 10 previous edits, since the accounts tend to be for the single purpose of removing data from VocaDB.

**Comment by andreoda** [comment]
For reference:
![grafik](https://user-images.githubusercontent.com/52045122/161357014-9d640db8-2b32-42b5-833a-2ff6c327c8a9.png)

There are some ideas mentioned, might be helpful in some way.

**Comment by szc126** [comment]
Duplicate of #635.
