### ISSUE TITLE
Suggestions for VocaDB player

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#1114]
The VocaDB player (at the bottom) is a great feature. I have a few suggestions to improve it. Perhaps you have already considered them.

In general, I would copy YouTube as much as possible, because they have pretty good usability in this sense.

- [x] 1. When clicking video preview to begin playback, I think it should still play on the page, it was before. (be48d5fff77a14f9809eed5bc48e4364b6ad7c0f)
- [x] 2. When navigating away to another page, the video could continue playing as small thumbnail in lower corner. (be48d5fff77a14f9809eed5bc48e4364b6ad7c0f)
- [x] 3. Instead of right-clicking video preview, there could be popup icons for "add to queue" and "play now", similar to YouTube. Or perhaps hamburger menu. (6d9d3533023b2c85febd51171e4571e4cd194842)
- [x] 4. There could be an option to show play queue and save it as song list. (4e2a2300208483de0164112a836ac4121a77abc1)

Feel free to split this issue into multiple smaller ones and ask for clarifications if you're unsure what I meant.

**Comment by ycanardeau** [comment]
Damn, if I say so myself, the new bottom player is so awesome that I can't live without it anymore. Having spent some time on the beta site, I've come to accidentally click a link while playing a video on the main site.

> 1. When clicking video preview to begin playback, I think it should still play on the page, it was before.

This was already suggested by @Shiroizu on [Discord](https://discord.com/channels/309072240639737866/818499255349018624/959791354483986462). I think this is possible only when a video preview has a static position, which means we would have to give up on the previews on the search page, which have a dynamic position.

> 2. When navigating away to another page, the video could continue playing as small thumbnail in lower corner.

I was thinking about this, but wouldn't it be too "obtrusive"? One of the most ambitious parts of the new bottom player is that it doesn't stop playing, even while editing (this will be available only after the edit pages have been converted to React). Having a button to hide the player might be a good idea, so that users can concentrate on editing.

> 3. Instead of right-clicking video preview, there could be popup icons for "add to queue" and "play now", similar to YouTube. Or perhaps hamburger menu.

I didn't know that YouTube have those buttons. You should come back to development, but as a UX designer this time. :P

> 4. There could be an option to show play queue and save it as song list.

Yeah, I'm thinking about this feature. Saving the current play queue to local storage when closing the tab, and restoring it next time would be also useful.

**Comment by riipah** [comment]
> Damn, if I say so myself, the new bottom player is so awesome that I can't live without it anymore. Having spent some time on the beta site, I've come to accidentally click a link while playing a video on the main site.
> 
> > 1. When clicking video preview to begin playback, I think it should still play on the page, it was before.
> 
> This was already suggested by @Shiroizu on [Discord](https://discord.com/channels/309072240639737866/818499255349018624/959791354483986462). I think this is possible only when a video preview has a static position, which means we would have to give up on the previews on the search page, which have a dynamic position.

That might be fine. I was mostly thinking about the song pages anyway. For search page, the bottom player should be fine. I didn't even test the search page yet. The preview on search page could be removed or made smaller. I think it could just have a small video thumbnail with the buttons, similar to YouTube, again.

> 
> > 2. When navigating away to another page, the video could continue playing as small thumbnail in lower corner.
> 
> I was thinking about this, but wouldn't it be too "obtrusive"? One of the most ambitious parts of the new bottom player is that it doesn't stop playing, even while editing (this will be available only after the edit pages have been converted to React). Having a button to hide the player might be a good idea, so that users can concentrate on editing.
> 

Yes, I was thinking there should be an option to hide the player anyway. The thumbnail player is just extra.

> > 3. Instead of right-clicking video preview, there could be popup icons for "add to queue" and "play now", similar to YouTube. Or perhaps hamburger menu.
> 
> I didn't know that YouTube have those buttons. You should come back to development, but as a UX designer this time. :P
> 

I don't know about design. I only know how to copy UX :). I'm just thinking that these are things that YouTube is already doing, and they have probably spent a ton of UX research money. I'm pretty happy how YouTube works, so it's probably a good idea to take inspiration from there, even if not copy directly.

**Comment by ycanardeau** [comment]
> I think YT doesn't allow playing while closing the player.

This is exactly what I was wondering. Where did you find the information? And does that mean the current bottom player is not allowed?

**Comment by CatgirlFrostmoon** [comment]
I'd like some way to open and close the bottom player, please~ I think a bottom player can be really useful, but it's also kind of distracting, so I think it should be closeable. Maybe a little close button in the right hand corner? And then a little arrow or tab on the bottom of the screen to open it back up. :3

**Comment by ycanardeau** [comment]
@CatgirlFrostmoon The bottom bar is now closeable.

![image](https://user-images.githubusercontent.com/51428094/186625077-aa126822-f73f-4555-9264-76a38ff488a2.png)

**Comment by ycanardeau** [comment]
> I think YT doesn't allow playing while closing the player.

I've changed the implementation so that the [minimum functional requirements](https://developers.google.com/youtube/terms/required-minimum-functionality) are fulfilled.

**Comment by andreoda** [comment]
Some more suggestions:

1. Maybe there could be a "shortcut" to close the mini player/video similar to how it is possible on YouTube, when you scroll down while a video is running. There is a small "X button" at the top left corner of the mini player.
![grafik](https://user-images.githubusercontent.com/52045122/187493601-78685465-050e-4b56-b944-3cd3fac11dd4.png)

2. About the function of hiding the media player: Currently the option to hide it is only for the current instance/page, maybe there could be an option to "hide it till you unhide it", so it will not appear again after switching pages or reloading the current page of the website.

*Not sure if I should open new issues regarding these suggestions.*
