### ISSUE TITLE
Display bug in the "view modifications" section of an event series

### ISSUE THREAD

**Issue by VirtualCaZuL** [VocaDB/vocadb#1120]
**Website**
VocaDB

**Describe the bug**
There is a display issue when viewing modifications of a series of event (things users updated)

**To Reproduce**
1. Go to any event series (https://vocadb.net/Es/264/the-vocaloid-collection for example)
2. Click on View Modifications
3. See the bug

**Expected behavior**
The modifications screen should behave like normal entries

**Screenshots**
![image](https://user-images.githubusercontent.com/78354050/164307335-193f0305-2794-48d1-b9d4-0cc64b0abc10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (doesn't work on edge either)

**Comment by ycanardeau** [comment]
Fixed by bc8f728.
