### ISSUE TITLE
Artist roles menu impossible to edit

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1150]
**Website**
VocaDB

**Describe the bug**
When opening the artist tab on the edit page of an entry and trying to customize the roles, the popup box appears inside the bottom left corner. It is impossible to move the box and editing anything inside of it.

Example:
![grafik](https://user-images.githubusercontent.com/52045122/175059253-c70f65d9-b526-4b8f-90cf-e773a91feb6d.png)

**Comment by CatgirlFrostmoon** [comment]
Just popping in to second this.

**Comment by ycanardeau** [comment]
Looks like #1139 doesn't work well with non-React pages. Reverted #1139.
