### ISSUE TITLE
'Unspecified' event type when searching for an event by name via API

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#1153]
Can be reproduced for any category:
* "Character anniversary" ([example](https://vocadb.net/api/releaseEvents?query=GUMI%27s%20Birthday%202022&maxResults=10))
* "Album release fair" ([example](https://vocadb.net/api/releaseEvents?query=THE%20VOC%40LOiD%20M%40STER%2047&maxResults=10))
* "Club" ([example](https://vocadb.net/api/releaseEvents?query=VOCALOiD%20LiMiT%20vol.11&maxResults=10))
* "Convention" ([example](https://vocadb.net/api/releaseEvents?query=Anime%20Expo%202012&maxResults=10))
* "Other" ([example](https://vocadb.net/api/releaseEvents?query=CustoMiku%20Paris&maxResults=10))
* "Concert" ([example](https://vocadb.net/api/releaseEvents?query=MIKUCrossing%E2%99%AA%20HOMEParty02%20%E9%8F%A1%E9%9F%B3%E6%A9%99%E9%BB%84%E6%AD%8C%E5%90%88%E6%88%A6&maxResults=10))
* "Contest" ([example](https://vocadb.net/api/releaseEvents?query=Lily%20Song%20Contest%202017&maxResults=10))

However, some events, when loaded in the same fashion, correct categories ([example](https://vocadb.net/api/releaseEvents?query=Vocaloid3%20Launch%20Contest&maxResults=10)).

**Comment by ycanardeau** [comment]
These are all series events, so the `category` is inherited from the series.

**Comment by kateabr** [comment]
I see, so it does not get inherited when accessing a particular event that belongs to the series. Thank you for the clarification!

**Comment by ycanardeau** [comment]
You're welcome!
