### ISSUE TITLE
Prefer most used/most popular artist entries when searching for artists on song submit/edit pages

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1155]
When adding or editing entries, searching for artists should prefer either most used/most popular or voice synth entries in general.

For example, searching for Hatsune Miku gives these results at the top:
![grafik](https://user-images.githubusercontent.com/52045122/176039582-99837cc8-11bb-4076-bc8a-cb14006bd628.png)
or
![grafik](https://user-images.githubusercontent.com/52045122/176039625-853cc5bf-3e7a-48ca-b73f-79b4c7041c36.png)

Example search for Saki (Synthesizer V):
![grafik](https://user-images.githubusercontent.com/52045122/176039701-e8c22a3d-bf81-4645-8ff5-40b600c9727c.png)

___

This issue is similar to https://github.com/VocaDB/vocadb/issues/949

**Comment by CatgirlFrostmoon** [comment]
THIS
PLEASE <3

**Comment by ycanardeau** [comment]
Sorted by total song rating. Available on the [beta site](https://beta.vocadb.net).

**Comment by CatgirlFrostmoon** [comment]
So, I attempted this with IA, which...kind of works? As you can see, Hyurno's kind of just hanging out in the middle of the IA pile. It might be best to sort by vocal synth then non-vocal synth, with each in-group sorted by popularity within itself.

![IA-ssue](https://user-images.githubusercontent.com/98185854/177012161-4409f7b7-d01e-4c7b-914a-103fb6598230.JPG)
