### ISSUE TITLE
Unable to add images to events

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1159]
I am not sure why but for some reason I always get an error when trying to upload an image to an event entry (it also happened when I tried to add external links). 

Example:
![grafik](https://user-images.githubusercontent.com/52045122/177227889-ba2ed456-95da-43a2-8584-c21ae6b3ca72.png)

The image is in correct format (tried it with JPG and PNG) so I don't understand why this happens. Other user are able to add images though (Shiroizu could add).

**Comment by ycanardeau** [comment]
Closing due to a lack of information.

**Comment by andreoda** [comment]
![grafik](https://user-images.githubusercontent.com/52045122/177329722-c535e7df-5c15-4c3d-9e7f-010f7c43d3f8.png)

I am also unable to add artists to event entries.

**Comment by andreoda** [comment]
New information:
I am able to edit existing event entries but not my own it seems. When I try to add images and artists to my created event entries, it says "Unable to save properties." Sometimes, it also happens with external links.
