### ISSUE TITLE
Sometimes "Unable to create song/save properties"

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1178]
### Website
VocaDB

### Describe the bug
Song submit page doesn't always work https://vocadb.net/Song/Create "Unable to create song. Please correct the errors and try again." Refreshing the page will fix this error. This seems to happen when multiple https://vocadb.net/Song/Create?pvUrl=https://www.nicovideo.jp/watch/{nicoid} -links are opened at first.

The same error can happen on https://vocadb.net/Song/Edit/ -pages as well: "Unable to save properties." -banner will sometimes appear. Refreshing the page fixes this issue. The browser console error message looks the same. 

Uncaught (in promise) Error: Request failed with status code 400:
<details>
  <summary>Browser console error message: (click to view)</summary>
      
`exports https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     exports https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     _ https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     exports https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     exports https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     exports https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     request https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     e https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     exports https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     value https://vocadb.net/bundles/index.js?id=d6e2d07c9c15d91c585029650b645e68:1     l https://vocadb.net/bundles/index.js?id=d6e2d07c9c15d91c585029650b645e68:1     l https://vocadb.net/bundles/index.js?id=d6e2d07c9c15d91c585029650b645e68:1     a https://vocadb.net/bundles/index.js?id=d6e2d07c9c15d91c585029650b645e68:1     a https://vocadb.net/bundles/index.js?id=d6e2d07c9c15d91c585029650b645e68:1     value https://vocadb.net/bundles/index.js?id=d6e2d07c9c15d91c585029650b645e68:1     value https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     value https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     l https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     l https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     P https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     P https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     value https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     Ie https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     r https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     onSubmit https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     l https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     l https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     W https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     W https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     onSubmit https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     We https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Je https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Li https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Li https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ci https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ai https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ne https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ai https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ai https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Qt https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Xt https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     unstable_runWithPriority https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ur https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     je https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Gt https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8 vendor.js:8:32894     l https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     (Async: promise callback)     s https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     W https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     W https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     onSubmit https://vocadb.net/bundles/5989.b3fb94f0652ac877.js:1     We https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Je https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Li https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Li https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ci https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ai https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ne https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ai https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ai https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Qt https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Xt https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     bind_applyFunctionN self-hosted:1349     Xt self-hosted:1312     unstable_runWithPriority https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Ur https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     je https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     Gt https://vocadb.net/bundles/vendor.js?id=641e74491596d3b91851225a894e5386:8     bind_applyFunctionN self-hosted:1349     Gt self-hosted:1312`  
</details>

Request payload: 

`-----------------------------368026306535668469231209668964 Content-Disposition: form-data; name="contract"  {"artists":[{"artist":{"additionalNames":"","artistType":"Producer","deleted":false,"id":228,"name":"maya","pictureMime":"image/jpeg","status":"Finished","version":22}},{"artist":{"additionalNames":"神威がくぽ, Gackpoid, がくっぽいど, Camui Gackpo","artistType":"Vocaloid","createDate":"2011-02-05T20:55:48","defaultName":"神威がくぽ","defaultNameLanguage":"Japanese","id":12,"name":"Kamui Gakupo","pictureMime":"image/png","releaseDate":"2008-07-31T00:00:00Z","status":"Approved","version":29}}],"draft":false,"names":[{"language":"Japanese","value":"６月２１日の不実在恋人"}],"pvUrls":["https://www.nicovideo.jp/watch/sm40846686"],"reprintPVUrl":"","songType":"Original"} -----------------------------368026306535668469231209668964--`

### To Reproduce
To reproduce (edit page error):  
1) Open two song entry edit pages 
2) Try clicking "Save changes" on both pages (no changes needed) 
3) One page will save and the page will show the error

(does not happen 100% of the time)

### Desktop:
 - OS: Windows10
 - Browser: Firefox 103.0

### Checklist

- [x] Tested on the **[beta site](https://beta.vocadb.net)** (this issue does not seem to exist in the beta site) !
- [x] Checked in **Chrome**, **Safari**, **Edge** and **Firefox** (tested in chrome & edge - no issue) !
- [x] Checked in **private mode** (tested in private mode - no issue) !
- [x] Cleared **browser cache** and **cookies**
- [x] Checked the **DevTools console**
- [x] Checked the **syslog** (mods+ only)

**Comment by ycanardeau** [comment]
Does this issue happen only after you use the website "for a while"? If that's the case, I suspect the request token has expired. 

> this issue does not seem to exist in the beta site

This is weird, because there are almost no difference between the main and beta sites, except for the new bottom player. Can you please make sure that browser cache is cleared? Maybe hard refresh would help?

**Comment by AgFlore** [comment]
Me too greeted by HTTP400.
```
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"traceId":"00-19bef65843e66b2a6461cb4b4cced534-27bf12cb7be0cbed-00"}
```

My `requestVerificationToken` was
```
CfDJ8GLnBD2oxndFlfieyW5m75vT7mWSOFgVJP7gv2s-mmJOw2ZhomuN5KW_z3wMtjxyHsgYKrgDCAeM6P4HbgKmUY9chpQhMpMWUlsxz-TvKhok-PI9dW0ivmpSYMGZVluOeujSvesqT7papnhYsC7MJ9rN96L-fi0hHaowVXWKsTuNaHZJ6bUkF8yCyeS4lwLa9Q
```

shall check how it decodes and how long it expires.

**Comment by ycanardeau** [comment]
@AgFlore Thanks, but maybe better not to share the token here, which is not intended to be shared publicly.

**Comment by andreoda** [comment]
Just experienced this as well. I could create some entries which were original songs but when it came to covers it didn't work.

**Comment by ycanardeau** [comment]
[Using a single token upon login](https://stackoverflow.com/questions/20057225/csrf-token-collisions-with-multiple-tabs) would solve this issue.

See also:
- [Multiple browser tabs and the Synchronizer Token Pattern](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0#multiple-browser-tabs-and-the-synchronizer-token-pattern-1)
- https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Antiforgery/src/Internal/DefaultAntiforgery.cs#L40

**Comment by andreoda** [comment]
Some additional info/comments on this:
![grafik](https://user-images.githubusercontent.com/52045122/183273245-ca56e107-8c12-4711-a6c1-34d093678743.png)
![grafik](https://user-images.githubusercontent.com/52045122/183273257-e2961803-60e6-4187-83f2-3103739e88fe.png)

**Comment by ycanardeau** [comment]
#1193 has been deployed to the main site. And I've improved error messages a bit. Please let me know if the issue still persists.
