### ISSUE TITLE
Merging songs will make the added events/tags disappear

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1191]
### Website
VocaDB

### Describe the bug
The merging action will not consider the events and tags added to the song entry.

### To Reproduce
*See Screenshots*

### Expected behavior
The events and tags should be transferred with the merge.

### Screenshots
First song entry: https://vocadb.net/S/425809
![grafik](https://user-images.githubusercontent.com/52045122/183274590-b83b1956-09ca-4641-8140-d81999991607.png)
Merged to this song entry: https://vocadb.net/S/429815 (The event and tags were added manually after the merge)
![grafik](https://user-images.githubusercontent.com/52045122/183274625-0b96a8bb-8e3f-40a4-b090-4ab8e3dde858.png)
![grafik](https://user-images.githubusercontent.com/52045122/183274616-54de3bc1-005f-48f1-aa6f-f9fb2e6fed77.png)

Test on the beta site with random songs:

Song 1: https://beta.vocadb.net/S/317511
![grafik](https://user-images.githubusercontent.com/52045122/183274750-07658f3a-9899-4b30-bb35-245e97574009.png)
Song 2: https://beta.vocadb.net/S/344599 with event: [プロセカNEXT 5](https://beta.vocadb.net/E/3197/proseka-next-5)
![grafik](https://user-images.githubusercontent.com/52045122/183274769-ce38fe98-05bb-4363-8ed6-e71c688339aa.png)
Merging:
![grafik](https://user-images.githubusercontent.com/52045122/183274791-6d1b6824-d925-427e-98f2-c4950472cfe3.png)
Result:
![grafik](https://user-images.githubusercontent.com/52045122/183274813-7b61972c-a56e-4302-86e1-589aec23305c.png)
*(This example did actually transfer one tag)*

Other examples where the event did not transfer and had to be added manually:
- https://vocadb.net/S/277104
- https://vocadb.net/S/374196
- https://vocadb.net/S/368710
- https://vocadb.net/S/368709
- https://vocadb.net/S/248544
- https://vocadb.net/S/428998

*Using: Windows / Firefox*

**Comment by ycanardeau** [comment]
I guess not merging tag usages is by design, because tag usages aren't included in version control.
