### ISSUE TITLE
Entry links' styles are incorrect

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#1207]
![изображение](https://user-images.githubusercontent.com/14264395/187492128-aa6b825d-c800-4333-8a4f-546814738c08.png)

Links I've visited appear as if I didn't visit them and vice versa.

**Comment by ycanardeau** [comment]
I had this issue on Android, but clearing browser cache fixed this. I can see visited links are displayed in a different color. Tested on Chrome, Edge and Firefox.

Please check the checklist first.
