### ISSUE TITLE
API for Song/PopupContentWithVote?id=416174 returns 500 (song popups do not work)

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1208]
### Website
VocaDB

### Describe the bug
When hovering over a songlink on VocaDB, the popup doesn't show the information properly (server error 500)

![image](https://user-images.githubusercontent.com/15908050/187573986-57541944-5a88-4b25-b292-2bfe444fd0c7.png)

Album, Artist and Tag -popups work normally:

https://vocadb.net/Album/PopupContent?id=28162
https://vocadb.net/Artist/PopupContent?id=885
https://vocadb.net/Tag/PopupContent?id=7854

### To Reproduce
1. Go to https://vocadb.net/S/416174 (or any page that has song entry links)
2. Hover over any songlink under "alternative versions"
3. See error

### Expected behavior
A song popup window should show up

### Desktop (please complete the following information):
 - OS: win10
 - Browser: firefox

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable

- [x] Tested on the **[beta site](https://beta.vocadb.net)**
- ~~[ ] Checked in **Chrome**, **Safari**, **Edge** and **Firefox**~~
- ~~[] Checked in **private mode**~~
- ~~[ ] Cleared **browser cache** and **cookies**~~
- [x] Checked the **DevTools console**
- [x] Checked the **syslog** (mods+ only)

2022-08-31 00:00:36.1936 [.NET ThreadPool Worker] ERROR An unhandled exception has occurred while executing the request. - System.InvalidOperationException The model item passed into the ViewDataDictionary is of type 'VocaDb.Model.DataContracts.Songs.SongWithPVAndVoteForApiContract', but this ViewDataDictionary instance requires a model item of type 'VocaDb.Model.DataContracts.Songs.SongWithPVAndVoteContract'. Void EnsureCompatible(System.Object)    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)

**Comment by ycanardeau** [comment]
Thanks for reporting the issue! I've removed qtip2, [which is no longer maintained](https://github.com/qTip2/qTip2), replacing it with React components. It's very likely that something has broken. Please feel free to report issues if you find any.

**Comment by ycanardeau** [comment]
test
