### ISSUE TITLE
User Messages & EntryEdits unavailable (Uncaught ReferenceError: vdb is not defined)

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1221]
### Website
VocaDB

### Describe the bug
When opening either the user messages https://vocadb.net/User/Messages or entryedits https://vocadb.net/User/EntryEdits/329, the pages do not load properly. The console error "Uncaught ReferenceError: vdb is not defined" is printed in both cases.

### To Reproduce
1. Go to https://vocadb.net/User/Messages
2. See error

### Desktop (please complete the following information):
 - OS: win10
 - Browser: firefox

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable

- [x] Tested on the **[beta site](https://beta.vocadb.net)** (also affected)
- [x] Checked in **Chrome**, and **Firefox**
- [x] Checked in **private mode**
- [x] Cleared **browser cache** and **cookies**
- [x] Checked the **DevTools console**
- [x] Checked the **syslog** (mods+ only)

**Comment by ycanardeau** [comment]
Thanks for reporting the issue!

This was caused by #1220 removing [VocaDb.js](https://github.com/VocaDB/vocadb/pull/1220/files#diff-242892cd3221376afbf8a4d7d441ac1206cb5597bf9e3860c49d8b7cfd4d153e), in which `vdb` was defined.
