### ISSUE TITLE
Unable to add tags

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1239]
### Website
VocaDB

### Describe the bug
Adding tags to album/artist/song entries does not currently work.

### To Reproduce
1. Go to any entry (https://vocadb.net/S/429550 for example)
2. Try adding any tag ([trance](https://vocadb.net/T/435/trance) for example)
3. See error (tag does not get added)

Audit log displays an empty line: "2022/10/07 16:38:43 | Shiroizu | tagging Material with"
The PUT-request returns 200, no error message on web console.

### Desktop (please complete the following information):
 - OS: win10
 - Browser: Firefox 105.0.2

### Checklist

Fill out the checklist, using ~~strikethroughs~~ to mark any items that are not applicable

- [x] Tested on the **[beta site](https://beta.vocadb.net)** (also affected)
- [x] Checked in **Chrome** and **Firefox**
- [x] Checked in **private mode**
- [x] Cleared **browser cache** and **cookies**
- [x] Checked the **DevTools console**
- [ ] Checked the **syslog** (mods+ only) (unavailable, 500 Internal Server Error)

**Comment by ycanardeau** [comment]
Thanks for reporting the issue. This was caused by #1238. I've reverted tag mappings from the latest backup.
