### ISSUE TITLE
Searching for VocaDB URLs broken

### ISSUE THREAD

**Issue by shnurks** [VocaDB/vocadb#1277]
### Website
https://vocadb.net/Search

### Describe the bug
Searching for a URL does not find any results.

### To Reproduce
1. Enter any link search in the search box such as `https://vocadb.net/S/271504`
2. get 0 results

### Expected behavior
one result should be found

### Screenshots
![image](https://user-images.githubusercontent.com/69062248/204158309-2bec4942-2886-4b9d-9ee2-65190f4f65e7.png)

### Additional context
It worked until a few hours ago.

### Checklist
- [x] Users should limit themselves to three or less active issues and PRs at any one time.
- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** and **[VocaDB/community](https://github.com/VocaDB/community)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] Checked in **Chrome**, ~~**Safari**~~, **Edge** and **Firefox**.
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and **cookies**.
- [ ] ~~Checked the **DevTools console**.~~
- [ ] ~~Checked the **syslog** (mods+ only).~~

**Comment by ycanardeau** [comment]
Thanks for reporting the issue.

> It worked until a few hours ago.

The search type in the screenshot is set to "Anything". Are you sure that it worked not only for "Song", but also for "Anything"? As far as I know, this functionality is only supported for the "Song" search type.

**Comment by shnurks** [comment]
Ah okay, that actually makes sense. Would it be possible to add a note for
that here: https://wiki.vocadb.net/wiki/33/search-terms-cheat-sheet ?

Am Mo., 28. Nov. 2022 um 09:49 Uhr schrieb Aigamo ***@***.***

**Comment by ycanardeau** [comment]
If you have a VocaDB account, you can edit the wiki using your account. Or you can post the note for that here so that I can copy and paste it to the wiki.

**Comment by shnurks** [comment]
Alright, I can do it myself then

**Comment by ycanardeau** [comment]
@shnurks can you please confirm if this issue can be closed when you have a chance?

**Comment by shnurks** [comment]
I haven't been able to edit the wiki page (mabybe a permission issue) but the search works as expected.
