### ISSUE TITLE
Captcha always invalid when triggering password reset

### ISSUE THREAD

**Issue by disqonnected** [VocaDB/vocadb#1284]
### Website
VocaDB / UtaiteDB / TouhouDB

### Describe the bug
When triggering password reset, the captcha always fails. 

### To Reproduce
1. Go to ['ForgotPassword'](https://vocadb.net/User/ForgotPassword)
2. Fill in the fields
3. Click Send Request
4. See error " CAPTCHA is invalid."

### Desktop (please complete the following information):
 - OS: Linux
 - Browser: Firefox
 
![image](https://user-images.githubusercontent.com/30081339/208309246-108a1907-0647-429d-866f-2458ed39e31b.png)

### Checklist

- [x] Users should limit themselves to three or less active issues and PRs at any one time.
- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** and **[VocaDB/community](https://github.com/VocaDB/community)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] Checked in **Chrome**~~, **Safari**, **Edge**~~ and **Firefox**.
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and **cookies**.
- [x] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by ycanardeau** [comment]
Thanks for reporting the issue.

As far as I can see from your screenshot, this issue is caused by #1245, removing `LayoutScripts.ts` that used legacy Knockout view models. The `ForgotPassword` page hasn't been converted to React yet,  so merging #1251 should fix this issue.
