### ISSUE TITLE
LogFileReader.GetLatestLogFileContents throws an IOException

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#1289]
`IOException: The process cannot access the file '...' because it is being used by another process.`

**Comment by snakefoot** [comment]
Replace this:
https://github.com/VocaDB/vocadb/blob/fff1ef72c4803a74daf9fd6deff926addea67126/VocaDbWeb/Code/Security/LogFileReader.cs#L24

With this:
```c#
using (var f = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
using (var s = new StreamReader(f))
{
    return s.ReadToEnd();
}
```

NLog v5 changes NLog FileTarget to use KeepFileOpen=true by default. See also:  https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#filetarget-keepfileopen--true-by-default

**Comment by ycanardeau** [comment]
@snakefoot I see. Actually, I was looking for a solution without having to set `KeepFileOpen` to `false`. Thanks for your kind support and maintaining NLog :)
