### ISSUE TITLE
Support importing into an existing song list instead of creating new song list

### ISSUE THREAD

**Issue by CXwudi** [VocaDB/vocadb#1299]
This issue is written to myself as I'd like to contribute to VocaDB and implement this feature, unless someone wants to take over it

### Is your feature request related to a problem? Please describe. (required)
When importing 3rd party list (NND, YT list) into VocaDB, it always creates a new list. There is no option to import it into an existing play list

![image](https://user-images.githubusercontent.com/17377423/215125709-26b6b6d5-b574-48ca-a00a-5e2c98494b85.png)

### Describe the solution you'd like. (required)

A button or option for users to choose where to import the 3rd party list into.

The flow is:

1. 3rdPartyList ← read the list from 3rd party list url using [ISongListImporter](https://github.com/VocaDB/vocadb/blob/08a4ae55262e3772d1f5b08f0bd838b1d9fd9386/VocaDbModel/Service/SongImport/ISongListImporter.cs#L5)
2. vocadbList ← ask for user the ID of the existing vocadb list, and read the list
3. allowDuplication ← a checkbox on UI 
4. newItemList ← for each item in 3rdPartyList: if the item is in vocadbList && not allowDuplication, filter out the item, else save the item into newItemList 
5. newVocadbList  ← vocadbList + newItemList 
6. show a final list newVocadbList to user, with a confirm button
7. if the user clicks the confirm button, replace the content of vocadbList with newVocadbList 

There are two ways to implement it:

1. First way is just modifying on the existing `https://vocadb.net/SongList/Import` webpage
	![prot-1](https://user-images.githubusercontent.com/17377423/215153276-bc9117b0-74d5-4b5d-8abb-e8b5497a65eb.jpg)
2. Second way is that instead of modifying on the existing page, create a new button in this webpage
	![image](https://user-images.githubusercontent.com/17377423/215154856-9d10269a-c48d-4c03-b8b2-10d16d20ea89.png)
	 And the new button will forward user into the new webpage similar to what described in the first way, but without the two tabs, and only accept the work flow for importing the 3rd party list into the existing song list.

### Describe alternatives you've considered. (required)

Infact, developers can use the `POST /api/songList` API to modify one's own playlist.

So potentially I or someone could just make a 3rd party GUI/CLI/web app that can handle playlist importing.

But I prefer to have this feature built-in in VocaDB.

Another alternative method is to support merging two VocaDB song list into one, but I don't like this idea as it wastes database IDs, because if I remember correctly, deleting the song list doesn't really release the old song list ID for creating a new song list. 

### How should the UI look like? Please draw. (required)
See above

### Additional context (optional)

I would like to say the second way is easier to implement, but the first way is more intuitive to users. So I am open to listen from opinions from VocaDB staff and other users.

If possible, the feature can be extended to merge two VocaDB song list into one. 

I learned Kotlin and Kotlin is similar to C#, so I should have no problem with C# although I have 0 experience, but I need time to learn React as I am just a Java backend developer, so don't expect me to start implementing this feature right away, but I will finish it one day.

### Checklist

Fill out the checklist.

- [x] Users should limit themselves to **three or less** active issues and PRs at any one time.
- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** and **[VocaDB/community](https://github.com/VocaDB/community)** for duplicate issues.
- [ ] Provided a link to a **pull request** or an **example repository** that demonstrates the feature.
- [x] Checked that the [**public API**](https://github.com/VocaDB/vocadb/wiki/Public-API) is not provided for this purpose.
   - As mentioned in alternative solutions, it is possible using the `POST /api/songList` API, but prefer to have this feature in VocaDB.
- [x] [**One active developer**](https://github.com/VocaDB/vocadb/wiki/Staff) approved the feature request and/or pull request.
   - https://discord.com/channels/1016918705063600128/1016920596208160768/1068533059000995930
- [ ] [**One active developer**](https://github.com/VocaDB/vocadb/wiki/Staff), or **at least three independent outside developers** reviewed the pull request.

**Comment by ycanardeau** [comment]
> There are two ways to implement it:
> 1. First way is just modifying on the existing https://vocadb.net/SongList/Import webpage
> 1. Second way is that instead of modifying on the existing page, create a new button in this webpage

I think these ways make the code unnecessarily complicated.

> If possible, the feature can be extended to merge two VocaDB song list into one.

I'd suggest you implement merging two song lists, just like other entries, instead of importing into an existing song list. It would be much easier to implement, more flexible and consistent with other entries, especially with tags. So you would have to create a new song list, and then merge the old one into new one. It's a bit intuitive and unfriendly to users, but it won't be a problem because I guess it's not used frequently.

> Another alternative method is to support merging two VocaDB song list into one, but I don't like this idea as it wastes database IDs,

And I don't think this is a problem. External links, for example, have already been wasting lots of database IDs internally.

> because if I remember correctly, deleting the song list doesn't really release the old song list ID for creating a new song list.

I'm not sure what you mean by this though.

**Comment by CXwudi** [comment]
@ycanardeau I agree implementing song list merging would be much easier. Previous I was just concerning about the database IDs. Because from what I observed, if I delete a song list and soon create a new one (assuming no one else created a song list during this time), then the new song list would take a new ID instead of reusing the old one. 

Anyways, may I close this issue as deprecated and re-open a new one for merging two song list?

**Comment by ycanardeau** [comment]
> Because from what I observed (in 2020), if I delete a song list and soon create a new one (assuming no one else created a song list during this time), then the new song list would take a new ID instead of reusing the old one. (Not sure if this behavior still there in 2023)

This is the correct behavior, and I think it will work like this as long as we use [`IDENTITY`](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property) (`AUTO_INCREMENT`).

> Anyways, may I close this issue as deprecated and re-open a new one for merging two song list?

Sure. Or perhaps you can just edit the title of this issue?

**Comment by CXwudi** [comment]
> This is the correct behavior, and I think it will work like this as long as we use [IDENTITY](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property) (AUTO_INCREMENT).

I see, that make sense.

**Comment by ycanardeau** [comment]
Superseded by #1300.
