### ISSUE TITLE
Support merging song lists

### ISSUE THREAD

**Issue by CXwudi** [VocaDB/vocadb#1300]
This issue is written to myself as I'd like to contribute to VocaDB and implement this feature, unless someone wants to take over it.

### Is your feature request related to a problem? Please describe. (required)
This is the follow-up of the deprecated #1299. Basically, by supporting merging two song lists into one, we could indirectly support importing multiple 3rd party song list into one song list.

### Describe the solution you'd like. (required)
I noticed VocaDB already has a merging mechanism for songs. Maybe the solution would be similar to this, but for merging the content of two song lists. 

Some options that users can configure:
- Is duplicated songs allowed/filtered
- Should the old list been deleted (probably not worth to implement)

### Describe alternatives you've considered. (required)
`POST /api/songList` is always the alternative solution, but I prefer to have this feature built-in in VocaDB, so that casual users can merge multiple song list as well.

### How should the UI look like? Please draw. (required)

Add a new button in the `https://vocadb.net/SongList/Edit/<song list id>` called `merge from another list`
![image](https://user-images.githubusercontent.com/17377423/215288810-f1818b44-9599-4a43-aa2b-688d504f03ac.png)

When clicked, the new button creates the following new HTML elements (not using a new webpage because the user may have other modifications):
![image](https://user-images.githubusercontent.com/17377423/215289649-be129076-e9fb-4bc7-9d4d-5146a38b8ba7.png)

When the "Proceed" button is clicked, more HTML elements will show up to show the confirm page
![image](https://user-images.githubusercontent.com/17377423/215289006-242dc471-4c10-4483-9f8b-88a2505a465f.png)

When the "Accept" button is clicked, the `https://vocadb.net/SongList/Edit/<song list id>` page should contain the new songs imported from another list. Then the user can continue the modification, and save it finally.

### Additional context (optional)
The implementation would likely be done purely in frontend. The fact is that this feature is implemented in the `https://vocadb.net/SongList/Edit/<song list id>` page which we can't redirect the user to another URL to avoid lost of other modification

### Checklist

Fill out the checklist.

- [x] Users should limit themselves to **three or less** active issues and PRs at any one time.
- [ ] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** and **[VocaDB/community](https://github.com/VocaDB/community)** for duplicate issues.
- [x] Provided a link to a **pull request** or an **example repository** that demonstrates the feature.
- [x] Checked that the [**public API**](https://github.com/VocaDB/vocadb/wiki/Public-API) is not provided for this purpose.
- [x] [**One active developer**](https://github.com/VocaDB/vocadb/wiki/Staff) approved the feature request and/or pull request.
- [ ] [**One active developer**](https://github.com/VocaDB/vocadb/wiki/Staff), or **at least three independent outside developers** reviewed the pull request.

**Comment by ycanardeau** [comment]
For your information, we already have an interface, which is available to trusted users+ only, to merge entries (albums, artists, songs and tags).

![image](https://user-images.githubusercontent.com/51428094/215316207-f1812718-d6ef-4f1f-847d-7b4c8a35b4ad.png)

**Comment by CXwudi** [comment]
> For your information, we already have an interface, which is available to trusted users+ only, to merge entries (albums, artists, songs and tags).
> 
> ![image](https://user-images.githubusercontent.com/51428094/215316207-f1812718-d6ef-4f1f-847d-7b4c8a35b4ad.png)

Thanks for the reference, yeah I couldn't find that page in my account.

**Comment by kyokudesuchan** [comment]
literally spam. take this down ❤️
