### ISSUE TITLE
Importing .csv files as songlists

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#1315]
### Is your feature request related to a problem? Please describe. (required)
Related to https://github.com/VocaDB/vocadb/issues/1317: a deleted list could be easily re-created.

### Describe the solution you'd like. (required)
It would be really convenient to be able to create songlists based on .csv files: for example, VocaColle rankings could be scrapped from the website, organized into a table, exported into .csv and then just imported into the database (rather than being compiled manually).

### Describe alternatives you've considered. (required)
Importing from Google Sheets -- very similar in terms of implementation (probably).
Direct import is a better option, I think, because:
1. it is faster: does not require the .csv to be uploaded to a third-party website
2. it does not point towards the editor's Google account: users concerned about their anonymity will feel more secure

### How should the UI look like? Please draw. (required)
![изображение](https://user-images.githubusercontent.com/14264395/226934412-68767548-13cd-43f1-8a2b-7cdee43a1f43.png)
![изображение](https://user-images.githubusercontent.com/14264395/226937340-e6f432d5-be09-4f6e-bf90-ae838561f79c.png)

Data format:
| url | notes |
| --- | --- |
| https://vocadb.net/S/0 | something about the song |

Other columns could just be ignored, then it will be completely compatible with the export format.

### Additional context (optional)
This should probably be a trusted+ user feature because of how easily it could be taken advantage of (?)

### Checklist

Fill out the checklist.

- [ ] Users should limit themselves to **three or less** active issues and PRs at any one time.
- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** and **[VocaDB/community](https://github.com/VocaDB/community)** for duplicate issues.
- [ ] Provided a link to a **pull request** or an **example repository** that demonstrates the feature.
- [x] Checked that the [**public API**](https://github.com/VocaDB/vocadb/wiki/Public-API) is not provided for this purpose.
- [ ] [**One active developer**](https://github.com/VocaDB/vocadb/wiki/Staff) approved the feature request and/or pull request.
- [ ] [**One active developer**](https://github.com/VocaDB/vocadb/wiki/Staff), or **at least three independent outside developers** reviewed the pull request.

**Comment by CXwudi** [comment]
Wow, I didn't expect that a PR is already created, Nice job devs.

But is there a security reason why it should be a trusted-user only feature? Because I find this feature helpful for myself as well, as a regular user
