### ISSUE TITLE
Unable to click the header when being on the "Entry reports" page 

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1376]
### Website
VocaDB

### Describe the bug
Being on the "Entry reports" page makes it impossible to click on the options in the header, specifically "Anything" (search filter), "Account" and "Messages".
The notifications disappear/are hidden as well.

### To Reproduce
1. Go to "https://vocadb.net/Admin/ViewEntryReports"
2. See empty and unclickable header options

### Screenshots
Normal view:
![grafik](https://user-images.githubusercontent.com/52045122/234633469-39360eae-2132-4163-99a1-f83b6932d8b5.png)
After entering the "Entry reports" page:
![grafik](https://user-images.githubusercontent.com/52045122/234633580-d8b77b86-70dc-45cd-9c49-33e50dc765bb.png)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser: Firefox

**Comment by FinnRG** [comment]
This should be solved, once the page is converted to react. See #1000 for more information.
