### ISSUE TITLE
Piapro embeds do not work anymore

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1377]
### Website
VocaDB

### Describe the bug
The "Piapro" embeds on song entries etc. do not function anymore.

### To Reproduce
1. Go to "https://vocadb.net/S/1363"
2. Click on the original media "Piapro" link
3. See the embed not displaying correctly

### Expected behavior
Normally, a mini player would appear (Piapro player).

### Screenshots
Result when trying to play a "Piapro" embed:
![grafik](https://user-images.githubusercontent.com/52045122/234636718-80748675-9800-457a-9dac-4814514fcbb5.png)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser: Firefox

**Comment by FinnRG** [comment]
The main issue here seems to be that the previous piapro embed was using shockwave flash and was launched in another window, where we can't control it using the bottom player.

I could easily pull the mp3 url from the piapro HTML page and create a simple custom player, but I don't know if there could be legal issues since we would be displaying piapro content without using an official embed.

**Comment by szc126** [comment]
One of the last conversations in the former dev server was that the piapro terms of service does not approve of embedding the HTML5 player, so yca added the still image instead.

**Comment by andreoda** [comment]
I researched and couldn't find any policy on Piapro forbidding embeds. If you have a source, can you link it?
Another point is that we never had any issue with it, if they see a problem, they can still reach out and we can disable it afterwards.

**Comment by andreoda** [comment]
I am split on this:
Enabling the embedding is most useful and we also never had any issues regarding it.
However, knowing about the rules now and mentioning them forces us to follow them.
All other media services we support seem to allow embedding so it is really annoying and sad to let it go of Piapro embeds.

Next steps:
Should the Piapro link stay in the "Original media" section then? If so, should a popup to the Piapro page be opened after clicking on it instead of showing the still image to avoid confusion?
