### ISSUE TITLE
Allow loading more comments in the "recent comments" view

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#138]
Currently limited to 50 comments. It's not possible to load more, because the comments are loaded from multiple tables, so skipping would be expensive.

Two solutions:
- Optimize comment loading so that only IDs are loaded first, then sorted and paginated, finally loading the actual comments, similar to how entries API works.
- Instead of pagination by index, do filtering by comment submission date: it would be fast and easy to load comments that are older than a specific timestamp.

**Comment by ycanardeau** [comment]
Maybe after #643.
