### ISSUE TITLE
Allow entering two or more "original" PVs on song submission page

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#14]
Currently there's fields for one original PV and one reprint. Should add dropdowns for selecting type for each PV (by default the first can be original and second a reprint). Possibly a button for adding more PVs as well.

If more than one original PV is entered, how to load metadata (artist, song title)? First original Nico PV? What if the PV type is changed? Maybe there should always be one (fixed) field for original PV?

**Comment by riipah** [comment]
Not sure I want to do this. The submission page is intended to be as simple as possible, and I can't figure out a way to enable entering multiple PVs without making it more complicated. The user can always enter additional PVs on the edit page.

**Comment by dset0x** [comment]
I agree there is no need for this.

We could add add a small "you may add more PVs later" comment in the New Song page (_maybe_) and close this.

**Comment by ycanardeau** [comment]
> We could add add a small "you may add more PVs later" comment in the New Song page (maybe) and close this.

@dset0x Could you please create an issue for that?
