### ISSUE TITLE
Add metadata (Twitter/OpenSearch) back

### ISSUE THREAD

**Issue by FinnRG** [VocaDB/vocadb#1405]
#1102 removed most of the html metadata tags. This is relevant, because this breaks support for proper TwitterCards and OpenSearch.

**Comment by szc126** [comment]
For reference: The metadata is here, correct?

https://github.com/VocaDB/vocadb/blob/f83f3e9bc8a35ea425af6dd48428b3e35014e70d/VocaDbWeb/Views/Shared/React/Index.cshtml#L20-L51

**Comment by FinnRG** [comment]
> For reference: The metadata is here, correct?
> 
> 
> 
> https://github.com/VocaDB/vocadb/blob/f83f3e9bc8a35ea425af6dd48428b3e35014e70d/VocaDbWeb/Views/Shared/React/Index.cshtml#L20-L51

Not anymore, in the linked PR I replaced all of the `View(Index)` calls with `File("index.html", " text/html")`. If you run `npm run prod`, you can see that vite (our current bundler) creates the index.html file in a wwwroot folder.

So to add metadata back, one would have to add placeholders into the `VocadbWeb/index.html` file and add a helper function, which takes the PageProperties and replaces the placeholders with the relevant properties.
