### ISSUE TITLE
Website does not display for Trusted(+?)

### ISSUE THREAD

**Issue by goomie** [VocaDB/vocadb#1421]
### Website
**VocaDB** / UtaiteDB / TouhouDB

### Describe the bug
Since today's maintenance, none of the website navigation panels will display while logged into a Trusted user account. The website cannot be used.

### To Reproduce
1. Log in as a Trusted user
2. Navigation panels no longer load

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox 113.0.1 (64-bit)

### Screenshots

![image](https://github.com/VocaDB/vocadb/assets/40348837/ae1a90bd-a685-4b2b-ac35-6f276b8a1c6b)

### Additional context
This error does not occur when logged out. I observed multiple Regular-level users making edits, but no one Trusted and above.

### Checklist

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**. - No error.
- [x] Checked in **Chrome**. (Error appears)
- ~~[ ] Checked in **Safari**.~~
- ~~[ ] Checked in **Edge**.~~
- [x] Checked in **Firefox**.
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and **cookies**. (Works correctly when logged out, error reappears when logging in)
- [x] Checked the **DevTools console**. (Possibly relevant error linked)
~~- [ ] Checked the **syslog** (mods+ only).~~

**Comment by FinnRG** [comment]
This wasn't caught in testing, because it only occurs if a user never changed their interface style and is logged in. The website will need to be redeployed for this change to take effect.

**Comment by FinnRG** [comment]
@goomie Could you check again?

**Comment by goomie** [comment]
Website is functioning correctly - thanks!
