### ISSUE TITLE
More song language options

### ISSUE THREAD

**Issue by FinnRG** [VocaDB/vocadb#1441]
Based off #1428.

We are currently only displaying a subset of the ISO 639-1/639-2 language codes for lyric languages. This should be expanded to allow a removal of all language tags on VocaDb after the implementation of #1408. We also need to continue supporting the current culture codes for backwards compatibility reasons.

After reviewing our current language tags I think that using the [glottolog codes](https://glottolog.org/) going forward is best. The glottolog codes include regional dialects, some fictional/constructed languages and  indigenous languages. The large number of languages can also cause confusion for users, so these less common languages should only appear after the user clicks a "More Languages" button.

**Comment by szc126** [comment]
Personally I think ISO is still better, due to the standard nature and common usage. I've never seen glottolog in the wild except for on Wikipedia, and I reckon that the granularity would get quickly confusing.

**Comment by FinnRG** [comment]
1. I also prefer ISO codes. We will also have to support ISO codes in the future because we need to be backwards compatible. There are however some languages and dialects which aren't covered by ISO codes. The most popular example would be [brazilian portuguese](https://vocadb.net/T/6244/brazilian-portuguese) with around 118 songs.
2. I really want to avoid having some languages covered by the new language field (#1408) and some by tags.

Maybe the best solution is to use ISO 639-3 codes per default, which should cover the majority of use cases and add glottolog codes per request. This is relatively easy because the backend only stores the culture codes as strings and doesn't validate them.

**Comment by szc126** [comment]
1. What about modifiers like pt-BR? That's a pretty common extension of the ISO codes.
