### ISSUE TITLE
Non-English languages suggestion

### ISSUE THREAD

**Issue by Kitsuneko2003** [VocaDB/vocadb#1463]
### Is your feature request related to a problem? Please describe. (required)
If i want to use Chinese language, i have to switch language setting to non-english.
But in Non-English language, text is mixing English, Japanese, and Chinese. It's so bad for me.
![image](https://github.com/VocaDB/vocadb/assets/134658521/e633f1d4-9ca1-415d-9540-28ac526ec647)
I have become accustomed to English genre name, but i don't like localized artist name and album name.

### Describe the solution you'd like. (required)
Separate non-english language. (It may take a lot of work, but I think it's necessary. Because someone are making Korean translations, and I'm making Chinese translations too. More languages there are, more problems there will be.) display localized name in brackets on some text like artist name and album name. Looks like "Original Name [Localized Name]".

**Comment by szc126** [comment]
Maybe related to #10.

**Comment by andreoda** [comment]
@Kitsuneko2003 

We have these options:
![grafik](https://github.com/VocaDB/vocadb/assets/52045122/dfcab205-495b-4b3d-b7ed-170e4e7ced25)

Here are the explanations to them:
![grafik](https://github.com/VocaDB/vocadb/assets/52045122/07f854be-42fb-4e67-854c-b13d0b94f145)

**Comment by Kitsuneko2003** [comment]
So, the problem is incorrect or missing translations. I think i can close this issues.
