### ISSUE TITLE
Related songs in API

### ISSUE THREAD

**Issue by bomjacob** [VocaDB/vocadb#148]
Hello!
I'm currently developing a VocaDB bot for the Telegram Messenger.
I've gotten most of the major features such as Song/Artist browsing and information done already. While doing this, however, I noticed that there doesn't seem to be any way get the related songs using the API. I know I can get devived/alternate versions of a song using `/api/songs/{id}/derived`, but that's not what I mean. I mean the page that you get when you go to any song page on the site and click the "Related songs" tab. I realise I could scrape it from `http://vocadb.net/Song/Related/{id}` - that just seems kinda stupid to have to resort too though, I feel like it should be included in the API somehow.

**Comment by riipah** [comment]
Hmm yes, should be doable without too much work. I can look into it if you need it. Can't promise that I can do it right away though.

**Comment by riipah** [comment]
Do you only need related songs, no related albums/artists?

**Comment by bomjacob** [comment]
It would be nice to have artist too (the bot currently doesn't support albums anyways), but how are those made, I don't see them anywhere on the site?
I don't /need/ it per say, but it would be nice to have. And it would save me from having to do scraping and then looking the song ids up afterwards (since I don't know how I would go about choosing the language of the results if it's not using the api)

**Comment by riipah** [comment]
It's better to do use the API anyway (the HTML might change, plus it's more load for the server).

Anyway, adding the API was very simple, I did that already.

http://vocadb.net/api/songs/125735/related

**Comment by bomjacob** [comment]
Thank you so much :D
Is there any way of knowing if it's related because of artist, likes or tag?
It seems like it's the same order as on the site, but I can't just assume that there will be a certain number of each type can I?
Also it seems like the version on the actual site is a bit broken now (missing names and pictures).

**Comment by riipah** [comment]
Ok, fixed. Need to wait for people to stop editing though

**Comment by riipah** [comment]
> Is there any way of knowing if it's related because of artist, likes or tag?
What do you mean? The results are grouped based on how they're related. 

>It seems like it's the same order as on the site, but I can't just assume that there will be a certain number of each type can I?
There's at most 16 results for the artist match, 12 for the others. Do you need that to be configurable? The songs are sorted descending based on rating score. I just took the same data as is on the website. Don't rely on the order, you should sort them yourself.

**Comment by bomjacob** [comment]
> What do you mean? The results are grouped based on how they're related. 
I'm so sorry, I didn't see that. It's perfect :D
> Do you need that to be configurable?
Nope, this is fine, it would be nice to have pagination, but since I very such doubt that a user would want to scroll through more than 12 (or 16) in each group, this is works perfectly.

**Comment by riipah** [comment]
Pagination would be very difficult to implement for this because the related songs in different categories are loaded separately (there's 3 database queries), and you'd need to merge the results for pagination.

**Comment by bomjacob** [comment]
Oh yeah, that's true. And since it's that difficult and not really needed this works just fine.
