### ISSUE TITLE
Allow username to be changed

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#149]
Possibly by moderator only at first. Currently usernames cannot be changed, but we've been getting some requests. Technically this should be possible since users are internally referred to by their ID.

**Comment by shiroiusagi** [comment]
+1 would really love to see this

**Comment by riipah** [comment]
One restriction: because the passwords are salted with the username, the user will have to reset their password after the username is changed.

**Comment by d-dd** [comment]
Can you  put a limit on this, such as one name change every 12 months? If people change names constantly it will be hard to remember who is who.

**Comment by riipah** [comment]
For now I'll only allow moderators to change usernames upon request. Later we might allow users to change their own name, and I'll add some limits. Also thinking about adding username history that records old names.
