### ISSUE TITLE
When submitting a song, get song information from all possible sources

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#15]
Currently, when submitting a song, the song title and artists are filled automatically, but only for Nico PVs. This is because most of the time, the original PVs is on NicoNicoDouga, but obviously this isn't always the case. The original might be from SoundCloud or Youtube as well, and the same title auto-parsing could be used for those.

Only "original" PVs should be considered, reprints are never parsed.

**Comment by romanrm** [comment]
I hope you can consider working on this, it'd be very helpful to also have this for YouTube.

**Comment by riipah** [comment]
I'll try to add this for YT at least.

**Comment by riipah** [comment]
Please understand that for other services besides NicoNico, the parsing will be much more unreliable, because those other sites do not have consistent conventions like Nico Nico does. At best I can add the title from YouTube as is, but it will need to be cleaned manually. Uploader can be matched, but that's about it.

**Comment by riipah** [comment]
This is done and will be deployed later today probably
