### ISSUE TITLE
Advanced filters don't work

### ISSUE THREAD

**Issue by lalondeguy** [VocaDB/vocadb#1520]
### Website (required)
VocaDB

### Describe the bug (required)
When you apply advanced filters, songs are not filtered by the criteria selected.

### To Reproduce (optional)
1. Go to the songs tab.
2. Click an advanced filter (I picked "Artist type: CeVIO" for the screenshot as it gives obvious erroneous results, since all songs on the immediate first page of the songs tab use Vocaloid.)
3. Notice that the songs stay the same.

### Expected behavior (optional)
When you click on an advanced filter, the results should be filtered to exclusively include songs that fit the criteria.
For example, if you pick "Artist type: CeVIO", the first song that appears should (likely, as I'm unaware of any CeVIO songs with higher scores) be "[不埒な喝采](https://vocadb.net/S/314253)".

### Screenshots (optional)
![image](https://github.com/VocaDB/vocadb/assets/109246223/8141e8bc-5ac9-43ad-bd64-5d9211b40310)

### Desktop (optional)
 - OS: Windows 11
 - Browser: Firefox

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
~~- [ ] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).~~
- [x] Checked in **private mode**.
~~- [ ] Cleared **browser cache** and **cookies**.~~
~~- [ ] Checked the **DevTools console**.~~
~~- [ ] Checked the **syslog** (mods+ only).~~

**Comment by FinnRG** [comment]
Will be fixes in the next update.
