### ISSUE TITLE
Add artist type for NEUTRINO

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1533]
Too many "other voice synthesizer" voicebanks exist on the database (736).
It might be useful to add an additional artist type to the list.

After a research, the following list was created: https://docs.google.com/spreadsheets/d/1kqwgrsF1yedGHlfoG4Dex5CSnAvvJmRPWXewgsqOf0I/edit?usp=sharing

The result is that a NEUTRINO artist type is the most logical.

___

Related issues:
- https://github.com/VocaDB/vocadb/issues/458
- https://github.com/VocaDB/vocadb/issues/1333

**Comment by FinnRG** [comment]
I really think we should consider #1333 at this point. In the coming years this list will only get longer and as a database we should always be as accurate as possible. So in the short term I will add NEUTRINO (and possibly more types) and in the long term ( so after the new frontend) migrate to a new database to implement #1333.
