### ISSUE TITLE
UtaiteDB favicon shows the VocaDB icon

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#1559]
### Website (required)
UtaiteDB

### Describe the bug (required)
UtaiteDB favicon (http://utaitedb.net/Content/favicon.ico) shows the VocaDB favicon (small Miku) instead of the UtaiteDB favicon (microphone).

### To Reproduce (optional)
1. Go to UtaiteDB

### Expected behavior (optional)
https://web.archive.org/web/20170327143010/http://utaitedb.net/Content/favicon.ico

### Screenshots (optional)
If applicable, add screenshots or videos to help explain your problem.

### Desktop (optional)
 - OS: n/a
 - Browser: n/a

### Smartphone (optional)
 - Device: n/a
 - OS: n/a
 - Browser n/a

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [ ] Tested on the **[beta site](https://beta.vocadb.net)**.
- [ ] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [ ] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
This issue seems to be fixed.
