### ISSUE TITLE
Adding categories for designers and instrumentalists

### ISSUE THREAD

**Issue by saturclay** [VocaDB/vocadb#1594]
### Is your feature request related to a problem? Please describe. (required)
Right now, there are no artist categories for instrumentalists or designers. Currently, they both just fall under "other individuals" (though sometimes people will put designers in the "illustrator" category as well). If you want to specifically credit someone as an instrumentalist on a song/album, you have to go in and set their role for that entry in particular. For designers, there's not a way to do even this, so I just leave their role as "other." Needless to say, this creates a lot of extra work since many, if not most, albums (at least on TouhouDB) have designers and/or instrumentalists credited.

### Describe the solution you'd like. (required)
Add both instrumentalist and designer as artist types, and have it so that, by default, those are their roles when added to a song or album. For designers, this would also necessitate adding a "designer" role.

### Describe alternatives you've considered. (optional)
At minimum a "designer" role could be added that could be selected when adding artists to a song/album. This would be less convenient than having it as an artist category, but would at least make it clear when crediting designers.

### Checklist (required)

Fill out the checklist.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.

**Comment by FinnRG** [comment]
I personally don't think that we have enough designers for a separate artist type  (if we add a designer type, we should also add animator, etc.). But a Designer role should work, as long as the wiki and tag description clarify the differentiation between Designer and Illustrator.

I can see the appeal of an instrumentalist artist type. On vocadb we have the following tags that denote instrumentalists:

- [bassist](https://vocadb.net/T/30/bassist)
- [clarinetist](https://vocadb.net/T/9193/clarinetist)
- [drummer](https://vocadb.net/T/107/drummer)
- [flautist](https://vocadb.net/T/510/flautist)
- [guitarist](https://vocadb.net/T/176/guitarist)
- [keyboardist](https://vocadb.net/T/222/keyboardist)
- [percussionist](https://vocadb.net/T/1523/percussionist)
- [pianist](https://vocadb.net/T/336/pianist)
- [saxophonist](https://vocadb.net/T/509/saxophonist)
- [synthesist](https://vocadb.net/T/6754/synthesist)
- [trombonist](https://vocadb.net/T/6811/trombonist)
- [trumpeter](https://vocadb.net/T/514/trumpeter)
- [violinist](https://vocadb.net/T/460/violinist)

Here, however, we must be mindful that many instrumentalists are also music producers, and therefore a majority of the tagged artists would not change to the suggested instrumentalist type (@Shiroizu / @andreoda do you have any insight how large this percentage could be?).

**Comment by saturclay** [comment]
I will take a sample of the data from TouhouDB, but it's my feeling from having been adding artists that there's a fairly large number who are often credited as instrumentalists and never as arrangers/composers, as well as a not insignificant number of people who are exclusively credited as designers. But again, I'll get back to you with some hard numbers. I don't know if the numbers are radically different for VocaDB, but if that's the case and it would render the change impractical, I'll accept that.

Also, when you say animator, do you mean something different from the existing animation producer artist type? I'm not sure what the difference between an animator and an animation producer would be, but I think there's a pretty clear difference between an illustrator and a designer.

**Comment by FinnRG** [comment]
@saturclay I forgot that we actually have an animation producer artist type. I was going to say that for smaller groups we should prefer tags/artist roles. Also, I'm not sure if the overlap of designers and illustrators might be too big (I don't have much experience with designer artist entries so I might be wrong here).

**Comment by saturclay** [comment]
@FinnRG OK I've taken a look at the databases, and here's what I found.

DB|other individuals|tagged as designer|tagged as guitarist|tagged as bassist|tagged as drummer|tagged as pianist
-|-|-|-|-|-|-|
TouhouDB|735|27|127|86|80|13
VocaDB|2517|5|529|324|141|68
UtaiteDB|1154|1|194|140|125|21

To note, these are *all* just in the "other individual" category, so this doesn't include any music producers, illustrators, etc. who are also tagged as designers or instrumentalists. The number of instrumentalists here is quite robust, so I think that can be safely added as a category.

I'm surprised by how small the numbers are for designers for VocaDB and UtaiteDB. Granted, the number of designers isn't huge for TouhouDB either, but it's magnitudes higher than VocaDB in terms of percentage (3.67% of other individuals for TouhouDB vs. 0.2% for VocaDB). I don't know the exact reason for this, but I would guess that it has something to do with the Touhou community having a greater emphasis on albums (where designers are usually credited), whereas VocaDB has a greater emphasis on individual song uploads. For reference, the current ratio of albums to songs is about 8:1 for TouhouDB and 21:1 for VocaDB.

So there you go! I do think that a designer category would be worth it for TouhouDB at the very least, since that number is only going to grow as more entries are added, but I see how that wouldn't necessarily be the case for VocaDB. Anyway, thanks for reading, hope this breakdown of the numbers is helpful for decision-making.

**Comment by saturclay** [comment]
Small addendum: as I've been going through artist entries on VocaDB, I've noticed at least a couple designers who were in the illustrator category, but were strictly designers and not illustrators, so it's possible that there are more artists on VocaDB where a designer category would be applicable than I previously thought.
