### ISSUE TITLE
Activity pages skip entries when clicking on "Show more"

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#1597]
### Website (required)
VocaDB

### Describe the bug (required)
Activity pages skip entries when clicking on "Show more". (previous mention: https://discord.com/channels/309072240639737866/818499255349018624/1138262187626999859 )

### To Reproduce (optional)
1. For example, https://vocadb.net/ActivityEntry currently shows the range of "13 minutes ago ~ an hour ago", then continues with "4 hours ago ~ 5 hours ago"; "an hour ago" is the tail end of a long and conspicuous wave of entries, and "4 hours ago" predates it entirely.
2. User pages ( https://vocadb.net/User/EntryEdits/ [user ID] ) show similar behavior.

### Expected behavior (optional)
All entries are shown in proper chronological order.

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [ ] Tested on the **[beta site](https://beta.vocadb.net)**.
- [ ] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [x] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
The API seems to subtract 3 hours from the before parameter in the API (i.e. https://vocadb.net/api/activityEntries?before=2023-10-23T07:00:00.000Z returns activity entries before 2023-10-23T04:00:00.000Z instead). Possibly related to #1257.
