### ISSUE TITLE
New song type for self-cover

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#164]
Cover version is generally made by an artist other than the original. The term "cover" has strong association with "not my work". In the Vocaloid/UTAU world, it is common that the artist remakes their own songs with new voicebanks. In this case the term [self-cover](http://vocadb.net/T/391/self-cover) (セルフカバー on NicoNicoDouga) is used. Because it's a derived version and thus cannot be classified as "original version", the song type is "cover", but this offends some artists who don't want to be labeled as makers of cover songs.

If this really becomes a problem, we may need to add a new song type for self-covers. Most likely the new song type would be called "self-cover".

**Comment by ycanardeau** [comment]
[mentioned](https://discord.com/channels/309072240639737866/666326527197315091/849891711017811978)
