### ISSUE TITLE
Album artist texts don‘t update after a producer name change

### ISSUE THREAD

**Issue by Diva-333** [VocaDB/vocadb#1649]
### Website (required)
VocaDB (probably also affects UtaiteDB and TouhouDB)

### Describe the bug (required)
Album artists (artistString) don't get updated if a producer has their name changed. It's visible in both album view and list.

This is also true in the database (API artistString), as I discovered this when I tried labeling some of my albums using API calls and noticed API gave different values for Giga (Giga vs GigaP) depending on which string I tried to get.

It fixes itself only after submitting any edit to an affected album

### To Reproduce (optional)
1. Find an album that hasn't been edited since its producers name change, or simply change producer name
2. Check their recent/popular albums or try to search for them

### Screenshots (optional)
![image](https://github.com/VocaDB/vocadb/assets/52682533/a61d4909-a55c-4004-b4a6-671dc7cc27c1)
![image](https://github.com/VocaDB/vocadb/assets/52682533/a5521cda-4f62-41b7-9da7-47d3038192ee)

### Desktop
 - OS: Windows 10
 - Browser: Opera, Firefox

### Checklist 

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] ~~Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).~~ issue is serverside
- [x] ~~Checked in **private mode**.~~ issue is serverside
- [x] ~~Cleared **browser cache** and **cookies**.~~ issue is serverside

**Comment by saturclay** [comment]
[Here's an example from TouhouDB](https://touhoudb.com/Al/10929). Note how her name is listed as "Ying-Ying Ei" below, but is in Chinese at the top.
![Screenshot 2024-01-16 at 12 27 33 AM](https://github.com/VocaDB/vocadb/assets/142631139/87d523a4-c3de-4d1c-b3b4-4b39e2e3ef3e)
