### ISSUE TITLE
Unable to create album reviews

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1662]
### Website (required)
VocaDB

### Describe the bug (required)

Unable to create album reviews.

### To Reproduce (optional)
1. Go to https://beta.vocadb.net/Al/1/reviews
2. Click on "Write review"
3. Choose language (any)
4. Fill the textbox for review (minimum 50 characters)
5. Click "Post"
6. The page https://beta.vocadb.net/Al/1/reviews is shown, but the review is missing

#### Admin/ViewSysLog:
(No error)

#### Web console:
Uncaught (in promise) 
Object { stack: "mt@https://beta.vocadb.net/assets/index-2ca9fa05.js:38:12963\nuU@https://beta.vocadb.net/assets/index-2ca9fa05.js:40:1050\np@https://beta.vocadb.net/assets/index-2ca9fa05.js:40:4346\n", message: "Request failed with status code 400", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }

#### Web developer tools --> Network monitor:
POST: 
* Respone status: 400
* Response title: "One or more validation errors occurred." 
* Response error: "Could not convert string to DateTime: 27/01/2024. Path 'date', line 1, position 20."

### Desktop (optional)
 - OS: win10
 - Browser: FireFox 121.0.1

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] Checked in **private mode**.
- [x] Checked the **DevTools console**.
- [x] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
I'm unable to reproduce this on the main and the beta site.
