### ISSUE TITLE
Extra character in Album PV Internet Archive links

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#1679]
### Website (required)
VocaDB

### Describe the bug (required)
The Internet Archive link for an unavailable Album PV has a dollar sign preceding the URL; the resulting link is not recognized by the Internet Archive.

### To Reproduce (optional)
1. See https://vocadb.net/Al/24304 (4 unavailable links total); links to https://web.archive.org/web/*/$http://www.nicovideo.jp/watch/sm31556725 and https://web.archive.org/web/*/$https://youtu.be/CL_F1NE0diw, as well as https://web.archive.org/web/*/http://atols.blog.jp/archives/64999701.html

### Expected behavior (optional)
N/A

### Screenshots (optional)
N/A

### Desktop (optional)
N/A

### Smartphone (optional)
N/A

### Additional context (optional)
N/A

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
Already included in #1677. This issue will be automatic closed after the PR gets merged.
