### ISSUE TITLE
Display tag votes for trusted users

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1681]
Since trusted users can manage (= remove) tags, it would make sense to show the tag votes for them as well.

https://vocadb.net/Artist/ManageTagUsages/57876
https://vocadb.net/Song/ManageTagUsages/361312
https://vocadb.net/Album/ManageTagUsages/23130

Currently, tag votes are only visible to moderators.

### Checklist (required)

Fill out the checklist.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.

**Comment by FinnRG** [comment]
This would increase the group of people who can view this information by the factor 10 (15 -> ~150 users). Would it be good to discuss this further? Are there any objections from other admins/mods?

**Comment by Shiroizu** [comment]
No objections from the other mods: [#mods-and-trusted](https://discord.com/channels/309072240639737866/797103264655081492/1221334684638904441).

When some user action is available (tag removal), it makes sense to include the full context (tag voters).

Tag removals are trackable through [the audit log](https://vocadb.net/api/admin/audit-logs?filter=removed tag).
