### ISSUE TITLE
Piapro redesign 

### ISSUE THREAD

**Issue by MrZilty** [VocaDB/vocadb#1684]
After seeing Piapro's redesign (that i personally dislike), I went and checked some piapro links on VocaDB, and they're no longer working, they're showing the piapro 404 page.

**Comment by goomie** [comment]
To be more precise: I checked profile links and external links to songs, and they work correctly. However, the Piapro media player no longer interfaces with the VocaDB player.

**Comment by Susko3** [comment]
Would be useful to have some examples of links/entries that no longer work.

**Comment by goomie** [comment]
The aforementioned 404 error has been consistent with all Piapro embeds I have seen so far.
Popular songs on Piapro (manually switch to the embed to reproduce):
https://vocadb.net/S/1508
https://vocadb.net/S/1363
https://vocadb.net/S/1360
https://vocadb.net/S/2982
Sample songs only on Piapro:
https://vocadb.net/S/584714
https://vocadb.net/S/584712

**Comment by MrZilty** [comment]
Forgot to point out that right now it always says "Could not find id element on page." when i try to put a piapro link in the media section
