### ISSUE TITLE
Adding piapro media fails with "Could not find id element on page."

### ISSUE THREAD

**Issue by Susko3** [VocaDB/vocadb#1685]
### Website (required)
VocaDB

### Describe the bug (required)
Since the piapro redesign on 2024-02-27, adding piapro.jp media no longer works.

### To Reproduce (optional)
1. Edit a song
2. Switch to media tab
3. Try to add a piapro link, like https://piapro.jp/t/me04
4. See error: "Could not find id element on page."
5. The media is not added

Alternatively: go to https://vocadb.net/api/pvs?pvUrl=https%3A%2F%2Fpiapro.jp%2Ft%2Fme04&type=Original

### Expected behavior (optional)

Adding piapro media should work like it previously did.

### Screenshots (optional)

![image](https://github.com/VocaDB/vocadb/assets/16479013/4ec7e19f-dcc3-4599-a23d-116f78876158)

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [ ] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [ ] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [x] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by andreoda** [comment]
related: https://github.com/VocaDB/vocadb/issues/1684#issuecomment-1967262479
