### ISSUE TITLE
Replace broken links leading to "Help/About" and old Wiki pages

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1714]
The "Help/About" page got removed from the sidebar but we forgot to replace the links forwarding to it.
One example is the "guide" link when being on draft entries: 
![Screenshot_20240313-085514](https://github.com/VocaDB/vocadb/assets/52045122/42f5d945-d268-47d5-9368-0e34f97a4c97)
*Screenshot by szhublox*
Leading to an error page: https://vocadb.net/Help/guidelines#glsongs

We need to find all and forward them to the specific VocaDB Wiki articles instead.

**Comment by szhublox** [comment]
Additionally, the tooltip on the song edit page
> Primary name (in one or more languages)

references "the guide" rather than the wiki. It's not a link though

**Comment by andreoda** [comment]
Note: The old Wiki got replaced with the new Wiki, so we need to replace links leading to that as well.

**Comment by FinnRG** [comment]
> Note: The old Wiki got replaced with the new Wiki, so we need to replace links leading to that as well.

We have redirects for the old wiki urls. Do you know of links that don't redirect properly (There were some reorganizations which could have broken some of them)?

**Comment by andreoda** [comment]
@FinnRG 
For example: I replaced a link on this page: https://vocadb.net/discussion/topics/637 leading to the old wiki which resulted in an error page.
I am assuming that other discussion posts and comments or entries contain broken links.

**Comment by mn7216** [comment]
As a quick note: Both the "guidelines" link and "Frequently asked questions" links are broken [on this wiki page](https://wiki.vocadb.net/docs/pinned/quick-guide-for-new-editors)

**Comment by saturclay** [comment]
These links are broken on TouhouDB and UtaiteDB as well; would it be possible when fixing them to have them link to different pages for each site?
