### ISSUE TITLE
Niconico thumbnails for entries created before mid-2019 are "blocked by OpaqueResponseBlocking"

### ISSUE THREAD

**Issue by goomie** [VocaDB/vocadb#1722]
### Website
**VocaDB** / **UtaiteDB** / **TouhouDB**

### Describe the bug

A large percentage of Niconico thumbnails on all of the live websites are not loading correctly, despite loading correctly in the past. Previously, this behavior would only occur when trying to fetch thumbnails of deleted videos. This bug is seemingly less than 12 hours old.

![Capture](https://github.com/VocaDB/vocadb/assets/40348837/fc4bb53d-c94b-4590-ae62-00b700d5c9cf)

By sorting through various searches, it becomes clear that there is a cutoff point right in the middle of 2019, prior to which most Niconico embeds are unreliable. [Example of search results on top of the date cutoff.](https://vocadb.net/Search?searchType=Song&artistParticipationStatus=Everything&childTags=false&childVoicebanks=false&draftsOnly=false&filter=&maxLength=0&minLength=0&onlyRatedSongs=false&onlyWithPVs=false&page=224&pageSize=10&songType=Unspecified&sort=AdditionDate&tagId%5B0%5D=262&unifyEntryTypesAndTags=false&viewMode=Details) (Note that if an entry fetches a thumbnail from a different embed, it will still work correctly.) There are some entries created after this cutoff affected by the bug ([example 1](https://vocadb.net/S/251001), [example 2](https://vocadb.net/S/250700)), as well as older entries that are unaffected ([example](https://vocadb.net/S/30867)), but these are exceptions.

In the browser console, the following message is generated for each failed thumbnail: _The resource at “[url]” was blocked by OpaqueResponseBlocking. Reason: “after sniff: status code is not in allowed range”._ Trying to open the image in a new tab may either fail to redirect to the thumbnail (displaying Http/1.1 Service Unavailable) or directly show an "Access Denied" message at the thumbnail's URL.

Deleting and re-adding the PV in a single edit is enough to successfully re-fetch the thumbnail for that entry. Tested [here](https://vocadb.net/S/634).

### Checklist

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**. (This site loaded thumbnails correctly until I cleared my cache, after which it was affected.)
- [x] Tested on different browsers (e.g. **Firefox**, **Chrome**, ~~**Safari**~~, ~~**Edge**~~).
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** ~~and **cookies**.~~
- [x] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
It seems like the thumbnail domain `tn.smilevideo.jp` doesn't work anymore. We might need to migrate to `https://nicovideo.cdn.nimg.jp/thumbnails/<video_id>/<video_id>`
