### ISSUE TITLE
Release event tooltip shows wrong text

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1738]
### Website
VocaDB

### Describe the bug
Release event tooltip shows "Release.OccurrenceDate" instead of "Date" or "Event date"

Example: 
![grafik](https://github.com/VocaDB/vocadb/assets/52045122/1b40da94-82a3-49bd-a79d-3359ed7c4d44)
Entry: https://vocadb.net/Al/30968

**Comment by FinnRG** [comment]
Fixed in 22581803bca4371f359f29ee369f90fc5ba68e2b.
