### ISSUE TITLE
Changing the text box watermark/placeholder for the comment/discussion section

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1743]
Currently, the placeholder text says "Write a comment".
I think the text could be changed to show comment/behaving guidelines (to encourage better comments and less spamming or rude behavior).

Examples:

"be responsible. do not post unwanted personal data/sensitive information and follow the rules on how to behave. be careful on what you share online"

or

![image](https://github.com/VocaDB/vocadb/assets/52045122/7aa96373-4667-4e8f-ae8a-470f200dcada)
_Screenshot by Shiroizu_

or in general some lines from the Wiki article: https://wiki.vocadb.net/docs/pinned/discussion-rules

**Comment by FinnRG** [comment]
@andreoda This can be updated in Crowdin

**Comment by andreoda** [comment]
I am reopening this issue again since it was only implemented for the German language and not the English one, even though it was added to Crowdin at the same time.

**Comment by FinnRG** [comment]
@andreoda What do you want as the new comment placeholder? I'll try updating it directly in the source code

**Comment by andreoda** [comment]
It is already in Crowdin, last time I added both the English and the German line but only the German one was implemented.

**Comment by FinnRG** [comment]
Completed in da8de4d.
