### ISSUE TITLE
Propose draft changes & entry reports for the wiki

### ISSUE THREAD

**Issue by mn7216** [VocaDB/vocadb#1744]
## The issue
The wiki is a useful resource, but there is a good deal of missing information and broken links on it, which can cause confusion among editors. new editors in particular. Currently, there does not seem to be a dedicated way to point out errors or gaps in info for wiki pages; the de facto way to go seems to be in discord, but this has the weakness of not having a persistent, visible entry report, so these discord messages can often be forgotten about or overshadowed.

## Proposal
The ability for users to submit entry reports on wiki pages could help with the addition of more relevant information which might have been overlooked, and fixing errors. In addition to this, I also think a very useful change (and perhaps the more important one) would be the ability for users (I think Trusted User and up) to submit changes to wiki pages, which then would be reviewed by Admins before being approved or denied.

## Alternatives
- Possibly, having a dedicated wiki discussion discord channel
- Dedicated discussion forum for the wiki using the DB's discussions feature.

I think these alternatives are much weaker than the proposed changes, though.

## Additional Context:

The wiki does not provide information on many common practices of the DB, here's a few from my experience:
   - That you shouldn't add the artist's personal description to the "Description" field.
   - Whether or not adding songs to the DB that have not been officially uploaded, but HAVE been played at a live venue, is allowed.
   - That remastered covers should generally be marked as "covers" and tagged with the "remastered cover" tag, rather than as "Remaster" song type.

Allowing the ability to submit changes to pages in particular would allow for both admins to become aware of confusion regarding a particular rule, review the changes and come to a consensus on what the correct course of action is, provide more information for users, and generally make the wiki more useful.

### Checklist (required)

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.

**Comment by Shiroizu** [comment]
1) The wiki repository supports issues and pull requests: https://github.com/VocaDB/Wiki

2) Questions can also be posted as [discussion topics](https://vocadb.net/discussion/folders/1).

3) I also accept messages (on VocaDB & discord) regarding the wiki.

4) I also opened a separate discord channel for wiki-related questions and suggestions: #vocadb-wiki.

----

> You shouldn't add the artist's personal description to the "Description" field.

I will clarify this on https://wiki.vocadb.net/docs/songs/song-entry-editing#song-description

> Whether or not adding songs to the DB that have not been officially uploaded, but HAVE been played at a live venue, is allowed.

Generally entries that are not specifically denied on the [content policy](https://wiki.vocadb.net/docs/other-guidelines/content-policy) are accepted.

> That remastered covers should generally be marked as "covers" and tagged with the "remastered cover" tag, rather than as "Remaster" song type.

The guidelines for this are documented at https://vocadb.net/T/8811

Currently, the tag <--> wiki guideline-integration is still underway. The progress can be viewed on [this comment on #mods-and-trusted](https://discord.com/channels/309072240639737866/797103264655081492/1224845199725822043).
