### ISSUE TITLE
SoundCloud parser failing 

### ISSUE THREAD

**Issue by szhublox** [VocaDB/vocadb#1745]
### Website (required)
VocaDB

### Describe the bug (required)
Adding media with a SoundCloud URL claims the link is invalid

### To Reproduce (optional)
1. Go to submit song or song editor
2. Add SoundCloud URL

### Screenshots (optional)
https://discord.com/channels/309072240639737866/666326527197315091/1233339621342187542

### Smartphone (optional)
 - Device: Android
 - Browser: Firefox, chrome (fresh profiles)

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- [x] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and **cookies**.
~~- [ ] Checked the **DevTools console**.~~
~~- [ ] Checked the **syslog** (mods+ only).~~

**Comment by FinnRG** [comment]
Short update: It seems like our SoundCloud token was revoked. We didn't receive any warning and SoundCloud doesn't respond to support requests and new API access applications. I'll wait a few more days for a response and experiment with possible workarounds.
