### ISSUE TITLE
Search broken on "Submit a new album" page

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1759]
### Website
VocaDB

### Describe the bug
On the submit page for albums, the "search for duplicates" system does not seem to work in some cases. Specific case with the album name "恋​は​り​ん​り​ん"​.

### To Reproduce
1. Go to https://vocadb.net/Album/Create
2. Type in "恋​は​り​ん​り​ん​"
3. See no duplicates being found

### Expected behavior
Normally, it should reveal that there are already albums with that name.
- https://vocadb.net/Al/33659
- https://vocadb.net/Al/41728

### Screenshots
![grafik](https://github.com/VocaDB/vocadb/assets/52045122/8dae994c-bf1d-41fa-a5d3-c199e23c5e6f)

### Desktop
 - OS: Windows
 - Browser: Firefox

### Additional context
The normal search gives the proper results: https://vocadb.net/Search?filter=%E6%81%8B%E2%80%8B%E3%81%AF%E2%80%8B%E3%82%8A%E2%80%8B%E3%82%93%E2%80%8B%E3%82%8A%E2%80%8B%E3%82%93%E2%80%8B&searchType=Album

![grafik](https://github.com/VocaDB/vocadb/assets/52045122/92c40fdf-e8d1-4e20-b2c0-f9c135bb2bc9)

**Comment by Shiroizu** [comment]
The FindDuplicate -API (see the browser/network-tab) only searches for exact matches.

"恋​は​り​ん​り​ん​" does not correspond to any album titles: https://vocadb.net/Search?searchType=Album&filter="恋%E2%80%8Bは%E2%80%8Bり%E2%80%8Bん%E2%80%8Bり%E2%80%8Bん"

The form works as intended when the whole title is inputted: "恋​は​り​ん​り​ん​／​浮​か​ぶ​ハ​ン​バ​ー​ガ​ー"

**Comment by Shiroizu** [comment]
Additionally, the example string seems to contain ZWSP-characters: https://en.wikipedia.org/wiki/Zero-width_space

![image](https://github.com/VocaDB/vocadb/assets/15908050/509ce9e4-d997-4f13-b0e5-72e8f45772b6)

(Notepad++ --> View --> Show Symbol --> Show All Characters)

This probably caused the initial confusion as these are not displayed.
