### ISSUE TITLE
Tagalog and Tajik language codes are mixed up

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#1784]
### Website (required)
VocaDB

### Describe the bug (required)
`tg` is Tagalog/Filipino in the short languages list and Tajik in the full languages list. (It should be  `tl` Tagalog/Filipino and  `tg` Tajik.)

### To Reproduce (optional)
1. Open the edit window of https://vocadb.net/S/161777
2. Navigate to the Lyrics tab; open Original
3. Click on `More language options`; `Filipino` will change to `Tajik`

### Expected behavior (optional)
The language codes are used correctly and consistently.

### Additional context (optional)
Encountered while running the script to migrate from language tags to the new entry/lyrics language system.

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [ ] Tested on the **[beta site](https://beta.vocadb.net)**.
- [ ] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [ ] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by FinnRG** [comment]
Fixed in 0ade14c6280d7bead4fe92ee97c9a599061e4754.

**Comment by Susko3** [comment]
It's fixed in code, but what about the existing entries that are now tagged with the wrong language?

**Comment by FinnRG** [comment]
@Susko3 They will need to be manually checked once the new version is deployed on the main site.
