### ISSUE TITLE
Auto fill-in titles of a cover on the song addition page when the original is selected

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#179]
Consider the following suggestion --

Clicking "Select" on the original song when adding a cover should also fill in all three titles of the cover to be added, from the song that the user has selected.

Example: https://lut.im/Y6f3Wt75iA/JuUJuEABXhIQ21G9.png
In this case after clicking "Select" the "Non-English" and "Romanized" names should be automatically filled in.

Currently this needs to be done manually via first opening the original in a new browser tab and then copy-pasting each title into its field on the song addition page, which is inconvenient.

Thanks

**Comment by riipah** [comment]
I'll think about it, but it will be low priority

**Comment by riipah** [comment]
I assume that if the cover is named differently then the names should not be copied? What about copying aliases or the default name selection? Those aren't currently on the submission form page, so they'd need to be added.

**Comment by romanrm** [comment]
When a cover is titled differently, very often the difference consists of adding some "(Piano arrange)", "(Ballad version)" or "(House remix)" to the original title. In this case I could still see filling in of the original titles into empty fields as being useful, what's left to the user is only to also copy the same addition to each of them, which should be pretty obvious. Just that the priority should be given to user input, i.e. don't auto-overwrite any title that was already explicitly entered.

As for other considerations, I can see it's important to not overcomplicate the submission page; and for that matter I don't think it's as critical to copy ALL possible aliases to each cover (some songs have tons of "translation variants", etc), just the three standard names seems enough. For the default name selection, the Non-English one being selected as primary by default if present, appears to work well in great majority of cases.

**Comment by romanrm** [comment]
How about a "Submit a cover" button, from a song page?  
It could open the song addition page with all three titles pre-filled, song type set to Cover, and Original version already selected.

**Comment by riipah** [comment]
I don't think that's needed. It's useless clutter for those just browsing the site, which is majority of the users. I could add the parameters for the submission page though, if you'd like to write a greasemonkey script for yourself.

**Comment by dset0x** [comment]
This would perhaps be easier to work with if it was a button named e.g., "Load data from Original" within the "New Song" page.

**Comment by Shiroizu** [comment]
Continued at #811
