### ISSUE TITLE
Piapro embeds failing since June

### ISSUE THREAD

**Issue by goomie** [VocaDB/vocadb#1798]
### Website
**VocaDB** / UtaiteDB / TouhouDB

### Describe the bug

Attempting to add a Piapro link as media returns the error "Could not find id element on page" and fails to add an embed, forcing users to add Piapro links under the links section. This bug seems to have existed since early June ([example](https://vocadb.net/S/637945)), and is likely a known issue, but has not yet been reported here.

### To Reproduce 
For existing songs:
1. Edit page
2. Click on "Media" tab
3. Add a Piapro link as media
4. Receive error: "Could not find id element on page."

For new songs:
1. Click "Submit a song"
2. Insert the Piapro link and populate relevant fields
3. Attempt to save
4. Receive the errors "Bad request" and "Could not find id element on page."

### Checklist

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**. (Same behavior)
- [ ] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [ ] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [x] Checked the **DevTools console**. *
- [ ] Checked the **syslog** (mods+ only).

\* Fail state from the new song page returns this error:
```
 Uncaught (in promise) 
 Object { stack: "mt@https://vocadb.net/assets/index-71051649.js:38:12958\nuU@https://vocadb.net/assets/index-71051649.js:40:1050\np@https://vocadb.net/assets/index-71051649.js:40:4346\nEventHandlerNonNull*vU</<@https://vocadb.net/assets/index-71051649.js:40:4418\nvU<@https://vocadb.net/assets/index-71051649.js:40:3324\nJS@https://vocadb.net/assets/index-71051649.js:42:512\nrequest@https://vocadb.net/assets/index-71051649.js:42:4173\nr/<@https://vocadb.net/assets/index-71051649.js:42:4630\nNO/<@https://vocadb.net/assets/index-71051649.js:38:7683\nEU/<@https://vocadb.net/assets/index-71051649.js:42:7978\nOV/<@https://vocadb.net/assets/index-71051649.js:45:36762\no/<@https://vocadb.net/assets/SongCreate-79cb677f.js:1:3922\nzx@https://vocadb.net/assets/index-71051649.js:46:7609\ni@https://vocadb.net/assets/index-71051649.js:46:7471\nonSubmit@https://vocadb.net/assets/SongCreate-79cb677f.js:1:6702\nasync*W7@https://vocadb.net/assets/index-71051649.js:105:9864\nK7@https://vocadb.net/assets/index-71051649.js:105:10018\nY7@https://vocadb.net/assets/index-71051649.js:105:10075\ndT@https://vocadb.net/assets/index-71051649.js:105:31482\nBR@https://vocadb.net/assets/index-71051649.js:105:31901\nxy/<@https://vocadb.net/assets/index-71051649.js:105:36814\nm1@https://vocadb.net/assets/index-71051649.js:108:36956\nhR@https://vocadb.net/assets/index-71051649.js:105:8999\nxy@https://vocadb.net/assets/index-71051649.js:105:33188\nHw@https://vocadb.net/assets/index-71051649.js:105:17378\ncK@https://vocadb.net/assets/index-71051649.js:105:17160\n", message: "Request failed with status code 400", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }
[SongCreate-79cb677f.js:1:6848](https://vocadb.net/assets/SongCreate-79cb677f.js)
```

**Comment by FinnRG** [comment]
Fixed with https://github.com/VocaDB/vocadb/commit/a5b8997058895d256a945f831de9cde09a45582a.
