### ISSUE TITLE
Song addition - Autofill not working as expected

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1802]
### Website
VocaDB

### Describe the bug
When trying to add certain videos from NND, the autofill does not work correctly.

### To Reproduce
1. Go to https://vocadb.net/Song/Create
2. Input the URL https://www.nicovideo.jp/watch/sm43910094
3. See nothing getting filled automatically

### Expected behavior
The system should at least fill in the name "FLY AWAY (feat.初音ミク)".

### Screenshots
![image](https://github.com/user-attachments/assets/7b0a00c6-c912-466f-9c6a-b0e359b8e1f3)

### Additional context
Browser console output errors (some appear in German):

15:09:12.568 GET
https://vocadb.net/Song/Create
[HTTP/2 200  60ms]

15:09:12.659 Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. Create
15:09:12.694 XHRGET
https://vocadb.net/api/songs/findDuplicate?term[]=&term[]=&term[]=&pv[]=https://www.nicovideo.jp/watch/sm43910094&pv[]=&getPVInfo=true
NS_BINDING_ABORTED

(...)

15:09:13.613 XHRGET
https://vocadb.net/api/entry-types/Song/Original/tag?fields=Description&lang=Default
[HTTP/2 200  61ms]

15:09:13.614 Fehler beim Verarbeiten des Wertes für 'transition'.  Deklaration ignoriert. Create:1:4
15:09:13.672 XHRPOST
https://vocadb-analytics.fly.dev/api/send
[HTTP/2 200  425ms]

(...)

15:09:38.160 XHRGET
https://vocadb.net/api/songs/findDuplicate?term[]=&term[]=&term[]=&pv[]=https://www.nicovideo.jp/watch/sm43910094&pv[]=&getPVInfo=true
[HTTP/2 500  40755ms]

15:09:48.103 Uncaught (in promise) 
Object { stack: "mt@https://vocadb.net/assets/index-a80ecd3f.js:38:12958\nuU@https://vocadb.net/assets/index-a80ecd3f.js:40:1050\np@https://vocadb.net/assets/index-a80ecd3f.js:40:4346\nEventHandlerNonNull*vU</<@https://vocadb.net/assets/index-a80ecd3f.js:40:4418\nvU<@https://vocadb.net/assets/index-a80ecd3f.js:40:3324\nJS@https://vocadb.net/assets/index-a80ecd3f.js:42:512\nrequest@https://vocadb.net/assets/index-a80ecd3f.js:42:4173\nGp.prototype[t]@https://vocadb.net/assets/index-a80ecd3f.js:42:4478\nNO/<@https://vocadb.net/assets/index-a80ecd3f.js:38:7683\nEU/<@https://vocadb.net/assets/index-a80ecd3f.js:42:7885\nOV/<@https://vocadb.net/assets/index-a80ecd3f.js:45:32733\no/<@https://vocadb.net/assets/SongCreate-d5896c47.js:1:2943\no/<@https://vocadb.net/assets/SongCreate-d5896c47.js:1:3432\nW7@https://vocadb.net/assets/index-a80ecd3f.js:105:9864\nK7@https://vocadb.net/assets/index-a80ecd3f.js:105:10018\nY7@https://vocadb.net/assets/index-a80ecd3f.js:105:10075\ndT@https://vocadb.net/assets/index-a80ecd3f.js:105:31482\nBR@https://vocadb.net/assets/index-a80ecd3f.js:105:31901\nxy/<@https://vocadb.net/assets/index-a80ecd3f.js:105:36814\nm1@https://vocadb.net/assets/index-a80ecd3f.js:108:36956\nhR@https://vocadb.net/assets/index-a80ecd3f.js:105:8999\nxy@https://vocadb.net/assets/index-a80ecd3f.js:105:33188\nHw@https://vocadb.net/assets/index-a80ecd3f.js:105:17378\ncK@https://vocadb.net/assets/index-a80ecd3f.js:105:17160\nEventListener.handleEvent*HR@https://vocadb.net/assets/index-a80ecd3f.js:105:32697\nOy@https://vocadb.net/assets/index-a80ecd3f.js:105:32097\ncd/<@https://vocadb.net/assets/index-a80ecd3f.js:105:32263\ncd@https://vocadb.net/assets/index-a80ecd3f.js:105:32208\nMY@https://vocadb.net/assets/index-a80ecd3f.js:108:53260\ncv@https://vocadb.net/assets/index-a80ecd3f.js:108:53477\nfi.render@https://vocadb.net/assets/index-a80ecd3f.js:108:57021\n@https://vocadb.net/assets/index-a80ecd3f.js:325:2693\n", message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…} }
2 SongCreate-d5896c47.js:1:2943

**Comment by FinnRG** [comment]
I can't reproduce this. Maybe there was an error with the NND API at that time? NND still isn't completely stable yet.

**Comment by andreoda** [comment]
True, I tried it just now and it worked again. Strange.
