### ISSUE TITLE
Keep multiple days events longer on front page

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1814]
The [front page](https://vocadb.net/) and the "[Upcoming events](https://vocadb.net/Event)" page do not display events that are ongoing for multiple days/months long enough.

Example events:

Multiple days:
https://vocadb.net/E/8021
https://vocadb.net/E/7723

One day:
https://vocadb.net/E/7979
https://vocadb.net/E/3424

To solve this, the events can either be displayed as long as the event dates are set or a separate tab/separation can be added to the front page and the upcoming events page to display exclusively multiple days events.

Related: https://github.com/VocaDB/vocadb/issues/1598

**Comment by FinnRG** [comment]
I won't change the behavior for https://vocadb.net/Event because it is explicitly called "Upcoming events". We can consider adding a new "Ongoing events" section with the same behavior as the frontpage "Happening now" section, but that needs to be a separate issue.

**Comment by andreoda** [comment]
@FinnRG good point and I agree with this approach. I will open a new issue about that in a bit. Thanks for your feedback!
