### ISSUE TITLE
SoundCloud media not displaying thumbnail

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1815]
### Website
VocaDB

### Describe the bug
Some song entries do not show or load the images/thumbnails from SoundCloud links.

Example:
Song entry: https://vocadb.net/S/682309

The SoundCloud link has an image/thumbnail:
![grafik](https://github.com/user-attachments/assets/29becc62-37d9-42ea-b61d-f56cbc6cfc1d)

The song entry itself shows a black image:
![grafik](https://github.com/user-attachments/assets/c7bff143-20ab-4c64-b523-8a42af6a048e)

Viewing it from a list of songs it shows that the thumbnail is missing/corrupted:
![grafik](https://github.com/user-attachments/assets/09be4f02-4e84-4127-9ae9-e52884c31ba2)

Trying the maintenance actions on the entry does not fix the issue.

Additional info:

![image](https://github.com/user-attachments/assets/cb022829-00bd-4c9c-9613-87ce23ffcf78)
Screenshot by Shiroizu

Context: https://discord.com/channels/309072240639737866/666326527197315091/1291682763803459606

**Comment by FinnRG** [comment]
This should be fixed now.
