### ISSUE TITLE
Valid swagger API

### ISSUE THREAD

**Issue by jsmnbom** [VocaDB/vocadb#188]
Hello riipah,
I was wondering if it would be possible to update the API such that it is valid swagger. Currently it works fine with the swagger ui, but because of a few errors in the definitions it is not possible to use with swagger-codegen.
I'm not entirely sure how hard it would be to fix, but I realise that changes may not be backwards compatible (and therefore require a v2 api) and you therefore don't want to do it.
Thanks in advance,
bomjacob.

**Comment by riipah** [comment]
What's the error you're getting? According to Swagger UI and http://bigstickcarpet.com/swagger-parser/www/index.html it's valid (http://vocadb.net/swagger/docs/v1)

**Comment by bomjacob** [comment]
Using that swagger validater I'm getting the following error:
```
missed comma between flow collection entries at line 1, column 95067:
     ... javascript","application/json-p"],"parameters":[{"name":"songId" ... 
                                         ^
```
But if I'm using the official editor/validator (which is what swagger-codegen relies on) I get the following errors:
![](http://i.imgur.com/9k30nMq.png)

And on http://vocadb.net/swagger/ui/index this is displayed in bottom right corner:
![](http://i.imgur.com/SlpfHRE.png)

Granted, it could just be a problem with my browser and the codegen I used... but I'm not sure.

**Comment by riipah** [comment]
That is really strange because the validator parses it just fine for me:

![image](https://cloud.githubusercontent.com/assets/550886/17441185/824f5710-5b38-11e6-853f-2ac9ed35d02b.png)

And the indicator at http://vocadb.net/swagger/ui/index says it's valid too 
![image](https://cloud.githubusercontent.com/assets/550886/17441190/936e8cdc-5b38-11e6-98d7-1b1f0010c29d.png)

**Comment by riipah** [comment]
At http://editor.swagger.io/#/ I'm getting the same errors are you are, but I can't find the duplicate paths, so I don't know what's wrong.

**Comment by riipah** [comment]
Looking at https://github.com/apigee-127/sway/issues/32, it seems that Swagger doesn't support endpoints that differ only by the HTTP method used. We have both GET /api/albums/{id} and DELETE /api/albums/{albumId}, which is the problem for Swagger apparently. I think those paths are properly RESTful so I'm reluctant to change them. I can try to research how this is solved in Swagger normally.

**Comment by bomjacob** [comment]
That's very strange. Even stranger is that even I open up http://vocadb.net/swagger/ui/index in another browser it knows neither the "error" nor the "valid" tag, so not sure what's going on there.
Currently, it's not a big issue for me personally, since I'm just using the API directly, but it would perhaps be nice to be able to use codegen for future projects.

**Comment by riipah** [comment]
I unified the parameter names and now swagger editor it's no longer showing errors. Can you try it again?

**Comment by bomjacob** [comment]
I'm not entirely sure what you mean by that. But it seems to be working now (haven't tested codegen but everything else checks out).
Won't this break backwards compatibility with other apps though?

**Comment by riipah** [comment]
The API itself isn't changed at all, just the generated Swagger markup.

I had for example
* GET /api/albums/{id} (for getting album)
* DELETE /api/albums/{albumId} (for deleting album)

The difference in the name of the placeholder (id vs. albumId) made Swashbuckle treat them as separate paths, even though they're supposed to be the same (both are called using /api/albums/123), just different verbs (verbs should be grouped under paths in the YAML). So the only difference is in how the Swagger documentation is generated, using the API is unchanged.
