### ISSUE TITLE
Not showing tags in search when searching "anything"

### ISSUE THREAD

**Issue by bomjacob** [VocaDB/vocadb#189]
When search is set to "anything" and tag showing is on, it is not showing any tags, only the commas that would be separating them.
This is how it looks:
![](http://i.imgur.com/kukgpjj.png)
This is how (i assume) it should look:
![](https://cloud.githubusercontent.com/assets/3002987/17437525/722ac97e-5b1e-11e6-9870-0908395bca68.png) (ignore the bad photoshop edit])

I should note that it shows fine when searching for artists, albums or songs.

**Comment by riipah** [comment]
fixed
