### ISSUE TITLE
Pagination error when searching albums

### ISSUE THREAD

**Issue by jsmnbom** [VocaDB/vocadb#197]
When searching for "The end" in the album api. Some results are shown multiple times instead of the proper ones.
Here I request 3 songs starting at 0.
http://vocadb.net/api/albums?query=the%20end&start=0&maxResults=3&getTotalCount=true&sort=NameThenReleaseDate&preferAccurateMatches=true&nameMatchMode=Auto&lang=Romaji
Doing that, it returns the following 3 albums:
1. The End by OwataP
2. The end of begin all by ROY
3. The End of One Story by TinySymphony

Which is what you'd expect since they match the name most accurately.
But when I try to start at item 15 I get the _exact_ same 3 albums instead of the ones that were supposed to be there.
http://vocadb.net/api/albums?query=the%20end&start=15&maxResults=3&getTotalCount=true&sort=NameThenReleaseDate&preferAccurateMatches=true&nameMatchMode=Auto&lang=Romaji

Moreover, when I request 10 albums I get these results: https://gist.github.com/bomjacob/3d2b87ce5e98a870755a8df157d9ac47
There you can see that The End of the World by UN ELITE NEET is album number 4.
But when I try to request 10 albums starting at 1, I get completely different results, even though I'd have expected no other change than The End of the World by UN ELITE NEET moving to number 3. (https://gist.github.com/bomjacob/d3de399d25db8fdce8ffd988e6184b1a)

Note that the total counts has stayed constant at 23 throughout the whole process.

**Comment by riipah** [comment]
PreferAccurateMatches is intended for autocomplete boxes, it doesn't support pagination. This is stated in the api docs

**Comment by bomjacob** [comment]
Oh sorry, my bad. It seems to work perfectly fine with songs so I never noticed the problem till now. I'll remove the PreferAccurateMatches now though, thanks :)

**Comment by riipah** [comment]
There might be some inconsistency in which takes priority when both preferAccurateMatches and pagination are specified, but the point is that those are not supported together

**Comment by bomjacob** [comment]
Alright, I'll keep that in mind. Thanks for your help.

**Comment by bomjacob** [comment]
@riipah Not stictly related to this issue, but I thought I'd ask it here instead of opening a new issue.
How would one go about logging in using the api?
Some api docs say "Login required" others say "Authorization cookie must be included." are those the same? If so, what are they? I see that each user has an acess key in their settings page, and I'm assuming it's to do with that, but I'm a bit lost as to how to use it...

**Comment by riipah** [comment]
Yes those are the same. It means you need to have the login cookie from the site. You can also get that by posting to /User/Login, the response includes a cookie that you'd pass to those APIs that require it. Currently there's no API for logging in with the access key...

**Comment by bomjacob** [comment]
So that mean I either have to parse both username and password or somehow instruct users on how to extract cookies from their browsers?

**Comment by riipah** [comment]
What would you use it for? I could make API for logging in with the access key...

The cookie behaves exactly like when logging in from the website. Currently the cookie stays valid for 7 days, unless refreshed by visiting the site.

**Comment by riipah** [comment]
If you're calling the API with JavaScript and the user is already logged in on the website, the cookie should  be delivered automatically and the user can use the authenticated APIs

**Comment by bomjacob** [comment]
Unfortunately I don't interact with the user in a web browser at all (I'm making that telegram bot).
I guess I could make a tiny web app that simply redirects the user to vocadb to login and afterwards redirects them to the bot again but since that would look something like:
User asks to login > send webapp login link > user clicks link > user get's redirected to vocadb to login > user has to get back to the webapp somehow > webapp captures the cookie and saves it > user is redirected to bot (using special links)
It doesn't really seem user friendly.
It would also be possible to just link users to like http://www.wikihow.com/View-Cookies to extract the cookie, but that again doesn't seem particulary user-friendly and if you have to refresh every 7 days it could get annoying (though I guess I could send a "keep-alive" request on the behalf of the user)

**Comment by riipah** [comment]
Well, in any case you'd need the user-specific credentials somehow, whether that's username/password or the access key. You still didn't explain what you'd use the authentication for.

**Comment by bomjacob** [comment]
Yeah that is true :/ (I'd much rather use something like the access key than asking for user+pass though)
The use would be allowing users to rate (that is, like or favorite) songs from within the telegram bot. See the bottom two buttons on this mockup for example:
![image](https://cloud.githubusercontent.com/assets/3002987/18099142/772e015e-6ee5-11e6-8dbf-4e270d9f4b3b.png)

**Comment by riipah** [comment]
Yes, if you're asking something from the user it should be the access key. So the bot knows who's calling it and you can store the user's authentication credentials (either the access key or login cookie) in its memory?

**Comment by bomjacob** [comment]
Yes that is correct, it has an internal database (where I'm also storing language preferences and such).

**Comment by riipah** [comment]
How secure is it? Keep in mind that if the credentials are leaked, the hacker has full access to the user's account.

**Comment by riipah** [comment]
A limited access using the access key would be more secure, but more work for me to implement.

**Comment by riipah** [comment]
Either that, or the cookie would have to be very short lived...

**Comment by bomjacob** [comment]
It's running on a Ubuntu 16 LTS DigitalOcean droplet with all the security features that I know of activated (SSH only using keys, no root access, strong firewall and such). The "weak" point would probably be the fact that the key would be transmitted over telegrams servers (and also be in the users chat log which anyone with access to the users telegram account - that is their phone, pc or login - could read it)
If the cookie is very short lived would that mean that users would have to login often?

**Comment by riipah** [comment]
Well what I'd really like to have is proper OAuth authentication. Everything else is more or less temporary. It's going to be more work than I can handle any time soon though. Even that temporary solution is going to be several hours of work because I don't want to rush it.

**Comment by riipah** [comment]
I submitted #198
