### ISSUE TITLE
The ability to link directly to help/about tabs.

### ISSUE THREAD

**Issue by bomjacob** [VocaDB/vocadb#207]
Would it be possible to make it such that you can link directly the help/about page about fx. Vocaloid.
Perhaps doing something like:
`http://vocadb.net/Help#Vocaloid`

**Comment by riipah** [comment]
Like http://vocadb.net/Help#aboutvocaloid ?

**Comment by bomjacob** [comment]
Yes exactly like that, sorry for not noticing that that was possible! (the url in your browser doesn't exactly update when you click the tabs)
