### ISSUE TITLE
Date format YYYY.MM.DD

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#224]
[Requested](http://vocadb.net/discussion/topics/54).

Current date formats are based on .NET cultures. The closest we have is YYYY/MM/DD for the Japanese culture. There is no commonly used culture with the "." separator, so  a custom culture needs to be defined.

We could add a new user setting for date format, to allow choosing the date formatting independently from culture. This could replace the current "Date and number formatting" setting.

How to handle time formatting? If the user wants YMD with 24 or 12 hour clock? Do we still need a separate setting for number formatting?

**Comment by romanrm** [comment]
Consider supporting https://en.wikipedia.org/wiki/ISO_8601 instead, if that requires a culture, that one can be "International".

**Comment by riipah** [comment]
The cultures are tied to .NET cultures. There's "invariant culture", but it uses MDY pattern. This will require separating date formatting from the culture setting.

**Comment by riipah** [comment]
I still want to hear more about the use case: why do you need the dates formatted in a specific way?
