### ISSUE TITLE
Add entries for event venues

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#275]
Could be used to reuse event venue information such as name, location and web address.

Venue management should be as lightweight as possible: a new venue can be created from event page. We still probably need a page for listing venues so that they can be deleted as necessary.

Who can create/edit venue information?

**Comment by riipah** [comment]
@ycanardeau I made some fixes (changed lat/long input to number, fix display in cultures that use comma).

Could you add the address field to venue edit page?

**Comment by ycanardeau** [comment]
Thanks for your fixes. Do you think only the address field is enough, or should I add separate fields for country, state and street address so that we can search for venues by country?

**Comment by riipah** [comment]
Separate field for country (saved as [2 letter ISO 3166 country code](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.regioninfo.twoletterisoregionname?view=netframework-4.8)) sounds like a good idea. Rest of the address can be one field.

**Comment by riipah** [comment]
@ycanardeau seems that Venue/Edit.ts/js is missing. Can you add that file?

**Comment by ycanardeau** [comment]
Added.

**Comment by riipah** [comment]
Thank you again, this is now in production.
