### ISSUE TITLE
Simple discussion forum on VocaDB

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#28]
We need to make it easier for all the contributors to communicate, discuss guidelines, ask questions and such. This can be done by setting up a new forum based on something like [discourse](http://www.discourse.org/) for example, or asking the forum to be created as a subforum somewhere else, such as reddit or VO. 

However, it wouldn't be too much work to implement very lightweight discussions on VocaDB itself, working in the same style as the entry comments. A single level of subforums should be enough, under that posts and comments under posts. So, root -> subforums -> posts -> comments. Post editing should also be implemented, but this is even more simple.

**Comment by d-dd** [comment]
I like the idea of VocaDB's own simple forum. This way users don't have to make new accounts, and it could eventually include integration such as alert on username mentions, following a thread, etc. displaying a notification on the top banner and also things like tool-tips on link hover.

**Comment by riipah** [comment]
It'd never be as feature rich as a separate forum based on actual forum software, but definitely better integration with VocaDB. Username mentions are already there (in entry comments), entry tooltips are trivial as well.

**Comment by riipah** [comment]
This one is done
