### ISSUE TITLE
Followed artists RSS feature request

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#288]
Hello,

Is it correct that there is currently no way to get http://vocadb.net/ActivityEntry/FollowedArtistActivity as RSS?

I understand this is per user, so it could have username as an URL parameter, and possibly require the Access key in URL too.

Also if there is or will be a way to follow via RSS, there should be a way to turn off updates sent via Notifications in the site (if I subscribe via RSS, I won't need to also have this in Notifications anymore).

**Comment by riipah** [comment]
Do you need all activity, or just songs (by followed artists)? There's already RSS listing for songs, so that would be a lot easier.

>Also if there is or will be a way to follow via RSS, there should be a way to turn off updates sent via Notifications in the site (if I subscribe via RSS, I won't need to also have this in Notifications anymore).

You can already turn off on-site notifications on per-artist basis. See the subscription customization (dropdown arrow) on artist page.

**Comment by romanrm** [comment]
> Do you need all activity, or just songs (by followed artists)?

Yes, just newly added songs.

**Comment by riipah** [comment]
[Try this](http://vocadb.net/Song/Feed?sort=additiondate&onlywithpvs=true&FollowedByUserId=8821)

**Comment by romanrm** [comment]
Thanks!
