### ISSUE TITLE
Zipping for archived version data

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#294]
Archived version XML data could be zipped to save space

**Comment by ycanardeau** [comment]
How about storing archived version data in JSON rather than XML?

**Comment by riipah** [comment]
Zipping would still save more space. I'm thinking about long strings such as lyrics especially. I guess the format could be converted to JSON at the same time. But in any case I think this issue is low priority.

**Comment by ycanardeau** [comment]
For future reference:
- https://www.mediawiki.org/wiki/Manual:Text_table#Fields
> If the $wgCompressRevisions option is on, new rows (=current revisions) will be gzipped transparently at save time. Previous revisions can also be compressed by using the script compressOld.php
