### ISSUE TITLE
No hyperlink on some users' pages for Submissions and Total edits?

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#296]
Noticed that when viewing some user profiles the Submissions and Total edits do not appear as hyperlinks (anymore?)

E.g. http://vocadb.net/Profile/Urajimiiru

The actual information is still accessible via a direct URL: http://vocadb.net/User/EntryEdits/10581?onlySubmissions=False so it appears this has not been made private? But why the URL does not show up in some cases then.

**Comment by riipah** [comment]
The privacy setting hides the link but not the view. That is intentional, it's not intended to hide that view completely.

**Comment by romanrm** [comment]
IMO in a publicly edited website there should not be a user-side setting which makes it difficult or impossible to view that user's past edits.

> it's not intended to hide that view completely.

With the links hidden, not knowing the user ID, there is no way to load that data. And there doesn't appear to be a straightforward way to get user ID for any given user.
