### ISSUE TITLE
"Unhandled error occured" editing event series

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#300]
When trying to edit the series http://vocadb.net/Es/10/rin--lens-birthday
to set names to 鏡音誕生際 and "Kagamine Birthday", I get tons of "Unhandled error occured" screens when trying to save the edit. These work when saved as extra aliases, but saving with them as primary names fails.

Could be related to duplicate series http://vocadb.net/Es/100/deleted I initially created (and then deleted after finding the proper one).

**Comment by romanrm** [comment]
Trying to edit the date on this one http://vocadb.net/E/1189/rin--lens-birthday-2015 also fails with an unhandled error.

**Comment by riipah** [comment]
The error is due to an unique constraint in the database and requires changing the way event names are updated, similar to how it's done for tags already, which also have unique names.

**Comment by romanrm** [comment]
I thought so, that's why tried changing the duplicate series names to "deleted", but that still didn't help. Perhaps this is cached somewhere I guess.

Also what about the 2nd post error? (when editing just the date)

**Comment by riipah** [comment]
You also created http://vocadb.net/E/1494/kagamine-birthday-2015 which is causing the duplicate name

**Comment by romanrm** [comment]
Oh okay, I thought names aren't really stored in events themselves.

**Comment by riipah** [comment]
No, the names are inherited from series and saved to events for performance reasons, which also makes this very troublesome to fix. I estimate at least a days work, and I just don't have the motivation anymore.

**Comment by riipah** [comment]
done

**Comment by romanrm** [comment]
I am still hitting the same errors though. Did you not deploy the changes yet?

**Comment by riipah** [comment]
Patience. Not deployed yet. I will test and then deploy, when I get the chance
