### ISSUE TITLE
groupId argument ignored on /User

### ISSUE THREAD

**Issue by disqonnected** [VocaDB/vocadb#307]
The last two links in [/Help](http://vocadb.net/Help) link to http://vocadb.net/User?groupId=Moderator and  http://vocadb.net/User?groupId=Admin. Neither appears to filter.

**Comment by disqonnected** [comment]
On the subject of the Help pages, the second tab has a link to [Delicious Cake Project](http://deliciouscakeproject.wordpress.com/2010/09/20/hatsune-miku-and-the-magic-of-make-believe/) which appears to be gone.

**Comment by disqonnected** [comment]
http://vocadb.net/User?groups=Moderator Appears to not work either. Is way to do this?

**Comment by riipah** [comment]
groupId= works now (after deploy)

**Comment by riipah** [comment]
please make another issue for the "Vocaloid" page
