### ISSUE TITLE
Deter users from marking Artists as "Support" mistakenly

### ISSUE THREAD

**Issue by disqonnected** [VocaDB/vocadb#309]
The word "Support" is vague for someone who has not carefully gone through [Wiki/Artist Roles](http://wiki.vocadb.net/wiki/21/artist-roles). According to that, "Support" means "Vocal Tuning Assistant".

The term "Support" could stay, but if the use-cases are as specific as described above, I think a mouse-over popup over the "Support" checkboxes could help.

**Comment by riipah** [comment]
Support can also mean things like backing vocals. Generally anything that's significantly lesser role than the others, so it's not worth crediting, even if the person was involved. I can add the tooltip though.

**Comment by disqonnected** [comment]
Great. I would format it along the lines of

> #### What does "Support" mean?
> A supporting artist is someone who did significantly less work than the others. For example, if they did 
> - complementary synthesizing work
> - backing vocals
> - finalized tuning, etc.
> 
> It is __not__, however the main remixer.
