### ISSUE TITLE
Running requests in /swagger actually runs them in production

### ISSUE THREAD

**Issue by disqonnected** [VocaDB/vocadb#312]
This came as a surprise. While testing tag creation I created tags in vocadb.net.

This behaviour may be useful for seeing what happens when a request fails because of an existing entry.

**Comment by riipah** [comment]
How would you expect it to work instead?

**Comment by disqonnected** [comment]
I would expect it to run on a ephemeral instance or return mock replies.

**Comment by riipah** [comment]
That's not how Swagger works though. It's by design. You'd have to run it in a separate test environment (there is no such public environment for VocaDB)
