### ISSUE TITLE
"Unavailable" needs to be settable for "Other" type PVs as well

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#313]
For cases when the only available PV is designated as Other due to using footage from the Project DIVA games.

**Comment by riipah** [comment]
I considered it, but decided that for now it's better to only allow "unavailable" status for the main PVs. Other PVs should simply be deleted, if they're not important enough to justify their own entry. I'm sorry, but PjD PVs fall into this category.

**Comment by romanrm** [comment]
Well I mean cases when a song is ONLY released as audio track in a PV with PJD footage, and there was no other release of that song in any other form. Such VDB entry will have a single media added in it, which will be marked as "Other". IMO in this case that PV has the same importance and could be marked Unavailable and remain listed.

(So it's not about cases when a PJD PV is only something additional to an entry with primary media qualifying as Original.)
