### ISSUE TITLE
User title for "VocaDB veteran"

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#314]
Users who have been on the website for more than a specific amount of years with a number of edits can automatically be promoted to the role of veteran. Veteran title doesn't provide any edit permissions, but it signals that the user has been on the site for a long time. Could be related to user level/power?

**Comment by goldenchild-vocadb** [comment]
user level power is easy to have, look at vocafan again, http://vocadb.net/Profile/Vocafan . You just need to like tons of songs and follow thousands of artists.

i don't know how they do it on projectdiva.net, i think they use a sort a badges system, but how is it handle ???

**Comment by riipah** [comment]
It's common that forums have sophisticated features for social interaction. VocaDB doesn't need as much social features, and replicating them would be too much work anyway. Projectdiva.net is based on a commercial platform, so supporting such features requires zero effort from their part. Meanwhile, on VocaDB all features needed to be programmed. 

VocaDB veteran would be a sort of badge that you get from certain criteria such as user power. Do note that the formula for counting power can be adjusted, for example the relative influence of edits compared to likes can be increased.

**Comment by goldenchild-vocadb** [comment]
yes, they have too much badges imo (they are very SEGA/playstation influenced ;) )

and yes again to have the number of edits/submissions more influence compared to likes / artists followed.

Maybe the counting power can be adjusted as well, since (for me) i don't know how it works and climbing some levels is fast in the beginning ut after i can take months to "level up ! ". i really don't care about this now but i remember that at the beginning i was like " how many more edits must i need to "level up ! " ?

**Comment by riipah** [comment]
Coming up with a good formula is a bit difficult. The problem is that that users have vastly different amounts of activity. Some have only a few rated songs or edits, some have tens of thousands. 

Currently the level is based on a natural logarithm on power. 

`Level = logN(Power)`

As you probably know, logarithms grow quickly at first, but slow down quickly. The code is [here](https://github.com/VocaDB/vocadb/blob/master/VocaDbModel/Helpers/UserHelper.cs). It should be straightforward enough to understand to even non-programmer. Changing the formula for calculating the level is also possible, if you can come up with something better. 

I think that it would be best to base the badge on the number of edits + time on site. For example, more than 500 edits and 6 months on site.

**Comment by goldenchild-vocadb** [comment]
Yes, i've been to school enough to know logarithm but i really don't understand a thing at programming.
A better formula ? this could be an idea (not for now may be next months), now that i know this i can start thinking slowly, very slowly :) 

"500 edits and 6 months on site. " yes, with 500 edits, i mean the user is involved really into vocaloid

**Comment by riipah** [comment]
Let me translate the whole current formula:

`Power = number of edits (includes submits) / 4 + number of submits / 2 + tag votes * 2 + album collection * 2 + owned albums * 5 + album ratings given * 3 + song ratings given * 2 + comments given * 4 + number of song lists * 5 + 100 if email is verified`

Any of those variables can be changed.

**Comment by riipah** [comment]
I'm thinking, for now criteria for veteran is:
* 1 year on the site
* >1000 edits

I also adjusted the formula for power, giving higher preference to edits and comments
