### ISSUE TITLE
Rate-limit comment posting to prevent spam

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#32]
The server should limit the rate of comments (and maybe private messages) being posted by a single user, for example one per second. This is mostly to prevent spam. 

* Does not affect trusted users (or moderators).
* Can be implemented as artificial delay by the server.
* Concurrent requests are not allowed.
* At first we can implement this only for "limited" users.

**Comment by FinnRG** [comment]
Closed in favor of #1596.
