### ISSUE TITLE
New artist role for subject

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#326]
If we decide to keep the artbooks, it would be useful to be able to connect characters featured in the artbooks with the "subject" role.

* Should this role only apply to artbooks? It would be useful for animation PVs as well.
* Should this be the default role for Vocaloids in artbooks? Currently it's not possible to customize the roles for Vocaloids. Do we need other roles?
* Could the subject role be used for character designs as well, for example Hagane Miku? See #519.

**Comment by ycanardeau** [comment]
[mentioned](https://discord.com/channels/309072240639737866/666326527197315091/852273096676081694)
