### ISSUE TITLE
Implementing artist search by nico user_id and mylist number

### ISSUE THREAD

**Issue by zazuge** [VocaDB/vocadb#33]
It's frequent to find confusing Artist's/producer's names and collisions;
Also, it's not unusual to find that editors adding the wrong artist just because they have a similar name.
But crediting artists by their mylist number is consistent on NND, so we migh as well use it to make adding artists to songs and albums less error prone and faster.

**Comment by riipah** [comment]
So what kind of URLs should we support? http://www.nicovideo.jp/mylist/18545388 and/or /mylist/18545388?

**Comment by riipah** [comment]
Works with http://www.nicovideo.jp/mylist/18545388 and /mylist/18545388 now (/user/ too).
