### ISSUE TITLE
Problem with unusual Nico video url

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#334]
Most of the times, Nico url are like this : http://www.nicovideo.jp/watch/sm31142175
two letters before a number

but sometimes with this url : http://www.nicovideo.jp/watch/1426449115
Only numbers so, vocadb can't recognise a song, it's like adding a deleted nico song.

http://vocadb.net/S/172441

i can add it, it works but all the informations must be submitted each by each

thanks for your help

**Comment by riipah** [comment]
Unfortunately this is a limitation on Nico Nico's side. Their api does not provide a proper response for those PVs:
```
<nicovideo_thumb_response status="fail">
<error>
<code>COMMUNITY</code>
<description>community</description>
</error>
</nicovideo_thumb_response>
```

**Comment by goldenchild-vocadb** [comment]
Thanks, it's not a big deal since i think it's the second or third time i submitted a video like this one, and we can submit "manually" all the informations
