### ISSUE TITLE
Cannot login after changing username to 2 characters

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#341]
Hello,

I changed my username to "rm" (as  I always wanted instead of rm_):
http://vocadb.net/Profile/rm

the site logged me out, and I can't log-in because the login form doesn't accept 2-character names:

Unable to log in.
The field Username must be a string with a minimum length of 3 and a maximum length of 100.

**Comment by riipah** [comment]
I changed it back to rm_ now and will add/review the restriction on the user page

**Comment by romanrm** [comment]
Thanks. If you decide to allow 2-character usernames, let me know, that would be great.

Or if not, could you remove the records of "Old usernames rm (until 11.12.2017), rm_ (until 11.12.2017)" on my user page please.

**Comment by riipah** [comment]
I added the same limitation on the my settings page, and removed your old usernames.

**Comment by romanrm** [comment]
Thanks!
