### ISSUE TITLE
Artist cannot be added as support and non-support simultaneously (on different roles)

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#344]
Such as when main producer also does supporting vocals in the song.

Example: https://romanrm.hk/2017-12-19T103752Z-support.png  
or https://romanrm.hk/2017-12-19T104058Z-support2.png  
in http://vocadb.net/S/177995

clicking the "Support" checkbox on the 2nd instance makes the duplicate warning bar disappear (and the green bar appear above the data), but this still won't be saved as user expects. The support vocalist credit is not retained on save.

If this is not supposed to be allowed, then the yellow warning bar should stay and not change to green.

**Comment by riipah** [comment]
Specifying the same artist twice is not an error, but it's not supported either, so that's why duplicates are removed. I see no reason to add additional warnings for this

**Comment by romanrm** [comment]
My point is that after marking the "Support" checkbox on the 2nd credit, the hint box changes from yellow "duplicate detected" to green "all OK now", giving the impression that it now will be saved fine. But actually it won't, which is bizarre.

If duplicates aren't saved no matter "Support" or not, then the warning box should also stay at all time, and not disappear if a duplicate is marked "Support".

**Comment by riipah** [comment]
Okay yeah, you're right. I forgot there was already a warning for duplicate artists. Somehow I explicitly made the warning take into account the support status, even though adding the same artist twice still isn't possible, regardless of support status. For now at least I will fix it by showing the warning in either case.
