### ISSUE TITLE
The "Supported services" caption on the "Edit song" page does not include Creofuga

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#345]
Currently [this line](https://github.com/VocaDB/vocadb/blob/8c9d78fc3778e770af5803f7b268781892bbd2ef/VocaDbWeb/Resources/Views/Song/EditStrings.resx#L220) says ```Supported services: YouTube, NicoNicoDouga, Vimeo, SoundCloud, Piapro and Bilibili.``` I found out that Creofuga is supported because I tried it out on a whim.

**Comment by riipah** [comment]
I added mention of Creofuga.
