### ISSUE TITLE
Bilibili cover images do not load

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#347]
I created a list with a few examples: http://vocadb.net/L/7416
Opening image in a new tab shows that the error is 403 Forbidden.
But copying the URL to a new tab manually (no vocadb HTTP Referrer sent) makes it load fine.
Seems like they blocked loading pictures embedded in external websites?

**Comment by riipah** [comment]
It works in other browsers besides Chrome. In IE at least. I'm not sure if it's a problem with Chrome or Bilibili. I couldn't figure out the reason myself. I know Google isn't in the best of terms with the Chinese government.

**Comment by riipah** [comment]
See related comment here http://vocadb.net/discussion/topics/119

**Comment by AgFlore** [comment]
I guess this may be resolved with replacing the 'https' in the thumb image URL with 'http'.

Embedding with <img>https://i2.hdslb.com/bfs/archive/d6aa7b1bad28372a396d9944bc247ea04a37b976.j
pg</img> may be blocked, while  <img>http://i2.hdslb.com/bfs/archive/d6aa7b1bad28372a396d9944bc247ea04a37b976.j
pg</img> works well.
Tested on other sites, like [this](https://bbs.pku.edu.cn/v2/post-read.php?bid=7&threadid=17518670). Sound speculative, but I think it is worth a try.

**Comment by riipah** [comment]
I'd rather not do that because showing http images on a https site causes warnings for mixed content and may in theory allow cross site attacks. Additionally, that thumbnail URL is coming from Bilibili's own API. I would have to manually "downgrade" it to http, which is silly.

**Comment by romanrm** [comment]
> showing http images on a https site causes warnings for mixed content

And not possible at all soon: https://love2dev.com/blog/chrome-mixed-content/

**Comment by AgFlore** [comment]
Right, I understand. Will try to not place Bilibili PV on the top when editing.

**Comment by AgFlore** [comment]
> 
> 
> I'd rather not do that because showing http images on a https site causes warnings for [mixed content](https://developer.mozilla.org/fi/docs/Web/Security/Mixed_content) and may in theory allow cross site attacks. It will also make the browser classify the website as less secure. I know we still have some http images from nico nico, but hopefully one day we can get rid of them. [There was already someone who was worried about this earlier](https://vocadb.net/discussion/topics/178).
> 
> Additionally, that thumbnail URL is coming from Bilibili's own API. I would have to manually "downgrade" it to http, which is silly.

Ah, I looked into this problem again, and I think adding an attribute `referrerpolicy="no-referrer"` to the `<img>` will make the picture show.
