### ISSUE TITLE
Detect adding duplicate artists by URL regardless of HTTP or HTTPS

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#349]
Currently when trying to add an artist with a "https" Pixiv URL the site will not detect that the same artist is already in the database -- because the Pixiv URL on their profile is "http".
https://romanrm.hk/2018-01-05T113059Z-https.png

Only removing "s" from the URL makes the expected yellow box appear:
https://romanrm.hk/2018-01-05T113126Z-http.png

Seems like many artists on VDB have their Pixiv profiles added as "http", and Pixiv recently(?) has switched to redirecting everyone to HTTPS by default, so this issue will be hit quite often.

I have not checked if this is relevant elsewhere in similar situation, but the duplicate URL checks everywhere should always disregard http/https and compare only the actual address part.

**Comment by riipah** [comment]
I guess it would be possible to strip the scheme prefix and then search http and https.

**Comment by riipah** [comment]
Done
