### ISSUE TITLE
Incorrect discussion relative time stamps

### ISSUE THREAD

**Issue by d-dd** [VocaDB/vocadb#35]
The discussion relative time stamp shows incorrect time (see image). The discussion preview in the "Basic Info" tab time stamps seem correct, so I don't think it's my local computer clock that's wrong.

![GitHub Logo](http://i.imgur.com/YexXEkX.png)

Somewhat related, it would be nice if hovering over the relative time revealed the actual clock time (like Twitter)

**Comment by riipah** [comment]
Obviously there was no timezone info in the returned dates. I changed all of those dates to UTC in the API, now they are recognized properly by the client. Also added tooltip.

**Comment by riipah** [comment]
Also note that server-side timestamps (such as on the discussion "preview") are rendered in UTC because there is no timezone info server-side yet (there's a task for that). Client-side timestamps (on the discussion tab) are rendered in client's timezone (because the browser knows its timezone).
