### ISSUE TITLE
Highcharts label cropped on tag pages

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#352]
The tag relationship charts are cropped from the bottom when the number of children tags is too large.

For Example: [mmd tag](http://vocadb.net/T/275/mmd)

![Screenshot](https://user-images.githubusercontent.com/15908050/35182365-138e19a4-fddc-11e7-9454-7a4c21047cf4.png)

**Comment by riipah** [comment]
I'm not sure if much can be done about that. Expanding the image seems impossible.

**Comment by riipah** [comment]
Closing this because no suggestions
