### ISSUE TITLE
Advanced search filters should be configured per website

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#362]

**Comment by ycanardeau** [comment]
@riipah Can you elaborate?

**Comment by riipah** [comment]
Some advanced search filters do not make sense on TouhouDB/UtaiteDB. For example, on UtaiteDB you can filter songs by "artist type: Vocaloid". We might also want to add UtaiteDB/TouhouDB-specific filters. The available search filters should be configurable per website. I think this one is relatively important usability issue for those using the advanced filters.
