### ISSUE TITLE
Switching song from Youtube to Youtube doesn't work

### ISSUE THREAD

**Issue by Johandrex** [VocaDB/vocadb#367]
When opening "All Songs" the first song plays, but it's impossible to switch to another Youtube video (soundcloud, niconicodouga can be switched to just fine). When you try to go from Youtube video to another Youtube video all it changes is the title. This have only been an issue for the last 3-4 days. I've cleared my browser cookies, disabled uBlock origin and HTTPS everywhere.

**Comment by riipah** [comment]
Can you give me a link?

**Comment by riipah** [comment]
It might be related to that SSL change I did.YouTube might've stopped working http://vocadb.net. Today I added redirect from http to https, so SSL is the only option anyway. Let me know if the page works on https://vocadb.net

**Comment by Johandrex** [comment]
It's working fine now, thanks.
