### ISSUE TITLE
Suggestions: Wiki page links on edit view

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#368]
Having wiki links on song/artist/album edit views would help reducing some common mistakes, such as those related to romanization. This would also make the wiki pages more known and in turn, could make the wiki pages more detailed.

These links could be embedded (hidden) into existing ".editor-label"s on the edit pages, and on click, they would open the wiki page as a new tab. For labels that have help tips (dash underlines), the link text could be added to the hover popup box. I'm not sure how to handle the cursor value in this case (help or pointer type).

Romanized - [wiki/1/romanization-guidelines](https://wiki.vocadb.net/wiki/1/romanization-guidelines) (on all edit pages)
External links - [wiki/5/external-links](https://wiki.vocadb.net/wiki/5/external-links) (on all edit pages)

Release event - [wiki/36/events](https://wiki.vocadb.net/wiki/36/events) (albums/songs)
Artist tab -> roles [wiki/21/artist-roles](https://wiki.vocadb.net/wiki/21/artist-roles) (albums/songs)
Artist tab -> support [wiki/21/artist-roles#Support-status](https://wiki.vocadb.net/wiki/21/artist-roles#Support-status) (albums/songs)

Song type - [wiki/6/song-types](https://wiki.vocadb.net/wiki/6/song-types) (songs)
Media tab -> Type [wiki/32/pv-types](https://wiki.vocadb.net/wiki/32/pv-types) (songs)

Artist type - [wiki/23/artist-types](https://wiki.vocadb.net/wiki/23/artist-types) (artists)
Main picture - [wiki/41/choosing-the-main-picture-for-artist-entries](https://wiki.vocadb.net/wiki/41/choosing-the-main-picture-for-artist-entries) (artists)

Record type - [wiki/8/album-types-and-artist-participation](https://wiki.vocadb.net/wiki/8/album-types-and-artist-participation) (albums)

Additionally, wiki pages such as [merging-entries](https://wiki.vocadb.net/wiki/46/merging-entries) and 
[search-terms-cheat-sheet](https://wiki.vocadb.net/wiki/33/search-terms-cheat-sheet) could be added to their respective pages.

**Comment by riipah** [comment]
Included in #134

**Comment by riipah** [comment]
I'm not very excited about adding HTML to help text resources because it gets messy. Languages are also a small problem because the wiki is only available in English now. I think the other options should be considered before doing this.

**Comment by riipah** [comment]
Song types and artist types can now be described with tags, see #292. I will add more in-line description later. Tags will be the main method of in-line summary (documentation), while the wiki can provide more extensive documentation.
