### ISSUE TITLE
Replace Bilibili flash embeds with HTML-based embed code

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#372]
Example:
```<iframe src="//player.bilibili.com/player.html?aid=21140802&cid=34714040&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>```

The HTML embeds require a new "cid" parameter in addition to video "aid". This cid parameter is returned for API responses, so VocaDB should save it. I'm not sure what is the purpose of that parameter, but it varies by PV.

**Comment by riipah** [comment]
A problem with the new player is that the playback controls won't appear unless the player is big enough. The embedded player on VocaDB is below that size. I think it's rather silly, because you can't for example seek at all. I wonder if there's an option to force the controls to appear always?

**Comment by riipah** [comment]
The new player is added on VocaDB, but the missing controls issue is not resolved yet. Also, the new player will only be available for new PVs, because it requires the cid parameter.

**Comment by AgFlore** [comment]
> The HTML embeds require a new "cid" parameter in addition to video "aid". This cid parameter is returned for API responses, so VocaDB should save it. I'm not sure what is the purpose of that parameter, but it varies by PV.

On bilibili one aid (av12345678) entry can have many episodes, while each of the episode can be referred to with a unique cid. 
See https://api.bilibili.com/x/player/pagelist?aid=12802603 for an example. The video [av12802603](https://www.bilibili.com/video/av12802603) is the full record of the 2017 Luotianyi Concert, and the uploader put each song performed into an individual episode, with respective cids.

**Comment by AgFlore** [comment]
> A problem with the new player is that the playback controls won't appear unless the player is big enough. The embedded player on VocaDB is below that size. I think it's rather silly, because you can't for example seek at all. I wonder if there's an option to force the controls to appear always?

I've tried it out and finds that the threhold of showing controls is that the height of embed must be greater than 360px, sounds like not very far from the currently using 315px. 

Also, according to https://blog.asucreyau.xyz/2018/11/19/bilibili-embed-optimize/, the best height of the embed should be (width*9/16+118px), where the 118px is the total height of the top banner, the time-control and the bottom danmuku input. In the case here the banner and the danmuku input is useless, so perhaps we can mask it out in the final page with some html technique?
