### ISSUE TITLE
Truncate long album/song names in listings

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#375]
Long album/song names are problematic, convoluting listings. They should be truncated, probably using CSS or lodash truncate.

Which is better? Pixel or character limit?

**Comment by riipah** [comment]
Added character truncate using JavaScript, but I actually think pixel truncate would be better. It requires additional work though.

**Comment by Move-Forward39** [comment]
Pixel would probably be better comparing something like IIIIIIIIIIIIIIIIIIII vs. MMMMMMMMMMMMMMMMMMMM, but both cases aren't very likely, and if character limit is easier, we can just go with that.
