### ISSUE TITLE
Remove code related to http/https switching

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#377]
All those bool ssl flags can now be removed because all sites are SSL only.

**Comment by Move-Forward39** [comment]
Would that include like deleting this file and removing instances of the class HttpRequestExtensions?
https://github.com/VocaDB/vocadb/blob/859fd58ebd52089f019bc5abb57b6642ba394ea2/VocaDbModel/Helpers/HttpRequestExtensions.cs
