### ISSUE TITLE
i can't access the "Main albums"

### ISSUE THREAD

**Issue by goldenchild-vocadb** [VocaDB/vocadb#378]
![what](https://user-images.githubusercontent.com/28261382/38775742-e5f8b706-4089-11e8-87a6-810df6289b35.jpg)

all i've got is this: one grey picture of one album and nothing else ?

**Comment by riipah** [comment]
fixed. It happened because I added title truncation because of that one absurdly long album name, but didn't add the code on all pages.

**Comment by goldenchild-vocadb** [comment]
Many thanks, have a nice day riipah
