### ISSUE TITLE
Image caption gets cut past one line.

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#386]
https://i.imgur.com/rEZMyJM.png

This happens at least for the Japanese interface. (Entry where above picture is from: https://vocadb.net/Ar/54932)

Edit: Tested for English and it occurs there, too, so I assume it's a global issue.

**Comment by szc126** [comment]
It it because the enclosing `<li>` (CSS selector `ul.thumbs li`) has a fixed height (`height: 280px;`). Removing the height rule seems to fix it, but I'm not sure if there would be any unwanted side effects (why was the height defined in the first place?).

**Comment by ycanardeau** [comment]
> Removing the height rule seems to fix it, but I'm not sure if there would be any unwanted side effects (why was the height defined in the first place?).

There would be side effects when displaying images in multiple rows. You can confirm this by using Developer Tools on your browser.

**Comment by riipah** [comment]
The height needs to be fixed in order for multiple rows to work, but it could be a little more so that it fits 2 lines of text. Need to make sure all similar grids still work.
