### ISSUE TITLE
Revision mistakenly detects change in description

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#391]
I'm not sure what keeps causing this, but sometimes it'll state that the description was changed in addition to something else that was actually changed.
Here, for example, the description is said to have changed, but the old and new descriptions are exactly the same: https://vocadb.net/Artist/ViewVersion/164471
Since this doesn't really affect anything, though, it's a very minor issue.

**Comment by riipah** [comment]
I think this happens for revisions that were created before the translated description field was added. An empty translated description is added for new revisions, which is detected as a change. It's possible to prevent this, but not sure if worth it.

**Comment by riipah** [comment]
I can't actually reproduce this. Since it seems like a minor issue, maybe it's better to ignore instead of wasting more time.

**Comment by Move-Forward39** [comment]
Yeah, that's fine.
