### ISSUE TITLE
Default name is shown on front page

### ISSUE THREAD

**Issue by Move-Forward39** [VocaDB/vocadb#392]
The home page shows the default name of entries despite having English chosen as the preferred language to be displayed.
It is possibly an issue with caching.

**Comment by riipah** [comment]
Seems to be this: https://stackoverflow.com/a/18384253

So not a caching issue, but I will need to do some adjustments.

**Comment by riipah** [comment]
I added the config setting, should be fixed now.

**Comment by Move-Forward39** [comment]
Looks good!
