### ISSUE TITLE
Character limit of lyrics translation source

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#396]
Do you think the character limit for translation source urls should be extended? I found out that the source of the English translation for this song has a really long url that doesn't fit completely fit in the source URL field: https://vocadb.net/S/115595
The part that's missing is just 6 characters long ( "e_no))" ), though, so one option would just be to chop off the "http://" part.
What do you think?

**Comment by riipah** [comment]
I assume you mean lyrics translation?

**Comment by Move-Forward39** [comment]
Yeah, that's what I mean.
