### ISSUE TITLE
Persist culture option in session cookie

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#400]

**Comment by ycanardeau** [comment]
@riipah Can you please explain why we need this?

**Comment by riipah** [comment]
The idea was to be able to set language (culture) without logging in. Currently it can be set with query string parameter (culture=ja-JP), but I was thinking it would be useful to be able to browse the website in a different culture. I guess the concrete use case was testing translations, but I could imagine for example Japanese user wanting to browse the website in English (or vice versa), without making an account. Anyway, it's probably not very important.
