### ISSUE TITLE
Minor inconsistency with producer name display

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#404]
In https://vocadb.net/S/192072:
https://romanrm.hk/2018-07-13T063530Z-vdbname.png
Producer has all 3 names filled, and Original language set to English;
I have the site settings set to "Preferred display language: Original".

**Comment by riipah** [comment]
Currently this is by design. Original language for artist string means the same language as song/album title. Song original language is English, so artist string original language is English.

**Comment by romanrm** [comment]
Thanks, good to know.
