### ISSUE TITLE
Deleting a tag mapping makes the tag page unaccessible (for a while)

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#416]
Happened with:

- https://vocadb.net/T/2847/rebellion-against-aesthetics
- https://vocadb.net/T/144/experimental

> 2018-08-01 22:03:00.7557 [] ERROR No row with the given identifier exists[VocaDb.Model.Domain.Tags.TagMapping#39] 
> 2018-08-01 22:03:00.7557 [] WARN HTTP error code 404 for '**.***.***.*** (IP)' , URL GET '/T/144/experimental', UA '***', referrer 'https://vocadb.net/T/2847/rebellion-against-aesthetics' 

**The page becomes accessible again after a few minutes (~3).**

**Comment by riipah** [comment]
NHibernate cache issue
