### ISSUE TITLE
i can't submit anymore songs

### ISSUE THREAD

**Issue by goldenchild-vocadb** [VocaDB/vocadb#428]
http://www.nicovideo.jp/watch/sm33772450
when i try to submit this video,  when i click on save it open a random song .

https://vocadb.net/Ar/58147

same for others songs and i think others user have this problem too, i can edit old songs but submitting new ones is not possible.

**Comment by riipah** [comment]
Should be fixed. Try it now.

**Comment by riipah** [comment]
TODO: add test

**Comment by goldenchild-vocadb** [comment]
fine, thank you
