### ISSUE TITLE
Suggest "possibly delete" tag for songs when applicable

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#430]
Tag will be suggested when all rules below apply:
* Song has no active PVs.
* Song has no albums.
* Song has no ratings.
* Song has no derivatives. (?)

TODO: is this an exhaustive list?

**Comment by Move-Forward39** [comment]
I suggest also having the condition of no links (or at least, absence of certain kinds of links) in case it's a Bandcamp or Spotify exclusive release.
