### ISSUE TITLE
Featured song list repeats listed pools

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#432]
It seems as though the Featured Song List -> Pools section will sometimes list pools multiple times.
![image](https://user-images.githubusercontent.com/32796979/47032548-9ef88780-d140-11e8-89c1-6a7c297a55e9.png)
![image](https://user-images.githubusercontent.com/32796979/47032566-a6b82c00-d140-11e8-94ed-bb684bfa2fe1.png)
It seems like when I type slow, it works fine:
![image](https://user-images.githubusercontent.com/32796979/47032686-f7c82000-d140-11e8-8b79-0633c5e79387.png)
But when I type fast, it will cause a repeat:
![image](https://user-images.githubusercontent.com/32796979/47032712-044c7880-d141-11e8-8004-4a9bed67c25c.png)
I'm guessing it's something to do with how the search is set up, as it seems to update per character I type, so perhaps when I type faster than it updates, it causes repeats.

**Comment by ycanardeau** [comment]
Looks like fixed by #578.
