### ISSUE TITLE
Piapro playback issue

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#446]
https://vocadb.net/S/201660 does not play in VDB embed.
Viewing the network log, it shows the browser tries to request http://c1.piapro.jp/audio_audition/12/12mejejtau4b3azf_20180616005030_audition.mp3 which returns Error 404.
The song plays fine at Piapro itself: http://piapro.jp/content/12mejejtau4b3azf

**Comment by romanrm** [comment]
The audio URL retrieved by the Piapro player is 
https://cdn.piapro.jp/mp3_a/12/12mejejtau4b3azf_20180616005030_audition.mp3

**Comment by riipah** [comment]
They must've changed the CDN server. Can you check are all songs available on the new server cdn.piapro.jp ?

**Comment by riipah** [comment]
Seems that all songs, including old songs, have been moved to the new server. I changed the server.
