### ISSUE TITLE
Events don't inherit series Original language until edited/saved

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#447]
At https://vocadb.net/Es/10/kagamine-birthday the Original language is set to Non-English; but most events in it still use English titles: https://romanrm.hk/2018-11-16T075603Z-vdbes.png
Only events which have been modified after changing the series language inherit it (even if just opening an event and clicking Edit/Save with no other changes).

**Comment by riipah** [comment]
Language selection is inherited from series to events (unless using custom name). Language selection is updated when editing events, but currently not updated when editing events. It can be changed.

**Comment by riipah** [comment]
Done.
