### ISSUE TITLE
Find originals should prefer original/remaster over cover/remix

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#449]
Probably easiest to implement by making two searches: all + original, then show originals first.

**Comment by Shiroizu** [comment]
Does not seem to work on edit pages (this might be a separate issue).

On the song submit page, searching with "みくみくにしてあげる♪" correctly returns S/1355 as the first result, but on the edit page (Original version -search box) the entry is not shown first.

<img width="230" alt="Untitled" src="https://user-images.githubusercontent.com/15908050/130622671-fc327667-1100-41d1-9a09-70479647f5e7.png">

**Comment by riipah** [comment]
Oh please don't reopen issues that have been implemented/fixed years ago, and probably used to work at least in a way. Better to make a new issue.

**Comment by Shiroizu** [comment]
#949

**Comment by riipah** [comment]
And actually now that I had time to look at it, this issue was only about the "Find originals" button, while you are talking about the search list. Related, but different. But yeah, good that you made another issue so it can be documented properly.
