### ISSUE TITLE
PM `code` escaping

### ISSUE THREAD

**Issue by d-dd** [VocaDB/vocadb#45]
Coded messages like `&&&` become escaped and turn into `&amp;&amp;&amp;` when sent through PM's.

The preview shows `&&&` so it's a little bit confusing when it turns out different.

I'm not sure if escaping is intended, but if it is maybe the preview should also show it escaped. It's such a minor thing but though I'd point it out. :dango: Might be related or duplicate of # #38 or #39.

**Comment by riipah** [comment]
Previews are always rendered with marked JavaScript library. Messages are rendered server-side using MarkdownSharp. Marked includes built-in HTML sanitizer, while MarkdownSharp doesn't. Instead, the HTML is sanitized using .NET's built-in library which probably encodes those ampersands. So yeah, it's related to both tasks, mainly #39, and should be fixed when that task is done.
