### ISSUE TITLE
Add artist type for Synthesizer V

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#458]
Currently following the situation, seeing if there's going to be more voicebanks and songs.

**Comment by andreoda** [comment]
(At least 5 root voicebanks):
Voidol - 18 root voicebanks
NIAONiao - 17 root voicebanks
Voiceroid - 13 root voicebanks
chipspeech - 12 root voicebanks
Synthesizer V - 9 root voicebanks
Muta - 8 root voicebanks
Alter/Ego - 6 root voicebanks
Sharpkey - 6 root voicebanks
Microsoft Speech API - 5 root voicebanks
Sinsy - 5 root voicebanks

There should be at least enough root voicebanks for an artist type field to make sense.
If we consider Synth V then we should consider the ones above as well.

**Comment by riipah** [comment]
I would also consider the number of songs/albums, not just number of voicebanks. And some of those are discontinued as far as I know. I think chipspeech and Alter/Ego said they are not making any more voices.

**Comment by andreoda** [comment]
How about making this available for editors to add. For example just like adding a new base/main/parent tag like the ones we have (Genres, Themes, etc.). 
We could simply add new artist "parent" types manually and the system automatically changes the colors of the aquare field. 
For example Cevio has a green color. The system would randomly pick a color that doesn't exists as an artist type already. If we decide to delete an artist type, then the color will be available again...or something like that. I don't know how complex that would be though.

**Comment by ycanardeau** [comment]
@andreoda 

>There should be at least enough root voicebanks for an artist type field to make sense.

Can we just add these 10 voicebanks as an artist type field for now?

> How about making this available for editors (or only trusted or mods) to add. For example just like adding a new base/main/parent tag like the ones we have (Genres, Themes, etc.).
> We could simply add new artist "parent" types manually and the system automatically changes the colors of the "square" field.

Could you please create a new issue (or a discussion) for that?

**Comment by ycanardeau** [comment]
@andreoda 

>There should be at least enough root voicebanks for an artist type field to make sense.

Can we just add these 8 voicebanks (except for chipspeech and Alter/Ego?) as an artist type for now? Does it make sense to have these new artist types considering relatively small number of entries compared to the existing ones? I guess, instead of having an `enum`, we should create a new table, if there are too many artist types.

> How about making this available for editors (or only trusted or mods) to add. For example just like adding a new base/main/parent tag like the ones we have (Genres, Themes, etc.).
> We could simply add new artist "parent" types manually and the system automatically changes the colors of the "square" field.

Could you please create a new issue (or a discussion) for that?

**Comment by andreoda** [comment]
Of course! Only add the ones that make sense for you. Synth V is the most important one requested.
Alright, I'll make another issue for that. Thank you for the feedback!

**Comment by ycanardeau** [comment]
I've only added Synthesizer V.

**Comment by andreoda** [comment]
Can this issue be closed?

**Comment by ycanardeau** [comment]
I think it's okay to keep it open for now.

**Comment by ycanardeau** [comment]
Closed in #705.
