### ISSUE TITLE
Strip SoundCloud querystring

### ISSUE THREAD

**Issue by disqonnected** [VocaDB/vocadb#459]
Having a querystring in SoundCloud PVs can cause them to fail to link to an existing song.

For example, given https://vocadb.net/S/156055 ,
The current SC PV has a URL of https://soundcloud.com/voicetextactor/original-demo-song-ver2017-07-6?in=voicetextactor/sets/all-1 .
While this creates the embed correctly, opening the URL results in a "We can’t find that playlist." error.
If the URL had been https://soundcloud.com/voicetextactor/original-demo-song-ver2017-07-6 there would had been no issue despite the playlist's deletion.

We cannot be entirely sure that there will be no future query string that will be necessary to open a song, but those that I have found so far have only served to cause this problem.

Edit: Note that this query string has also found its way to the `pvId` served by vocadb's API.

**Comment by riipah** [comment]
I'm confused now what's the original source URL. But yes, the PV ID is constructed by concatenating the internal SoundCloud ID with the URL, because both are needed for the embed. Query parameters should be removed though.

**Comment by disqonnected** [comment]
The PV URL that was listed in vocadb (before I started trying to figure out if the site will auto-strip it for me) was this:
https://soundcloud.com/voicetextactor/original-demo-song-ver2017-07-6?in=voicetextactor/sets/all-1

**Comment by riipah** [comment]
So you're saying that the URL https://soundcloud.com/voicetextactor/original-demo-song-ver2017-07-6?in=voicetextactor/sets/all-1 probably used to work at some point, but the playlist was probably removed?

SoundCloud has really complicated URL handling because there's no way to link to the song based on just the internal ID. That's why we need to save the public URL, but as said, that public URL can change. You'd have to make an API call to get the up to date URL.

Anyway, I can fix this by removing the query string.

**Comment by disqonnected** [comment]
> So you're saying that the URL https://soundcloud.com/voicetextactor/original-demo-song-ver2017-07-6?in=voicetextactor/sets/all-1 probably used to work at some point, but the playlist was probably removed?

Yes.

> SoundCloud has really complicated URL handling because there's no way to link to the song based on just the internal ID. That's why we need to save the public URL, but as said, that public URL can change. You'd have to make an API call to get the up to date URL.

This is the conclusion I have also reached, but at least the embed keeps working even when the URL doesn't, prompting someone (or something) to go looking for the new URL.

**Comment by disqonnected** [comment]
Thanks for the fix!
