### ISSUE TITLE
SongForApiContract does not include 'deleted' status

### ISSUE THREAD

**Issue by disqonnected** [VocaDB/vocadb#460]
Hello again,
It would be useful if one could resolve, via the API, whether a song has been deleted.

**Comment by riipah** [comment]
What's the use case for this? And are you talking about a single song by ID, or listing deleted songs?

**Comment by disqonnected** [comment]
I meant "song by ID". My use case is to avoid storing songs which have been deleted.

Thank you very much for yet another fix! :)
