### ISSUE TITLE
More choices for the show items fields

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#461]
can we have more choices than ?
10 items per page
20 items per page
40 items per page

maybe 10 items can be deleted (i understand that at the beginning of the website there where fews entries but now)
and have well 25 items, 50 items, 100 items and 200 items

**Comment by goldenchild-vocadb** [comment]
sorry for the late answer, you're right for the 10 items per page, maybe, can we have more than 3 choices ?
10 items per page
25 items per page
50 items per page
100 items per page
200 items per page (this one is not really usefull now)

**Comment by riipah** [comment]
Is it enough if I add 100 items for now? I would rather not modify the existing ones unless absolutely necessary. Keep in mind the translations need to be updated too, so it's more work than it sounds.

**Comment by goldenchild-vocadb** [comment]
many thanks @riipah
