### ISSUE TITLE
Search both http and https for mylist URLs when adding artists to songs

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#465]
i know i'm asking a lot, but we we are adding links, can the software search both https://link and http://link
through the database ?

because when i add some mylist in the artists fields
if the mylist was already added on the website with http://link and you're adding the same mylist but with the " s " : https://link the sofware don't recognize it and everytime you have to try once, then delete the " s " and try again the link.
this happen when you're editing songs, but when you're adding artist, well... with or without " s " , the software recognize if the artist is already on the database.

**Comment by riipah** [comment]
You're mainly talking about the mylist links? I think VocaDB only checks certain URLs. For performance reasons it's better not check both URLs unless necessary, but I can add it here.

**Comment by goldenchild-vocadb** [comment]
nico mylist links, main piapro links, nico user ( https://www.nicovideo.jp/user/ ), piapro user link (for exemple : https://piapro.jp/tobefoopers ), maybe twitter ?

**Comment by goldenchild-vocadb** [comment]
I still need this, please, everytime i'm adding a link, i need to check with or without the " s " , and with nico links, i must try to add a new artist to be sure about the link (if the artists links are already added in https .

**Comment by riipah** [comment]
I have been quite busy lately. Going to be back next month, then I can maybe take a look.

**Comment by riipah** [comment]
This should be done now
