### ISSUE TITLE
Overly aggressive caching of "Unavailable" thumbnails

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#472]
Sometimes I upload reprints of songs which went unavailable on their original source: https://vocadb.net/L/6823
Currently 9 out of 58 songs continue to show the generic "Video unavailable" thumbnail in songlists and the like, despite the YouTube media marked as unavailable in the song, and an alternative existing (and many months passed).
Media with the "Unavailable" checkbox should not be considered as thumbnail source and thumbnails should be (re)fetched from the still available media, if any.
Thanks!

**Comment by riipah** [comment]
Currently unavailable PVs are also included in search for thumbnails. That can be changed.

**Comment by riipah** [comment]
These songs had also another problem. They only have "Other" PVs that are still active, and "Other" PVs were not considered, unless they're the only PVs available. Well, I changed that too.

**Comment by riipah** [comment]
I just realized there is still a problem with this change. Private PVs are marked as unavailable here, but the thumbnail is usually still available. For Nico Nico, thumbnail might be available even after deletion. So we do need to consider disabled PVs too. Perhaps it's ok to check active PVs first, then disabled.

**Comment by romanrm** [comment]
Has this been deployed to the site? Or maybe it doesn't solve the issue entirely?
At  https://vocadb.net/L/6823 on page 3 a few still show broken icons.
Or even some popular stuff such as https://vocadb.net/L/8140

**Comment by riipah** [comment]
The thumbnails need to be updated per song. That means removing a PV and then re-adding it. There's also a mod maintenance action for that.
