### ISSUE TITLE
Parameterize all counting resource strings

### ISSUE THREAD

**Issue by d-dd** [VocaDB/vocadb#48]
It would be easier to translate if we are free to move the number/count within the string, for example "AlbumCount" (Views/Shared/MiscStrings) has "album(s)" in neutral/English, but it would be better if it was "{0} album(s)"

Most counting strings already have {0} parameters. 

The one I noticed was:
Views/Shared/MiscStrings (AlbumCount, SongCount, ArtistCount) and 
Views/Shared/EntryDetailStrings (Hits).

**Comment by riipah** [comment]
I think AlbumCount, SongCount, ArtistCount in MiscStrings aren't used, they can be removed

**Comment by riipah** [comment]
Removed the unused strings and parameterized "hits", anything else?

**Comment by d-dd** [comment]
Not that I noticed. Thanks!
