### ISSUE TITLE
Allow drag and drop a song on mobile

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/vocadb#489]
It's impossible to change order of songs on mobile. It can be done on desktop by drag and drop. 

The workaround is to remove songs from a list before newly added song and add them again, which can be troublesome for songs with descriptions on song lists.
 
Song order change is used in album tracklist and song lists/pools pages.

Probably related to #6.

**Comment by riipah** [comment]
The editing features are especially not designed to be mobile friendly. The idea is that you would do most of the editing on a desktop. I understand that more and more people would want to do the editing on mobile too, but the editing features are still second priority for mobile support.

That said, I wonder if this could be solved just by adding a number field so you can move the song straight to a specific position, similar to Steam wish lists? That would be easy to implement, and would also be useful on desktop.

![image](https://user-images.githubusercontent.com/550886/55688767-366ac480-5985-11e9-8586-1f2d28e6b48f.png)

**Comment by Nefere256** [comment]
Do you think about changing current song number text into modifiable field? I'm not sure if it would fit nicely into a song row, but we can give a try.

If drag and drop isn't an option, I thought about adding down/up arrows on every song row to change song order by one position. But your solution looks better since tracks usually has a fixed number on the tracklist and only few clicks (taps?) will be needed to set songs in correct order.

We can't forget about albums with multiple discs - I guess a number order change would work only within one disc. It would be easier to change disk number too, or we would have to uncheck "next disc" option to move the song into a desired place and recheck "next discs".

**Comment by ycanardeau** [comment]
Probably we can use [SortableJS](https://sortablejs.github.io/Sortable/). It works on mobile as well.
