### ISSUE TITLE
Hope to obtain the duration of bilibili video automatically

### ISSUE THREAD

**Issue by AgFlore** [VocaDB/vocadb#493]
With https://api.bilibili.com/x/player/pagelist?aid=[aid] , I suppose one can obtain the duration of a video. It is helpful to see the the duration filled in automatically when adding songs from a bilibili PV.
For example with https://api.bilibili.com/x/player/pagelist?aid=6009789, it returns that the duration of the current PV of [世末歌者](https://vocadb.net/S/132917) is 363 (06'03"). (different from the album version due to some bonus in the PV)

**Comment by riipah** [comment]
Ok, I'll check the API at home. I wonder why they didn't add it to the actual video info call? This call doesn't require parsing any HTML, right?

**Comment by AgFlore** [comment]
Request in browser https://api.bilibili.com/x/player/pagelist?aid=6009789, and I get
{"code":0,"message":"0","ttl":1,"data":[{"cid":35302832,"page":1,"from":"vupload","part":"","duration":363,"vid":"","weblink":"","dimension":{"width":1280,"height":568,"rotate":0}}]}

**Comment by riipah** [comment]
Don't you need to sign the request first? Or you don't if you're logged in to Bilibili? I don't have working credentials to Bilibili.

**Comment by riipah** [comment]
So this API returns JSON? The other one I'm using (https://api.bilibili.com/view) returns XML.

**Comment by AgFlore** [comment]
> Don't you need to sign the request first? Or you don't if you're logged in to Bilibili? I don't have working credentials to Bilibili, I'm just using the API key.

It would return an error page if I click the link https://api.bilibili.com/x/player/pagelist?aid=6009789; but if I copy the link address and start the page, it works ok and returns the json. It also works if I click the link and ask my Chrome to start it in the incognito window. Don't know why this happens.

**Comment by riipah** [comment]
Ah I see. Must be some referral protection. It seems to be working.

**Comment by riipah** [comment]
We have Bililbili API documentation at https://github.com/VocaDB/vocadb/wiki/Bilibili-API-documentation . I updated that documentation and also mentioned this new endpoint.
