### ISSUE TITLE
Bilibili flash embeds don't work

### ISSUE THREAD

**Issue by AgFlore** [VocaDB/vocadb#495]
Bilibili flash embeds don't load on multiple browsers of mine. For example https://vocadb.net/S/162351.
Guess there to be some problem with the old flash embed.

Is is possible to update all the old flash embeds that some entries still use into the new HTML5 embed?

P.S. I would suggest adjust the height of the Bilibili HTML5 embed to show the controls. I've tried it out and finds that the threhold of showing controls is that the height of embed must be greater than 360px, sounds like not very far from the currently using 315px.

Also, according to https://blog.asucreyau.xyz/2018/11/19/bilibili-embed-optimize/, the best height of the embed should be (width*9/16+118px), where the 118px is the total height of the top banner, the time-control and the bottom danmuku input. In the case here the banner and the danmuku input is useless, so perhaps we can mask it out in the final page with some html technique?

**Comment by riipah** [comment]
I'm not doing a script for this, but there is a facility available for moderators to refresh the embed for one song at a time. Users may also do that by hand of course.
