### ISSUE TITLE
Song addition page lists already existing entry twice

### ISSUE THREAD

**Issue by romanrm** [VocaDB/vocadb#496]
E.g. adding a song by URL https://www.youtube.com/watch?v=qMWzSYHYWGo
results in the found existing entry listed twice on the bottom-right of the page:
https://romanrm.hk/2019-05-24T053332Z-vdbdup.png
both of these link to the same https://vocadb.net/S/220697

Happens not just with this particular song, one more example:
https://romanrm.hk/2019-05-24T053951Z-vdbdup2.png

**Comment by andreoda** [comment]
I also have the same issue for a long time but I can not remember if it always occurs (with every link I add).

**Comment by Nefere256** [comment]
Few more examples from TouhouDB:
* adding [a Touhou-style original](https://www.nicovideo.jp/watch/sm35868450) shows [S/15756](https://touhoudb.com/S/15756) twice,
* adding [an arrangement of The Gensokyo The Gods Loved](https://www.youtube.com/watch?v=nxm7TrbYTWs) shows [S/15867](https://touhoudb.com/S/15867) twice.

I've found yout that if you edit a suggested title, the duplicate matching entry will disappear.
