### ISSUE TITLE
more favicons and URL templates for commercial links

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#497]
**AKIBA HOBBY**
examples:
http://ec.akbh.jp/products/detail.php?product_id=2100000081448
https://ec.akbh.jp/products/detail.php?product_id=2100000104482
https://ec.akbh.jp/products/detail.php?product_id=2100000103560
https://ec.akbh.jp/products/detail.php?product_id=2100000097548
https://ec.akbh.jp/products/detail.php?product_id=2100000100019
favicon:
![AKIBA HOBBY favicon](https://user-images.githubusercontent.com/52045122/59883581-d7c6bb80-93b5-11e9-9f34-0c3acaba6e58.png)

**akibaoo**
examples:
http://www.akibaoo.com/c/item/2500020429068/
http://www.akibaoo.com/c/item/2500020472361/
http://www.akibaoo.com/c/item/2500020473337/
http://www.akibaoo.com/c/item/2500020465301/
http://www.akibaoo.com/c/item/2500020449615/
favicon:
![akibaoo favicon](https://user-images.githubusercontent.com/52045122/59883583-d7c6bb80-93b5-11e9-81ac-4900f891e482.png)

**DIVERSE DIRECT**
examples:
https://diverse.direct/polyphonix/adsr-0009/
https://diverse.direct/kikuo-sound-works/ksw-0006/
https://diverse.direct/tatsuta-recordings/tzta-0002/
https://diverse.direct/adsrecordings/adsr-0007/
https://diverse.direct/kikuo-sound-works/ksw-0004a/
favicon:
?

**iTunes (JP)**
iTunes seems to have different URLs (https://itunes.apple.com and https://www.apple.com and https://music.apple.com)
examples:
https://music.apple.com/jp/album/drop-single/1467709723
https://music.apple.com/jp/album/mikus-bounce-xx-single/1467092880
https://music.apple.com/jp/album/a-shower-single/1464614436
https://music.apple.com/jp/album/stars-align-single/1464619373
https://music.apple.com/jp/album/poker-face-and-sexual-frigidity-single/1464619213
favicon:
![iTunes favicon](https://user-images.githubusercontent.com/52045122/59883584-d7c6bb80-93b5-11e9-97d0-84754a43f3f3.png)

**KKBOX**
examples:
https://kkbox.fm/ql3i6k
https://kkbox.fm/nl3qwN
https://kkbox.fm/kl3Yl0
https://kkbox.fm/kl3wlC
https://kkbox.fm/kl3ElJ
favicon:
![KKBOX favicon](https://user-images.githubusercontent.com/52045122/59883585-d7c6bb80-93b5-11e9-81fa-58672648f362.png)

**music-book**
examples:
http://music-book.jp/music/Artist/401845/Album/aaa3gkth
http://music-book.jp/music/Artist/401845/Album/aaa3e7j4
http://music-book.jp/music/Artist/619426/Album/aaa7ljox
http://music-book.jp/music/Artist/409539/Album/aaa2d0dn
http://music-book.jp/music/Artist/409298/Album/aaa4lz36
favicon:
![music-book](https://user-images.githubusercontent.com/52045122/59886371-f2e9f900-93be-11e9-9512-c01ab06bf74f.png)

**MySound**
examples:
https://mysound.jp/album/266525/
https://mysound.jp/album/280926/
https://mysound.jp/album/77780/
https://mysound.jp/album/202543/
https://mysound.jp/album/186428/
favicon:
![MySound favicon](https://user-images.githubusercontent.com/52045122/59883586-d85f5200-93b5-11e9-91a2-c7e35094e791.png)

**Oricon**
examples:
http://music.oricon.co.jp/php/cd/CdTop.php?cd=SPC00520939
https://music.oricon.co.jp/php/cd/CdTop.php?cd=SPB00050272
https://music.oricon.co.jp/php/cd/CdTop.php?cd=SPB00058489
https://music.oricon.co.jp/php/cd/CdTop.php?cd=SPB00050308
https://music.oricon.co.jp/php/cd/CdTop.php?cd=SPB00023267
favicon:
![Oricon favicon](https://user-images.githubusercontent.com/52045122/59883587-d85f5200-93b5-11e9-8b46-e2a5f100683d.png)

**OTOTOY**
examples:
https://ototoy.jp/_/default/p/381564
https://ototoy.jp/_/default/p/381563
https://ototoy.jp/_/default/p/381386
https://ototoy.jp/_/default/p/397149
http://ototoy.jp/_/default/p/45127
favicon:
![OTOTOY favicon](https://user-images.githubusercontent.com/52045122/59883588-d85f5200-93b5-11e9-897d-f426eae15a47.png)

**potune**
examples:
https://potune.jp/item/?id=5523
https://potune.jp/item/?id=5545
https://potune.jp/item/?id=4838
https://potune.jp/item/?id=4691
https://potune.jp/item/?id=4686
favicon:
![potune favicon](https://user-images.githubusercontent.com/52045122/59886003-a225d080-93bd-11e9-9db3-820d45dd899d.png)

**Singtel musicStore**
examples:
http://musicstore.sg/musicstore/index.php?r=album&albumID=1033455
http://musicstore.sg/musicstore/index.php?r=album&albumID=2725216
http://musicstore.sg/musicstore/index.php?r=album&albumID=1023707
http://musicstore.sg/musicstore/index.php?r=album&albumID=2727344
http://musicstore.sg/musicstore/index.php?r=album&albumID=2025644
favicon:
?

**TANO*C STORE**
examples:
https://www.tanocstore.net/shop/shopdetail.html?brandcode=000000001212
https://www.tanocstore.net/shop/shopdetail.html?brandcode=000000001973
https://www.tanocstore.net/shop/shopdetail.html?brandcode=000000002028
https://www.tanocstore.net/shop/shopdetail.html?brandcode=000000001856
https://www.tanocstore.net/shop/shopdetail.html?brandcode=000000001275
favicon:
![TANO C STORE favicon](https://user-images.githubusercontent.com/52045122/59883589-d85f5200-93b5-11e9-9592-1d774b645d83.png)

**Toranoana**
examples:
https://ec.toranoana.shop/tora/ec/item/040030651902/
https://ec.toranoana.shop/tora/ec/item/040030694914/
https://ec.toranoana.shop/tora/ec/item/040030562061/
https://ec.toranoana.shop/tora/ec/item/040030695879/
https://ec.toranoana.shop/tora/ec/item/040030726875/
favicon:
![Toranoana favicon](https://user-images.githubusercontent.com/52045122/59883590-d85f5200-93b5-11e9-80ff-4189cca25a13.png)

**VILLAGE VANGUARD**
examples:
https://vvstore.jp/i/vv_000000000173172/
https://vvstore.jp/i/vv_000000000099148/
https://vvstore.jp/i/vv_000000000171138/
https://vvstore.jp/i/vv_000000000169640/
https://vvstore.jp/i/vv_000000000135902/
favicon:
![VILLAGE VANGUARD favicon](https://user-images.githubusercontent.com/52045122/59883591-d8f7e880-93b5-11e9-85d8-0d0677cd2a4c.png)

**TOWER RECORDS**
examples:
https://tower.jp/item/4830289/
https://tower.jp/item/4857557/
https://tower.jp/item/4206708/
https://tower.jp/item/3207444/
https://tower.jp/item/3445337/
favicon:
![TOWER RECORDS favicon](https://user-images.githubusercontent.com/52045122/59883593-d8f7e880-93b5-11e9-8bc4-6ea6f4bd3635.png)

**LINE MUSIC**
examples:
https://music.line.me/launch?target=album&item=mb00000000018c7d7b&cc=JP&from=tw
https://music.line.me/launch?target=album&item=mb00000000018c7d79&cc=JP&from=tw
https://music.line.me/launch?target=album&item=mb00000000018edb5c&cc=JP&from=tw
https://music.line.me/album/mb0000000001865454
https://music.line.me/album/mb00000000017d8a2f
https://music.line.me/album/mb0000000000011fa8
favicon:
![LINE MUSIC favicon](https://user-images.githubusercontent.com/52045122/59883594-d8f7e880-93b5-11e9-9d86-1f4bb76ada0c.png)

_____

I hope this list will help adding favicons and finding out the URL templates.
- all favicons are in "png" format
- some links are "HTTP" and others are "HTTPS"

**Comment by goldenchild-vocadb** [comment]
Very good idea, the more important is the toranoana one, with their new url, the website can't recognize it's toranoana :( .

**Comment by goldenchild-vocadb** [comment]
and http://www.grep-shop.com/tsuhan/ as well please :) there are some vocaloids CDs here

**Comment by ycanardeau** [comment]
You can do the following steps yourself. It seems that some icons are already added though.
1. Add png files (16 x 16 pixels) to [VocaDbWeb/Content/ExtIcons](https://github.com/VocaDB/vocadb/tree/master/VocaDbWeb/Content/ExtIcons).
1. Edit [VocaDbWeb/Content/Styles/ExtLinks.less](https://github.com/VocaDB/vocadb/blob/master/VocaDbWeb/Content/Styles/ExtLinks.less) (not ExtLinks.css)
3. Edit [VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts](https://github.com/VocaDB/vocadb/blob/master/VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts).

**Comment by andreoda** [comment]
@ycanardeau 
I can't upload any files there.

**Comment by ycanardeau** [comment]
You cannot (should not) directly upload files there. You need to fork a repo, and then create a pull request.

References:
- [Fork a repo](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo)
- [Creating a pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)
- [About branches](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-branches)

If you have any questions, please ask me anything.
