### ISSUE TITLE
Provision for 'historical versions' of piapro media

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#503]
Example: https://piapro.jp/ex_content/history_list/0on9/1 (https://vocadb.net/S/7319):
* https://piapro.jp/t/0on9/20091108085115 `1925`
* https://piapro.jp/t/0on9/20091108085816 `1925 Karaoke`
* https://piapro.jp/t/0on9 `1925 Karaoke w/o Chorus`

**Comment by riipah** [comment]
Just FYI, there is a [separate repository](https://github.com/riipah/piapro-dotnet) for the Piapro library. It would be better to report Piapro requests/issues there.

**Comment by riipah** [comment]
Moved to piapro repo.
