### ISSUE TITLE
Adding more informations from Niconico douga

### ISSUE THREAD

**Issue by goldenchild-vocadb** [VocaDB/vocadb#514]
For example : 
https://vocadb.net/S/256336

Published | 07/10/2019
Addition date | 07/10/2019 03:02:00

can't you add the published hour ? in this case, it was  12:00 , japan local time

**Comment by riipah** [comment]
If you add time then you need to worry about timezones and such, so it's just easier this way. Why do you need the time?

**Comment by goldenchild-vocadb** [comment]
Well, sometimes producer are uploading songs on the same day, and then the songs are listed in alphabetic order instead of by release date/time.

**Comment by riipah** [comment]
And... can you give a case where this really matters? Why do you need to know if a particular song was released 2 hours earlier?

**Comment by goldenchild-vocadb** [comment]
It"s just to have the same song order as a nico mylist.

**Comment by riipah** [comment]
And why does it need to be the same order as nico mylist?

**Comment by goldenchild-vocadb** [comment]
it's to have the same quality of information available on vocadb or on nicovideo.

**Comment by riipah** [comment]
I think it makes sense that Nico has slightly more detailed information, where appropriate. VocaDB isn't tied to just Nico anyway. We have different criteria for classifying original songs, for example. The way I see it, for VocaDB saving the publish date and ignoring specific time is a good compromise between simplicity and completeness, unless there's an important use case that requires saving the publish time.

**Comment by goomie** [comment]
I have a few large lists that are ordered by publish time, so it would be convenient to be able to reference VocaDB directly for this instead of manually checking Nico.

**Comment by riipah** [comment]
For features like this, it requires significant planning. How to do the UI, how should it work when time is not available/provided. I just don't consider it worth the effort.
