### ISSUE TITLE
I can't add a piapro media

### ISSUE THREAD

**Issue by ghost** [VocaDB/vocadb#524]
https://vocadb.net/S/261127

i want to add this piapro link : https://www.piapro.jp/t/1ocj

and then i have a message : " Unable to get a response from the server, try again later "

**Comment by riipah** [comment]
Please please, report Piapro-related issues [in the Piapro repository](https://github.com/riipah/piapro-dotnet). The Piapro parser is notoriously fragile because it's using HTML scraping, so if they change anything, it breaks.

**Comment by riipah** [comment]
And it worked for me, so maybe it was a temporary issue?

**Comment by goldenchild-vocadb** [comment]
Hi riipah, sorry for posting this report in the wrong section, about the issue, i tried to submit it first when i created the song entry, that's why i added the link in the comment section, then i tried again few minutes ago (and failed), that's why i created this issue. Well, thanks for adding it.

**Comment by riipah** [comment]
The timeout is a little bit too short (1 second), so if Piapro is being slow, it may not be enough. I can increase it.

**Comment by riipah** [comment]
Huuh, I think it's not the timeout. They must've renewed the certificate or something. www.piapro.jp is returning an invalid certificate, but of course you can't see it when browsing the website because it redirects to piapro.jp. So https://piapro.jp/t/1ocj works, but with www it gives that error.
