### ISSUE TITLE
Event series name error / event name already in use bug

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/vocadb#532]
**Describe the bug**
I added a new event series called [Comiket Special](https://touhoudb.com/Es/153/comiket-special) - a set of side-events of well-known [Comiket](https://touhoudb.com/Es/1/comiket). I tried to add a 4th edition of the side-event, but encountered an error like this:

> Unable to save properties.
> Event name already in use: コミックマーケットスペシャル 4

I've tried to get around this problem by changing event number (didn't work) and series event name (I initially thought it's because of the name clashing with regular Comiket events) When I removed "コミックマーケットスペシャル" and "こみっくまーけっとすぺしゃる"  aliases from side-event series entry, I could save the event entry.

**To Reproduce**
1. Create an event series with a long alias in Japanese (such as "コミックマーケットスペシャル").
2. Click on "+ Create event" on the event series page.
3. Fill fields as usual (event number, date, venue, some links, without image).
4. Click "save changes".

The page will be reloaded with the mentioned error above the filled event entry form.

**Expected behavior**
One of two options:
1. Event name is too long warning/error when editing event series entry,
2. Event entry will be saved without issues.

**Desktop:**
 - OS: Windows 7
 - Browser: Firefox 67

**Comment by riipah** [comment]
It's not about the length. It's not obvious, but VocaDB considers hiragana and katanana equal. This is the same behavior as many other apps have. For example, in Google Chrome browser, if you search for "コミックマーケットスペシャル", it also highlights "こみっくまーけっとすぺしゃる". For VocaDB (and other apps such as Google Chrome), those two strings are equal, thus the duplicate name error. Can you verify that this is the case? From the code I don't see it's possible to get this error when name is too long.

**Comment by Nefere256** [comment]
I haven't consider the case VocaDB could detect the event with such names as a duplicate of itself...

I checked the issue with [test event series](https://touhoudb.com/Es/154/test) and you're right - I can't add an event with both "てすと" and "テスト" as a name (neither if both strings are aliases or as a main name+alias set).

**Comment by riipah** [comment]
Yeah, it also checks duplicates for the event itself.
