### ISSUE TITLE
Search derivative songs by original version

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/vocadb#534]
**Is your feature request related to a problem? Please describe.**
People in Touhou community often categorize arrangements not only by genre or an artist, but by original song. Sometimes I find it difficult to find a song I once added to the database: I know the theme, I know the artist, I know I liked it, but it takes a while to find it. The feature would give more possibilities to explore the database.

**Describe the solution you'd like**
It's quite similar to https://github.com/VocaDB/vocadb/issues/1355 (search derivative songs of a given artist's works) - a new filter in song search options. It would be nice to search songs by original along with other search options, like:
* by artist (ex. to search all [Plain Asia](https://touhoudb.com/S/93) remixes by [D.watt](https://touhoudb.com/Ar/24), as it's his favorite song),
* by tag (especially genre tags).

The feature would be useful on databases other than TouhouDB to search covers of popular songs (but most of them have the title unchanged).

**Describe alternatives you've considered**
The current search options allow searching by name, but arrangements often got new titles and it's hard to find them once forgotten. The other way is to look in alternate versions section of an original song, but it's better to search by artist and not by specified genre.

**Additional context**
I'd like to see the filter looking like that:
![original version search](https://user-images.githubusercontent.com/46942248/71446838-2d46a100-2728-11ea-8844-c7f1ca58e18e.png)

The input would be allowed for originals and derived songs (or any type that is allowed to have derived entries). The additional checkbox would be to search for indirect derived songs, ex. [original U.N. Owen was Her](https://touhoudb.com/S/4784) -> [instrumental Christmas arrange](https://touhoudb.com/S/17441) -> [rap vocal over Christmas instrumental](https://touhoudb.com/S/17453).

**Comment by riipah** [comment]
On VocaDB this was not needed, but I understand the need on TouhouDB. It should be relatively easy to add.

**Comment by riipah** [comment]
How important is that "include indirect results"? Do you think it could automatically search the whole hierarchy (is if always checked)?

**Comment by Nefere256** [comment]
Sure, I agree with you. I wanted to highlight there's a hierarchy to be aware. The full hierarchy searching will be enough, the direct derivatives search option would be used only by picky users, ex. to find arrangements of [Love-Colored Magic](https://touhoudb.com/S/249) without derivatives of [Love-Colored Master Spark](https://touhoudb.com/S/77).

**Comment by riipah** [comment]
Ok. Also, I should note that the depth of hierarchy is limited. Usually I've had maximum of 3 levels (for child voicebanks at least). If we need more, it gets complicated because we'd have to maintain a list of parent songs.

**Comment by riipah** [comment]
Note #2: this is going to make #58 even more difficult. Good thing we're probably never going to do it :).

**Comment by riipah** [comment]
This is done and deployed on TouhouDB. Please test and give feedback.

**Comment by Nefere256** [comment]
Thanks, the search by a parent song works - I tested searching with every search option. I'm happy it works with "in my collection" checkbox so I can search for my favourite songs of any theme.

I don't know if it's related, but adding/removing tags in entries (checked for songs, albums and artists) seems broken (clicking "save" button in tags window doesn't make changes in tags list). The problem appears in TouhouDB but not in VocaDB.

**Comment by riipah** [comment]
I had to run migrations due to unrelated change
