### ISSUE TITLE
Knockout.Punches converts double curly-brace syntax input by users to a virtual element

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#542]
For example, if an album description contains `{{expression}}`, it is converted to `<!--ko text:expression--><!--/ko-->` by `ko.punches.enableAll()` in [vocadb/VocaDbWeb/Views/Album/Details.cshtml](https://github.com/VocaDB/vocadb/blob/a29a6a3ee2f300d87aeaa39ebaf7d039168bb515/VocaDbWeb/Views/Album/Details.cshtml#L495).

**Comment by riipah** [comment]
Right. Do you think it's a real issue, would any albums have that description? Can we just escape it? Or maybe we can skip specific elements from KO punches evaluation.

**Comment by ycanardeau** [comment]
I'm not sure whether or not an album has that description, but if there is one, it causes `Uncaught SyntaxError: Unable to parse bindings.` and the page cannot be loaded. I haven't found out the appropriate solution yet, so I submitted this issue.

**Comment by riipah** [comment]
Perhaps we could apply StopBinding to all description/comment fields. It should take care of this.

**Comment by riipah** [comment]
StopBinding seems to be working.

**Comment by ycanardeau** [comment]
With this method, you'll have to apply StopBinding not only to the Description field, but also to all fields that can be edited by users. For example, if a user inputs `{{{'<i>Hello World!</i>'}}}` in the Non-English name field of an album, it is rendered as HTML (`<script>` tags don't work for some reason). I guess this is not an expected behaviour.

**Comment by ycanardeau** [comment]
Fixed in #1245.
