### ISSUE TITLE
Mass-alignment of reprints with existing songs

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#545]
**Is your feature request related to a problem? Please describe.**
1. A mass reprinter exists on YouTube.
2. You have found at least one video on their channel that has vanished from Niconico.
3. Idea: Compare their channel with the VocaDB song database, linking reprints to existing songs and maybe finding missing songs at the same time.

**Describe the solution you'd like**
Something like the existing "Import from the YouTube" page, but looking for possible existing songs.

**Describe alternatives you've considered**
looking up songs manually?

**Additional context**
I did consider working on this idea myself, but I haven't put any effort into actually thinking about implementation. Is this possible with the existing API? I don't know! I leave this here in case someone else wants to think about it too. It's not a terribly important idea, IMO.

**Comment by riipah** [comment]
Of course, this assumes the reprinter kept the title from Nico Nico as is? Otherwise there would be a lot of "missing songs" that are not identified. Or what would you suggest for matching the songs?

**Comment by szc126** [comment]
For matching songs, potential methods that I thought of are:
1. by title
2. by searching for a NND ID in the description
3. manual searching
Perhaps as fallbacks, or providing all three at once.

**Comment by szc126** [comment]
I've made a script in Python that has been satisfactory. →https://github.com/szc126/vocadb-sc
