### ISSUE TITLE
Prevent multiple account creation with email aliases

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#564]
Recently I've seen spammers creating multiple accounts using email aliases, that is user+1@gmail.com, user+2@gmail.com, user+3@gmail.com etc. IP is different, so blocking IP doesn't help.

We should either add option to ban email address, with aliases, or prevent creating multiple accounts (including disabled) with the same email, ignoring alias.

That is, either we ban user+*@gmail.com or we consider user+1@gmail.com and user+2@gmail.com the same so that only one of them can exist. I think the latter one makes more sense and should be easier to implement too.

**Comment by ycanardeau** [comment]
We have to consider not only user+1@gmail.com, user+2@gmail.com and etc., but also us.er@gmail.com, u.s.e.r@gmail.com and etc. the same because [dots don't matter in Gmail addresses](https://support.google.com/mail/answer/7436150).

**Comment by riipah** [comment]
Good point, I didn't know that. I've only seen the + aliases. I think the dots will be more difficult to check...

**Comment by ycanardeau** [comment]
Can be closed now?
