### ISSUE TITLE
The list of supported embeds needs updating

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#565]
> Supported services: YouTube, NicoNico, Vimeo, SoundCloud, Piapro, Bilibili and Creofuga.

Bandcamp is missing, maybe some other services I don't know about do as well.

**Comment by ycanardeau** [comment]
You can fix this by editing [VocaDbWeb.Resources/Resources/Views/Album/EditStrings.resx](https://github.com/VocaDB/vocadb/blob/master/VocaDbWeb.Resources/Resources/Views/Album/EditStrings.resx#L232). We should not edit resource files directly, but I'll do the rest.

**Comment by kateabr** [comment]
@ycanardeau Fixed

What do you mean by the rest? Is there something more to this?

**Comment by ycanardeau** [comment]
Some files on VocaDb projects are auto-generated by tools. Please see [here](https://github.com/VocaDB/vocadb/commit/259ce0b709f0ccfc0d04824132a0a9e7e621564b). Actually, we should not include those files in git. We need some updates to `.gitignore` too. You need [Visual Studio](https://visualstudio.microsoft.com/) to edit resource files, but it takes a few hours to install it. You can add more translations to the same folder.
