### ISSUE TITLE
Unable to connect with Twitter

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/vocadb#568]
**Describe the bug**
Actually it's a bug discovered by one of new users in TouhouDB, but I found out I'm experiencing the problem too.

**To Reproduce**
1. Log in to Twitter in the same browser (optional)
2. Go to your own profile page > My settings > Conectivity
3. Click on "Connect" under a Twitter label

You'll see a text "There was an error while connecting to Twitter - please try again later." in red box. The browser also navigates to the first tab of "My settings" page.

**Expected behavior**
Any step that would lead to connect a profile with Twitter - a Twitter page asking for permission to connect, "connect complete" box etc.

**Desktop:**
 - OS: Windows 7
 - Browser: Firefox 67, Chrome 79

**Comment by riipah** [comment]
The twitter login is notoriously unreliable because they keep changing the API and they never notify in advance :/. I'll try to investigate.

**Comment by riipah** [comment]
I added it to TouhouDB. Can you test it?

**Comment by Nefere256** [comment]
Sure.

Connecting, disconnecting and log in via Twitter work in Chrome and Firefox.

Thank you very much for fixing this :)
