### ISSUE TITLE
Associating a song with multiple parent (original) versions

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#58]
Mostly useful for mashups. Has been requested a few times, for TouhouDB as well.

Would obviously require changing the current association from one-to-many to many-to-many. Could possibly make the performance worse. To mitigate performance penalty we could still use the old original song property to minimize the number of times the collection needs to be accessed. 

Still need to evaluate whether it's feasible to implement due to increased complexity and lower performance.

Also need to consider how to implement "filter by parent version" feature. Probably the many-to-many list would need to include the whole parent hierarchy, and maintaining that could be very complicated.

Open issues: if multiple parents are specified, from which should the lyrics and characters be inherited? Could we always use the first parent song (most derived songs only have one parent anyway)?

**Comment by ycanardeau** [comment]
This could be done by #558.

**Comment by dset0x** [comment]
@ycanardeau Perhaps linked to the wrong issue? How is BPM related to multiple song inheritance?

**Comment by ycanardeau** [comment]
@dset0x No, it's not wrong. Originally I was thinking having multiple offset-length pairs (which is overly complicated) to support variable BPM.

| Offset in seconds | Length in seconds | BPM | Song (nullable) |
| --- | --- | --- | --- |
| 0 | 10 | 100 | Song 1 |
| 10 | 10 | 200 | Song 2 |
| 20 | 30 | 50 | Song 3 |

**Comment by dset0x** [comment]
Oh, I think this is too much. I might also not be applicable to many songs.

Do you have a use-case for trying to maintain so much information?

**Comment by riipah** [comment]
I also don't recommend this suggestion. It sounds too complicated for the main website. If necessary, such information could be on a related website.

>Do you have a use-case for trying to maintain so much information?

I can imagine mashups at least?

**Comment by ycanardeau** [comment]
> Do you have a use-case for trying to maintain so much information?

Yes. For example, [this song](https://vocadb.net/S/194659) could be associated with 26 parent songs.

**Comment by dset0x** [comment]
> 
> 
> > Do you have a use-case for trying to maintain so much information?
> 
> Yes. For example, [this song](https://vocadb.net/S/194659) could be associated with 26 parent songs.

Oh, I understand having multiple parent songs, but I wonder if making a table like the example you gave is generally useful (where you maintain not only the relationship, but also the timing)
