### ISSUE TITLE
Allow moderator to hide a revision

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#606]
Because of personal identifiable information. Hidden revision details are visible only for users with the hide role. Hidden revisions will still be used for getting properties, but those properties are assumed to be hidden by newer revisions. Hidden revisions can be shown in revisions listing, but only title + summary, without details.

**Comment by ycanardeau** [comment]
Should we have a boolean field (e.g. `Hidden`) or an enum type with the `Flags` attribute (e.g. `RevisionVisibilityRestrictions`)? [MediaWiki](https://www.mediawiki.org/wiki/MediaWiki) uses the latter method and the enum has three values: `Content`, `EditSummary` and `Username`. Or we could have an enum like `RevisionVisibility` with values `Visible` and`Hidden`.

**Comment by ycanardeau** [comment]
Should we have a boolean field (e.g. `Hidden`) or an enum type with the `Flags` attribute (e.g. `RevisionVisibilityRestrictions`)? [MediaWiki uses the latter method](https://www.mediawiki.org/wiki/Help:RevisionDelete) and the enum has three values: `Content`, `EditSummary` and `Username`. Or we could have an enum like `RevisionVisibility` with values `Visible` and`Hidden`.

**Comment by riipah** [comment]
I think a boolean should be enough.

**Comment by ycanardeau** [comment]
Do we need to be able to make hidden revisions visible again? I used `AuditLog` to log who changed revision visibilities (please see [here](https://github.com/VocaDB/vocadb/pull/608/commits/e0babc16176b64c3f9e57aa65868a0681f952b50)), but should we add `HiddenBy` and `HiddenAt` fields similar to entry reports?

**Comment by riipah** [comment]
AuditLog is enough for logging who changed it and when. No need special database fields for now. It's fine like this.

Probably we want to have some way to restore hidden revisions, but that is not needed right away either.
