### ISSUE TITLE
Cannot save one album with artists added to a tracklist

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/vocadb#611]
**Website**
TouhouDB

**Describe the bug**
I wanted to finish 8th ambient album by Stas Garvik https://touhoudb.com/Al/2666 which doesn't have a finished tracklist, but I couldn't add artists by editing the album. The 'Save changes' button leads to an error page.

**To Reproduce**
1. Go to https://touhoudb.com/Al/2666
2. Click on 'Edit' button
3. Click on 'Tracks' tab
4. Select one/few/all tracks (the number of them doesn't matter)
5. Click on 'Set artists for selected tracks' link
6. Click on 'Stas Garvik' button
7. Click on 'Add to tracks' button
8. Click on 'Save changes' button
9. See error

**Expected behavior**
The album and songs are updated with an artist added.

**Desktop:**
 - OS: Windows 7
 - Browser: Firefox 67

**Additional context**
The album can be saved if I made no edits. I don't think it's because the tracklist is large - I've never had such a problem with compilation albums by Toranoana or Melonbooks.

**Comment by riipah** [comment]
I believe it was the same problem as [here](https://vocadb.net/Al/28582). I deployed it on TouhouDB as well. It happened when making artist changes to multiple tracks on the album page.
