### ISSUE TITLE
GoogleBot can't find the lyrics

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#630]
Compare `あれ、なんだかアタシの名前みたい（笑）` with `site:vocadb.net あれ、なんだかアタシの名前みたい（笑）` on Google Search.

**Comment by riipah** [comment]
https://developers.google.com/search/docs/guides/fix-search-javascript

It sounds like adding history API URLs (client-side routing) to the tabs on song pages could fix the problem.

**Comment by ycanardeau** [comment]
I think we can use the history API for the search page as well. For example, if I search a song, click it and go back to the search page, then the search result will be lost.

**Comment by riipah** [comment]
Ideally yes, but for the search page it's going to be much more complicated because there is so many options. For song/artist/album pages it's much easier.

**Comment by ycanardeau** [comment]
What should the URL look like? For example, `https://vocadb.net/S/186287/Lyrics/54513`?

**Comment by riipah** [comment]
Something like that yes, maybe lowercase "l" and maybe you could append the language too. So, ```https://vocadb.net/S/186287/lyrics/54513/english```

**Comment by ycanardeau** [comment]
I noticed that comments in the Discussion tab on the song details page are indexed by Google. And I think I found the cause of this issue. If you access the following URL directly, the lyrics won't appear. https://vocadb.net/S/186287#lyricsTab

**Comment by riipah** [comment]
Right. Well, fixing that could be a quick fix, so that the content loads when navigating to URL directly.

But I think that overall, routing to tabs by URL fragment (#) is not so recommended anymore. Using the history API with proper client side routing (/S/3939/lyrics...) would still be better in the long run.
