### ISSUE TITLE
Missing implementation for ignoreIds parameter in /api/albums/top

### ISSUE THREAD

**Issue by TheCardinalSystem** [VocaDB/vocadb#639]
**Website**
VocaDB

**Describe the bug**
The API is missing an implementation for the `ignoreIds` parameter in `/api/albums/top`. In the documentation it requests that `ignoreIds` is passed as the body of a POST request, however the endpoint only accepts GET requests

I attempted passing the values as URL parameters and headers, but to no avail. Interestingly enough, the documentation says that `ignoreIds` is a *required* field.

**To Reproduce**
1. Go to [https://vocadb.net/swagger/ui/index](https://vocadb.net/swagger/ui/index)
2. Click on AlbumApi
3. Click on `/api/albums/top`
4. Add values to `ignoreIds` text field
5. Click "Try it out!"
6. Repeat steps 4 and 5 with different values

**Expected behavior**
The result is expected to exempt albums with ids matching those in the `ignoreIds` field sent with the request.

**Screenshots**
![image](https://user-images.githubusercontent.com/27778301/97784894-296d8180-1b78-11eb-996f-a8965002e34b.png)
![image](https://user-images.githubusercontent.com/27778301/97785041-1dce8a80-1b79-11eb-9f8f-a8b5528dbfe6.png)
![image](https://user-images.githubusercontent.com/27778301/97785115-73a33280-1b79-11eb-8284-a54e1a4c0e6a.png)
![image](https://user-images.githubusercontent.com/27778301/97785136-95041e80-1b79-11eb-99c7-ef04616c58a1.png)
![image](https://user-images.githubusercontent.com/27778301/97785149-a64d2b00-1b79-11eb-90f5-1dfdd2a77f15.png)
![image](https://user-images.githubusercontent.com/27778301/97785168-be24af00-1b79-11eb-91d8-f2950c878b24.png)

**Comment by ycanardeau** [comment]
Thank you!
