### ISSUE TITLE
TouhouDB - Rename song list categories

### ISSUE THREAD

**Issue by Shyany** [VocaDB/vocadb#641]
We currently have the same 4 categories for song list on TouhouDB as we have on VocaDB.

    Concert setlists
    Vocaloid rankings
    Pools
    Other

**Concert setlists**
I know for sure that [SOUND HOLIC](https://touhoudb.com/Ar/14) does some concerts from time to time (for example [here](https://www.youtube.com/watch?v=n7ABi7KYzAg)). I don't know if that's enough to keep the category, tho. Some of the bigger Touhou circles make music livestreams on YouTube ([like this](https://www.youtube.com/watch?v=zoZX7chNAhM&t=115s) or [like this](https://www.youtube.com/watch?v=BfNysjgFUIk)). Maybe this would count as a "concert" as well if it's done by the official arranger. 

**Vocaloid rankings**
This... shouldn't be there. This _could_ be renamed into Touhou rankings but I doubt our editor community is big enough for this. I can't really give you a good replacement by now, the first thing that came to my mind was to give ZUN/Game related playlists ([see here](https://touhoudb.com/L/11)) a special category. Or to archive YouTube mixes ([like this](https://youtu.be/Ws_AbuXqlvY)) via the song list feature for overview purposes and make this a special category.

**Pools, Other**
These are fine.

**Comment by riipah** [comment]
Sounds like it's best to just hide the extra categories, instead of renaming them.

**Comment by Shyany** [comment]
Yeah, that would work as well.
