### ISSUE TITLE
Move comments into one table

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#643]
The current schema looks like this:

**AlbumComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | |
| Message | nvarchar(4000) | |
| Album | int | |

**ArtistComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | |
| Message | nvarchar(4000) | |
| Artist | int | |

etc.

***

Solution 1 (inspired by activity entries):

**Comments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | |
| Message | nvarchar(4000) | |
| EntryType | varchar(20) | |
| Album | int | ✔️ |
| Artist | int | ✔️ |
| DiscussionTopic | int | ✔️ |
| ReleaseEvent | int | ✔️ |
| Song | int | ✔️ |
| SongList | int | ✔️ |
| Tag | int | ✔️ |
| User | int | ✔️ |

***

Solution 2 (inspired by MusicBrainz):

**Comments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | |
| Message | nvarchar(4000) | |

**AlbumComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Album | int | |
| Comment | int | |

**ArtistComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Artist | int | |
| Comment | int | |

etc.

**Comment by riipah** [comment]
Table-per-hierarchy (TPH) inheritance strategy, same activity entries. This is the most efficient strategy if multiple types of entities ever need to be listed.

**Comment by ycanardeau** [comment]
The current schema looks like this:

**AlbumComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | ✔️ |
| Message | nvarchar(4000) | |
| Album | int | |

**ArtistComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | ✔️ |
| Message | nvarchar(4000) | |
| Artist | int | |

etc.

***

Solution 1 (inspired by activity entries):

**Comments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | ✔️ |
| Message | nvarchar(4000) | |
| EntryType | varchar(20) | |
| Album | int | ✔️ |
| Artist | int | ✔️ |
| DiscussionTopic | int | ✔️ |
| ReleaseEvent | int | ✔️ |
| Song | int | ✔️ |
| SongList | int | ✔️ |
| Tag | int | ✔️ |
| User | int | ✔️ |

***

Solution 2 (inspired by MusicBrainz):

**Comments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Id | int | |
| Author | int | ✔️ |
| Message | nvarchar(4000) | |

**AlbumComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Album | int | |
| Comment | int | |

**ArtistComments** table:
| Name | Data Type | Allow Nulls |
| --- | --- | --- |
| Artist | int | |
| Comment | int | |

etc.

**Comment by riipah** [comment]
The musicbrainz schema is an example of table per type (TPT). Usually I would prefer that if the subclass has a lot of properties not found in the base class. But in this class it's just the associated entity. Downside is that it still needs to join data from multiple tables. Can you make sure that NHibernate supports querying the base type (Comment) when using this inheritance strategy? I can't remember anymore. But in any case, I still think everything in one table (TPH) makes more sense for comments because all the other properties are the same.
