### ISSUE TITLE
Albums not showing up correctly on song entries

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#652]
There is a problem with the display of albums on song entries. See Screenshot:
![screen](https://user-images.githubusercontent.com/52045122/100087267-c3aaa780-2e4e-11eb-9ddd-aafb439b1160.PNG)

**Comment by ycanardeau** [comment]
Fixed by #651 and deployed. Thanks for reporting!

**Comment by riipah** [comment]
What was causing it?

**Comment by ycanardeau** [comment]
I've added a comment.
