### ISSUE TITLE
Filters on own user edits/addition page

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#654]
I think it would be nice to have filters also displayed [on the edits and additions page on the user page](https://vocadb.net/User/EntryEdits/1083?onlySubmissions=False). Currently using Ctrl+F to find specific entries that I edited. For example, only artist additions or songs. I know the audit log can be used for that as well but this way it is easier and also other users can profit from this.

**Comment by ycanardeau** [comment]
Can I add a link to your entry edits page as a reference?

**Comment by andreoda** [comment]
Sure!
