### ISSUE TITLE
Display for all comments that a user made

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#655]
I would like to see all of my comments that I made on VocaDB. The user page says that I made 494 comments so far. It can be useful to check older comments regarding an issue etc.
Maybe a page could open when clicking on "comments: xxx".

**Comment by riipah** [comment]
I'd say #643 is a pre-requirement for this, otherwise it will be complicated.

**Comment by andreoda** [comment]
You mean layout-wise?

**Comment by riipah** [comment]
Technical implementation and performance.

**Comment by riipah** [comment]
It would be good to reuse the page for "recent comments" listing (at /Comments). No need to maintain two separate implementations, and it should be more clear for the user also. The comment author could be just another filter on that page. The layout would be the same also, including grouping comments by entry (to avoid repeating entry information).
