### ISSUE TITLE
Mark external links as unavailable

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#656]
Just like the links for media, it would be nice to have a field for the external links to mark them as dead/empty/deleted.
Useful for artist entries, since removing external links is not a wise option and it will be easier (especially for regular users).

![screen](https://user-images.githubusercontent.com/52045122/100111962-fd8ba600-2e6e-11eb-8102-de91b984ac40.PNG)

![screen2](https://user-images.githubusercontent.com/52045122/100111967-ff556980-2e6e-11eb-9f25-7028e010529e.PNG)

**Comment by ycanardeau** [comment]
We could automatically replace those links with [Internet Archive](https://archive.org/).

**Comment by Nefere256** [comment]
> We could automatically replace those links with [Internet Archive](https://archive.org/).

By the way, the automatically archiving pages feature was recently added to [VGMdb](https://vgmdb.net/forums/showpost.php?p=98064&postcount=94):
> Submitted and edited links are automatically queued for archiviation on the Wayback Machine, preventing important data and sources from being lost forever.
This also applies to links used in the comment field mentioned above.

A recent example with TouhouDB link: [DAYDREAM TUNES album](https://vgmdb.net/album/47500).

**Comment by ycanardeau** [comment]
@Nefere256 Thanks for your useful info. Could you please submit a new issue for that?
