### ISSUE TITLE
Default sorting events on venue page by date

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/vocadb#657]
**Describe the bug**

If a venue hosts more than one event series, the list of events gets messy as events are sorted by series number. Example: any venue with events of multiple series: [Miyakomesse](https://touhoudb.com/Venue/Details/17), [Nagomix](https://touhoudb.com/Venue/Details/14) or [PiO](https://touhoudb.com/Venue/Details/21).

Usually venue schedules are sorted by date or in calendar form, ex. [nagomix](http://nagomix.co.jp/schedule), [Kyoto Swallow Tail](https://swallowtail.asia/?page_id=16) or [Always Umeda](http://www.always-live.info/Live2020-11.html).

**Comment by ycanardeau** [comment]
Could you please review #658?
