### ISSUE TITLE
Playlist view has song list below player and is extra wide 

### ISSUE THREAD

**Issue by Ninten-Droid** [VocaDB/vocadb#662]
**Website**
VocaDB 

**Describe the bug**
The "Playlist" view when looking at a list of songs on the site now sits below the embedded player and is unnecessarily wide. It used to be right next to it. 

**To Reproduce**
1. Go to a list of songs, either through the search function or on an artist's page
2. Click on 'Playlist'
3. See error

**Expected behavior**
The playlist view is expected to be the embedded player and the list of songs, side by side.

**Screenshots**
![image](https://user-images.githubusercontent.com/3254864/100277444-283e3300-2f31-11eb-825b-1de0b1486002.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, latest version

Not sure if this change was intentional but it seems like a bug to me considering the list is so offset and oddly wide.

**Comment by Nefere256** [comment]
The width of the song list is related to song's titles. If you scroll the song list (ex. on "Recent PVs" search page) few times, then the song list will widen to fit song titles and finally - will move under the embedded video player.

The workaround is to change zoom in a browser with <kbd>CTRL</kbd> + <kbd>+</kbd> / <kbd>CTRL</kbd> + <kbd>-</kbd> and <kbd>CTRL</kbd> + <kbd>mouse wheel up</kbd> / <kbd>CTRL</kbd> + <kbd>mouse wheel down</kbd>. The list and the player beside will change sizes and they'll  finally fit in one row.

Some examples (for testing purposes) of song lists with titles that greatly widens the list in "Original" display language (on a 1280x768 screen with 100% browser zoom set):
* [sansuiP](https://vocadb.net/Ar/532) songs,
* [shizen-no-tekiP](https://vocadb.net/Ar/552) songs.

**Comment by Ninten-Droid** [comment]
Ah I see, so it was intentional.
Thank you for the response.
