### ISSUE TITLE
Tag page failing

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#666]
**Website**
VocaDB

**Describe the bug**
[rock](https://vocadb.net/T/481/rock) tag page lags and throws an error after about 30 seconds.

**To Reproduce**
1. Go to page (happened just now).

**Expected behavior**
Display tag page.

**Additional context**
Probably a timeout? Figure out the query and simplify it, or catch the error.

**Comment by ycanardeau** [comment]
```SqlException Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.```
