### ISSUE TITLE
Song publish date tooltips displaying wrong

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#670]
**Website**
VocaDB

**Describe the bug**
When hovering over the calendar icon next to song title, to show publish date, tooltip appears but is full screen wide.

Might affect other tooltips as well.

**To Reproduce**
1. Go to https://vocadb.net/Ar/84968
2. Hover over any calendar icon next to song title

**Expected behavior**
Publish date appears in tooltip

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chromium

**Comment by ycanardeau** [comment]
Fixed, thanks for reporting! For your information, [jQueryUI Tooltips were competing with Twitter Bootstrap](https://stackoverflow.com/questions/13731400/jqueryui-tooltips-are-competing-with-twitter-bootstrap). I've just removed it since it is not necessary.

**Comment by riipah** [comment]
Thanks for fixing it :)
