### ISSUE TITLE
Updating development instructions

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#680]
Now that we are using Laravel Mix, the [development environment](https://github.com/VocaDB/vocadb/wiki/VocaDB-development-environment) wiki document should be updated.

Intall node with npm. Which node version is required?

**Comment by ycanardeau** [comment]
I updated the wiki. Is there still something that needs to be added?

**Comment by riipah** [comment]
I updated it a bit too, it's fine  for now.
