### ISSUE TITLE
Tracklist editor bug

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#682]
**Website**
VocaDB

**Describe the bug**
User "Plyn" reported that the tracklist editor is not working.
-> Tracklist editor is glitching out when trying to arrange the songs in an album entry.

**To Reproduce**
1. Go to https://vocadb.net/Al/29395
2. Try to sort the tracklist

**Comment by ycanardeau** [comment]
Fixed, thanks for reporting the issue!
