### ISSUE TITLE
Separating album ratings from ownership, adding reviews

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#70]
It's more clear to have ratings separate from album collection. Additionally, optional review text could be added. These reviews and ratings could be displayed similar to comments, perhaps on a separate tab. Review date could also be displayed. It would probably be useful to set review language.

**Comment by riipah** [comment]
The main thing I'm thinking about is how to migrate the current album ratings: should the reviews be completely separate from user's album collection? Ratings are displayed on the collection page and I think we want to keep it that way.

**Comment by riipah** [comment]
I'm thinking it should be possible to give a review and rating independently of each other, but if both are given, then the rating is also displayed next to user's review. Unlike Discogs, I would prefer separating reviews from comments. Another tab might be good.

**Comment by Nefere256** [comment]
I think reviews should be separated from user's album collection. The user isn't obliged to have the album to write an opinion about songs that are released earlier on NicoNico/YouTube. And I assume many users would put an album into their collection with no constructive review to leave.

It would be nice to have an album status in the reviewer's collection. The reviews of users having the album seems to be more reliable.

I checked some websites you mentioned:
* MusicBrainz: even if it's hard to find reviews in desired language on CritiqueBrainz, [the API](https://critiquebrainz.readthedocs.io/api/endpoints.html#reviews) allows to filter them by language. A list of supported languages is available via another endpoint.
* Discogs: I'm not sure about adding many reviews to a single album, but [the guidelines](https://support.discogs.com/hc/en-us/articles/360004982673-How-To-Post-A-Review) discouraged adding the same review for all album releases separately.

**Comment by riipah** [comment]
Is there need to submit review in multiple languages by the same user? This would make it more complicated because of supporting many instances instead of just one. If we limit it to one review per person per album it's more simple to implement, but then you can submit your review in just one language.

**Comment by riipah** [comment]
Backend work done. Still needs UI work. 

I decided to make another table for reviews anyway because it's cleaner data model.

**Comment by riipah** [comment]
It was more work than I expected, but basic functionality is done now. Still need to add album reviews on front page somehow.
