### ISSUE TITLE
Remove extra spaces in album artist list

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#702]
If you check any album page with multiple artists, the artists list contains extra spaces before comma and role.

For example [here](https://vocadb.net/Al/49) and [here](https://vocadb.net/Al/29486).

```
hansi  (Illustrator), KagomeP  (Mastering), Momopan  (Illustrator, Other), (Mienohito )

Ann-MeltsP , emon , iroha(sasaki) , LeleleP , mothy , WorldwideP
```

Likely caused by Razor, it's a common issue.

**Comment by ycanardeau** [comment]
Thanks for reporting!
