### ISSUE TITLE
Git history of localization files is interrupted

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#709]
Low priority:

New localization files (`VocaDbWeb.Resources/App_GlobalResources/AlbumArchiveReasonNames.Designer.cs`) were created in ba9704831002f0c22bbd01bf714dd9780c25f099 and old localization files (`VocaDbWeb/App_GlobalResources/AlbumArchiveReasonNames.Designer.cs`) were deleted in ece2c19486467e20cd2b03b69e1d98553338fdba.

When viewing file history, the history of the new files starts in July with ba9704831002f0c22bbd01bf714dd9780c25f099, instead of being continuous. Repairing this would ease attribution and history investigation.

**Comment by ycanardeau** [comment]
See isaacs/github#900.
