### ISSUE TITLE
Random song/album/artist/event button

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#732]
Requested/Feedback of the survey: A random button for songs, albums, artists, events on the main page or somewhere in the header, navigation bars (appearing anytime) or search page.

**Comment by ycanardeau** [comment]
As you mentioned, we already have that feature. http://vocaloid.eu/vocadb/random-page/

**Comment by andreoda** [comment]
Please continue reading.

**Comment by ycanardeau** [comment]
As a rule of thumb, I don't implement features that are already implemented, regardless of on-site or off-site, unless that are requested by a lot of people.
