### ISSUE TITLE
Artist page: Show "Manager of"

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#739]
UTAU vocalists have fields `Illustrator`, `Character designer`, `Voice provider`, `Manager`, etc.

On the corresponding artist pages one can see `Illustrator of`, `Voice provider of`, but not `Manager of`. I think that it would be a good field to show. Sometimes it's clear who owns an UTAU character, but other details such as voice provider, etc. are not clear.

It is jarring that artist entries for \<Person A> and \<Person B> do not show that \<Person A> is the owner of \<UTAU A>, but show that \<Person B> is the character designer of \<UTAU A>.

**Comment by ycanardeau** [comment]
@szc126 I've created a pull request for this issue (#745), could you please review it?
