### ISSUE TITLE
"Kana reading" field for Japanese names

### ISSUE THREAD

**Issue by szc126** [VocaDB/vocadb#740]
Most atwiki.jp and dic.nicovideo.jp entries have the pronunciation of the entry title written in hiragana. It's also sometimes given for usernames, UTAU names, etc.

For Japanese-language users of VocaDB, it can make searching easier (instead of having to input the precise kanji/katakana/hiragana used in a name: 唄 or 歌 or うた or ウタ, or inputting romaji), would be good for phonetic sorting, and would be a good addition to entries as well.

It is roughly related to the Romaji field, both being readings, but the Romaji field has potential searching barriers such as restoration of loanwords and word spacing, as opposed to a hiragana string.

**Comment by ycanardeau** [comment]
Could this be done as part of #10? AniDB and MusicBrainz will be useful as a reference.

**Comment by szc126** [comment]
I like that way of thinking of it.

**Comment by blueset** [comment]
Here is a dump of automated `ja-Hira` name notations based on http://vocaloid.eu/vocadb/dump.zip in 2021 Sep 04. Only the titles able to be confirmed automatically are included (with some manual additions).

Hope this helps
[vocadb_safe.csv](https://github.com/VocaDB/vocadb/files/7110966/vocadb_safe.csv)

**Comment by ycanardeau** [comment]
@blueset Thanks for your help! Note that the dump file isn't always up-to-date and it's manually done. Please let me know if you need the latest dump. By the way, I think it would be nice if you could share your automated script somewhere for future usage.

**Comment by blueset** [comment]
Thanks for the suggestion. I’ve uploaded the source to https://github.com/blueset/vocaloid-yomigana, along with some data from Vocaloid Wiki (Fandom/Wikia) and 初音ミク wiki (atwiki). Hope this helps.
