### ISSUE TITLE
Show yearly event in "upcoming events" based on series, without actual event

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#741]
For character anniversary/birthday events that happen every year at the same time, those events could be shown dynamically in upcoming events (and front page), without editor having to create that event entry.

This would reduce editor workload and clutter, when the yearly event doesn't have any songs, albums or links attached to it.

There should probably be a date field for event series (this would be useful anyway), and possibly a checkbox for automatically generating that dynamic event.

The dynamic event could have a link to series, or for creating the actual event, but this is not needed at first.

Is there other places where we should show the dynamic event?

**Comment by andreoda** [comment]
I am a bit confused about this. Is it only for character anniversaries? How does it work when you for example create a song with voicebank xxx and it's their "birthday"? Do you mean in the event field of the song, there you could type the name of the event without it existing and then the system creates the event automatically based on some pattern. What if there is no series for that event created yet?

**Comment by riipah** [comment]
>Is it only for character anniversaries?

Mainly for those, but not only for them. It's for any yearly recurring events, when you don't necessarily want to create an event page for each occurrence.

>How does it work when you for example create a song with voicebank xxx and it's their "birthday"?

This issue does not change that experience at all. This issue only concerns the "upcoming events" page and event listing on front page. It does not affect song edit page. The event page can be created as before. If the event page is created, it works exactly as before. 

>Do you mean in the event field of the song, there you could type the name of the event without it existing and then the system creates the event automatically based on some pattern. 

The current functionality is not changed by this task. I remember there is already some code for creating series event based on pattern. That could be used, but again, it's not necessary for this issue.

>What if there is no series for that event created yet?

You need to create the series first, as before. This issue is for adding an option to series. If the series does not exist or the option is not checked, nothing is done. This issue is mainly for recurring series that are already created, mainly character birthdays.

**Comment by andreoda** [comment]
alright, thanks for explaining!
