### ISSUE TITLE
Suggestion: Own section for voicebank birthdays

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#747]
A suggestion: An own section for voicebank/voice synth birthdays (not all character anniversaries, since some are not birthdays) on the main page and event page "upcoming events".
![grafik](https://user-images.githubusercontent.com/52045122/105327965-d67ff500-5bcf-11eb-9c0d-366002957e85.png)
and here
![grafik](https://user-images.githubusercontent.com/52045122/105328071-f0b9d300-5bcf-11eb-902d-9815f762ce1a.png)
So that they are not "mixed" with other events there. I think users would like that.

Associated issues:
- https://github.com/VocaDB/vocadb/issues/741
- https://github.com/VocaDB/vocadb/issues/720

**Comment by ycanardeau** [comment]
@andreoda Instead of adding a section for voicebank/voice synth birthdays, how about posting messages on Discord via webhook? How would you distinguish between voicebank/voice synth birthdays and other character anniversaries? By using the "birthday" tag?

**Comment by riipah** [comment]
Maybe we could consider adding a new event category for character birthdays? It might be confusing though, choosing which one to use.

**Comment by andreoda** [comment]
Yeah because actually there are two events that can happen: release day and character birthday that was assigned to the character. Both are somewhat birthdays and can also fall on to the same date.

**Comment by riipah** [comment]
Yeah but the system has to know unambiguously which one it is. And I dislike using special tags unless necessary because it's not obvious.

**Comment by andreoda** [comment]
The "Character release date anniversary" can be automatically recognized by the system by reading the (base-) voicebanks release date.
Maybe if a field for the "Character (fictional) birthday" exists for voicebank entries, the system can read it in this case as well.

About the event entries:
If that is the case, and for example the events will be created automatically by the system, not manually, either two events will be created, if the dates are different, or just one will be created, merging them together (because they are both on the same date).
Another option would be to have always two seperate event entries regardless of the date being the same.

**Comment by riipah** [comment]
Determining the anniversary/birthday event based on dates sounds complicated and fragile, since we have no good way of specifying the link between voicebank and event. We could make assumptions that single "participating artist" which is a voicebank with matching dates means it's an anniversary, but I can imagine situations where this is still not true.
