### ISSUE TITLE
Tag tooltips are wrong

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#768]
For every tag tooltip I'm getting "music producer".

**Comment by andreoda** [comment]
For me it looks like this:
![108112410-534ea380-7096-11eb-83d0-fe3217025611](https://user-images.githubusercontent.com/52045122/108113497-e50ae080-7097-11eb-8ec3-96bc09f97fec.png)
![108112457-695c6400-7096-11eb-970d-1e1c23b4e240](https://user-images.githubusercontent.com/52045122/108113504-e6d4a400-7097-11eb-9be2-2404be7a6189.png)

**Comment by ycanardeau** [comment]
Could be a browser issue, possibly related to caching. Try [F5], [Ctrl]+[F5] or [Shift]+[F5].

**Comment by ycanardeau** [comment]
`ResponseCache` should vary by query keys (`id` and `lang`).

https://github.com/VocaDB/vocadb/blob/f1ef5e040e82b0ba91f28531d4936542f856af2e/VocaDbWeb/Controllers/TagController.cs#L240
