### ISSUE TITLE
Unauthenticated APIs require CORS authentication

### ISSUE THREAD

**Issue by FinnRG** [VocaDB/vocadb#772]
**Website**
VocaDB / UtaiteDB / TouhouDB

**Describe the bug**
Since the new update, unauthenticated APIs require CORS authentication.
The exact error is: `Access to XMLHttpRequest at '[APIRequest]' from origin '[origin]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Expected behavior**
As stated here: [https://github.com/VocaDB/vocadb/wiki/Public-API](https://github.com/VocaDB/vocadb/wiki/Public-API), unauthenticated API requests like  /api/songs/byPv should work without authentication.

**Comment by andreoda** [comment]
Here is the German variant :D
![grafik](https://user-images.githubusercontent.com/52045122/108223720-631fc380-713a-11eb-8e16-b9fd6e0e2aa5.png)

**Comment by andreoda** [comment]
Maybe this helps for fixing it:
https://stackoverflow.com/questions/40869386/cors-authentication-with-asp-net-web-api-is-not-working

**Comment by ycanardeau** [comment]
See also https://github.com/VocaDB/vocadb/pull/701#discussion_r549267148.

**Comment by Shiroizu** [comment]
Possible temporary workaround: API requests work outside the browser (using python's requests-library for example).

**Comment by ycanardeau** [comment]
@dset0x @Pyther99 Could you please review #783?
