### ISSUE TITLE
Edit song tags on album edit page

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#78]

**Comment by dset0x** [comment]
Do you mean to be able to batch-set a tag on all the songs of the album?

Note that this might be a little tricky for _removing_ tags afterwards, as one might accidentally remove more than desired (e.g. song Album1.Song1 has tag X, and then you add tag X on Album1.Song*. Then by removing tag X from the album you've also removed it from Album1.Song1 where it actually belongs).

This might actually call for tag inheritance instead
