### ISSUE TITLE
A way to lock/approve tags

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#789]
**Is your feature request related to a problem? Please describe.**
New user or inexperienced user add tags to entries that shouldn't be there. Most problematic with vocalist artist entries like UTAUs or Vocaloids.

**Describe the solution you'd like**
An option to lock/approve the tagging field for a specific entry, so that only specific user groups can edit those.

**Describe alternatives you've considered**
Tagging is locked/approved automatically when the entry is locked/approved.

**Comment by ycanardeau** [comment]
What do you mean by "only specific user groups"?

**Comment by ycanardeau** [comment]
See also #361.

**Comment by ycanardeau** [comment]
@andreoda I made a prototype for this and deployed it to the beta site. Can you please test it there and let me know if it's working?

**Comment by andreoda** [comment]
@ycanardeau 
It took a while but I collected the results here: https://docs.google.com/spreadsheets/d/1xLrWo7o-aFI-J3buvEoXzlRLNYvskk12h1bC18qiiMU/edit?usp=sharing

There were unexpected behaviors.

**Comment by ycanardeau** [comment]
@andreoda @Nefere256 Thanks for testing it and collecting the results! The spreadsheet is really easy to understand :) I think the problem of removing tags by the "manage tags" button has been fixed now. On album and artist details pages, all users who have the `EditTags` permission can open the tags edit dialog, but it won't be a problem as long as they can't save the changes. This will be fixed only after these pages have been converted to React. (For the artist details page, see #1047)

@Shiroizu If you think these changes make sense, I'll merge #1048 after some more testing.
