### ISSUE TITLE
Songs api not returning information correctly

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#796]
I used to check if a song exists with this following code (JS):

```
var apiUrl = "https://vocadb.net/api/songs?pvService=" + service + "&pvId=" + videoID;
var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
      if (xhttp.responseText != "null") {
          // Song does not exist
      } else {
          // Song exists
         var entryLink = "https://vocadb.net/S/" + JSON.parse(xhttp.responseText).id;
      }
```

https://vocadb.net/api/songs?pvService=NicoNicoDouga&pvId=sm1097445 should return a song
https://vocadb.net/api/songs?pvService=NicoNicoDouga&pvId=sm10000000000 should not return anything

Currently, both of the queries return 10 random(?) songs

**Comment by ycanardeau** [comment]
@Shiroizu Use https://vocadb.net/api/songs/byPV?pvService=NicoNicoDouga&pvId=sm1097445 and https://vocadb.net/api/songs/byPV?pvService=NicoNicoDouga&pvId=sm10000000000 respectively.

@riipah Is there any reason for `SongApiController.GetByPV` to have multiple routes? https://github.com/VocaDB/vocadb/blob/c42e884eff1089fe8821bda262457011e74b664b/VocaDbWeb/Controllers/Api/SongApiController.cs#L350-L352

**Comment by Shiroizu** [comment]
@ycanardeau Thank you!

**Comment by riipah** [comment]
> 
> 
> @Shiroizu Use https://vocadb.net/api/songs/byPV?pvService=NicoNicoDouga&pvId=sm1097445 and https://vocadb.net/api/songs/byPV?pvService=NicoNicoDouga&pvId=sm10000000000 respectively.
> 
> @riipah Is there any reason for `SongApiController.GetByPV` to have multiple routes?
> 
> https://github.com/VocaDB/vocadb/blob/c42e884eff1089fe8821bda262457011e74b664b/VocaDbWeb/Controllers/Api/SongApiController.cs#L350-L352

Back then (**5 years ago**), with ASP.NET Web API (before Swagger) it was ok to have two routes for the same URL. The idea was that you could search songs by either PV or name, which was two separate use cases with different code paths. Of course the API has evolved much since then. And Swagger/OpenAPI doesn't support multiple routes for the same URL anyway, so the empty route should be removed.
