### ISSUE TITLE
"Refresh PV metadata" wont't update/add the song length

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#803]
Maintenance action "Refresh PV metadata" does not update/add the PV length. 

This fix would be useful with updating the song entries that have the incorrect length "0:00", mostly from bilibili (around 1300 songs).

Example entries:

https://vocadb.net/S/1419
https://vocadb.net/S/193284

**Comment by riipah** [comment]
I wonder, should there also be an API for this?
