### ISSUE TITLE
User profile contains field for Discord

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#808]
Requested/Feedback of the survey:
Just like the specific Twitter field, there could be a field to put in ones Discord account/name containing: "name hashtag number". You can not "link" your Discord account so a specific field to put in that name would be useful (Since we even have an active Discord server now).

**Comment by ycanardeau** [comment]
You can get a link to a Discord profile by following [these steps](https://www.swipetips.com/how-to-send-a-link-to-a-discord-profile/).
