### ISSUE TITLE
Staistics page overhaul

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#812]
-> https://vocadb.net/stats

1. I would like to see the voicebank children included when calculating the usage of each voicebank in the VocaDB stats page.
Currently, the statistics show ALL voicebanks as seen here:
![grafik](https://user-images.githubusercontent.com/52045122/110834484-e21d9d00-829d-11eb-9bdb-307fa36a26d6.png)

- Example: Hatsune Miku V3 English, Hatsune Miku Append Dark -> Hatsune Miku (in general)
- Another solution would be to make it optional, like making it possible to choose, if I want all voicebank counted together with their children or not.

2. A more detailed time filter. It only gives the options: Overall, Last day, Last two days etc.. I would like to be able to choose a more specific time. At least months, for example: "December 2020" -> Year and Month

3. A way to either mark and copy the name or making it possible to click on names to go to the VocaDB pages of that name

4. Some sections don't seem to work anymore like before, for example: "Songs by voicebank over time"
The page doesn't load that section at all.

**Comment by hikaru-soeda** [comment]
The following three sections do not seem to be working
- Songs per voicebank over time
- Songs per voicebank type over time
- Songs by UTAU over time
![2022-03-23 (2)_LI](https://user-images.githubusercontent.com/76765993/159651782-6ab65956-e9eb-4e6d-be4a-480bea45c48a.jpg)

**Comment by ycanardeau** [comment]
@hikaru-soeda Thanks for reporting it, can you please open a new issue for that?

**Comment by hikaru-soeda** [comment]
@ycanardeau #1092 Issue opened.

**Comment by ycanardeau** [comment]
@hikaru-soeda Thanks!
