### ISSUE TITLE
Artist types could be grouped in dropdowns

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#821]
On artist edit and search pages.

For example, producer roles under one group, vocalists under another? Use HTML optgroup element.

What are the groupings? Same as song page? Maybe,

* Groups
* Producers
* Vocalists
* Other

**Comment by ycanardeau** [comment]
How about grouping by [ArtistCategories](https://github.com/VocaDB/vocadb/blob/4fa48be2f8e0b05ea6f81e5f8ce629a489249de1/VocaDbModel/Helpers/ArtistHelper.cs#L49)?

**Comment by riipah** [comment]
Mostly yes, but with some differences:
* Label would be better grouped with Circle (and probably "Other group")
* Animator could be grouped with music producer

But I guess ArtistCategories could be used as is at first, to make it simple.
