### ISSUE TITLE
Bad contrast in the search field

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#838]
![grafik](https://user-images.githubusercontent.com/52045122/114875659-cc037f00-9dfd-11eb-9cd3-de27fec4b878.png)

**Comment by ycanardeau** [comment]
I can't reproduce this on my local machine. Can you clear your cache and reload the page?

**Comment by ycanardeau** [comment]
Seems like this is a Firefox-only issue.

**Comment by andreoda** [comment]
Sorry for the late reply, even after reloading it looks like this.
I just tried chrome and you are right, there it looks alright: 
![grafik](https://user-images.githubusercontent.com/52045122/114990422-c1e28e80-9e98-11eb-8132-6137a09d45e8.png)
