### ISSUE TITLE
Artist url parser for twitter "@handle"

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#843]
Add url helper for twitter links:

Typing "@{artist twitter}" would give the artist entry that has the twitter URL, similarly to "mylist/{id}" with NND mylist links: https://github.com/VocaDB/vocadb/blob/f77563e9ba12b386c69bcb4532ee919daa2cd752/VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs

It would be useful on song/album edit pages, since it's common to see artists credited that way.

**Comment by Pyther99** [comment]
There are some artists who have a name that starts with @ (https://vocadb.net/Search?filter=@&searchType=Artist). Do you have a suggestion for an alternative shortcut? ( The best I can think of is t/{artist name} )
