### ISSUE TITLE
Increase the amount of visible events on the homepage

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#849]
A large event is currently hidden from the home page due to other events taking precedence because they're more recent.

https://vocadb.net/E/3784/the-vocaloid-collection-2021-s

Currently, the limit seems to be 3: https://github.com/VocaDB/vocadb/blob/821e292b118e2049e44bb1474e5db002f8c374dc/VocaDbModel/Service/OtherService.cs

Maybe 4-6 would be better.

**Comment by ycanardeau** [comment]
Implemented by @Pyther99.
