### ISSUE TITLE
Editing tags/tag system is broken

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#855]
**Website**
VocaDB

**Describe the bug**
It is not possible to edit tags. After creating one, the fields are empty when in the editing mode and the category and parent field do not recognize any text. After saving, the page leads to an error page.

![grafik](https://user-images.githubusercontent.com/52045122/116445860-a0997f00-a856-11eb-9bc2-c7d07e260c62.png)

**Comment by andreoda** [comment]
I just found out that deleting tags is also not possible anymore. There is a spam tag I want to delete but the buttons don't do anything anymore ("delete" and "move to trash").

**Comment by ycanardeau** [comment]
Fixed.
