### ISSUE TITLE
Missing entry link gives internal server error (500) instead of not found (404)

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#858]
Navigating to nonexistent page for example https://vocadb.net/S/393939 gives error 500. It should instead show content from https://vocadb.net/Error/NotFound

This used to work on the old site. Maybe related to ASP.NET Core conversion.

**Comment by ycanardeau** [comment]
In ASP.NET 4.x, we were able to handle errors in the [Application_Error](https://github.com/VocaDB/vocadb/blob/4fa48be2f8e0b05ea6f81e5f8ce629a489249de1/VocaDbWeb/Global.asax.cs#L83) method, but in ASP.NET Core, we need to handle exceptions  in middleware.
