### ISSUE TITLE
Linking UtaiteDB entries as "Original version" broken

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#859]
**Website**
VocaDB

**Describe the bug**
Linking UtaiteDB (or TouhouDB) entries as "Original version" under the song type field does not seem to work.

Example: https://vocadb.net/S/331659

Original issue: https://github.com/VocaDB/vocadb/issues/73

**Comment by riipah** [comment]
There's an error in console, it seems to be querying VocaDB with the same ID
