### ISSUE TITLE
Show that logging in with email is possible in login form

### ISSUE THREAD

**Issue by dset0x** [VocaDB/vocadb#865]
~~This would be convenient for users who forgot their username.~~
Perhaps replace "Username" with "Username or verified email"

**Comment by riipah** [comment]
I think this should already work if the email is verified.

**Comment by dset0x** [comment]
You're absolutely right! Edited the issue.

We recently had a user who had forgotten their username, but recovery is only possible if you know your username. I take it this is by design to avoid abusing the recovery form. I wonder if it's really necessary given that there's a captcha on it (is there also a rate limit?).
