### ISSUE TITLE
bilibili embedded window needs adjusting

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#876]
**Website**
VocaDB

**Describe the bug**
The bilibili embedded window needs adjusting in size, the bottom shows a bit of unnecessary space. That space also shows a corner of a popup window that can be accidentally clicked on and leads to another page (Commercial for the bilibili app). It is pretty annoying when actually trying to click on the play button.

![window](https://user-images.githubusercontent.com/52045122/118892380-1eeebb80-b901-11eb-839c-87b3a50d2ab5.png)

**Comment by ycanardeau** [comment]
Please provide at least 10 examples of VocaDB entries when you open an issue.

**Comment by ycanardeau** [comment]
@andreoda Can you try it on the beta site?

**Comment by andreoda** [comment]
@ycanardeau yes, on the beta site it is fixed. Thank you.

not fixed: ![grafik](https://user-images.githubusercontent.com/52045122/122572838-6bd3c800-d04e-11eb-8e9f-b3aa395cfe51.png)
fixed: ![grafik](https://user-images.githubusercontent.com/52045122/122572866-73936c80-d04e-11eb-9293-21999dd4a8fa.png)

**Comment by ycanardeau** [comment]
Fixed by @AgFlore.
