### ISSUE TITLE
Include albums whose release dates were specified only by year/month in sorted queries

### ISSUE THREAD

**Issue by AgFlore** [VocaDB/vocadb#881]
**Is your feature request related to a problem? Please describe.**
When querying albums, if one chooses "sort by release date", only albums whose release date have been specified by date are listed. Albums with release date specified like "2020/10" won't show up in the query result. This can be confusing (if not misleading) to readers.

There're many albums who have no accurate release date announced; producers just put up the ordering some day, and start shipping whatever else day when everything gets ready to ship. And our editors would finalize the release date specified to the month people receives the album, leaving the date field blank.

**Describe the solution you'd like**
Currently the logic is 
```
public static IQueryable<Album> WhereHasReleaseDate(this IQueryable<Album> criteria) 
{ 
    return criteria.Where(a => a.OriginalRelease.ReleaseDate.Year != null 
        && a.OriginalRelease.ReleaseDate.Month != null && a.OriginalRelease.ReleaseDate.Day != null); 
}
```
https://github.com/VocaDB/vocadb/blob/585136f696bdff161acbd3c6e6599860a66d8386/VocaDbModel/Service/QueryableExtensions/AlbumQueryableExtensions.cs#L133

And we may change this behaviour.

**Comment by ycanardeau** [comment]
Can you please create a branch or PR, so that we can test it on the beta site? It should be pretty easy to implement, because you already know where to change.

1. Add an extension method named `WhereHasReleaseYearAndMonth` to the `AlbumQueryableExtensions` class.
2. Replace `WhereHasReleaseDate` in the `WhereSortBy` method with `WhereHasReleaseYearAndMonth`.

**Comment by AgFlore** [comment]
The beta search page easily gets stuck when i'm making queries. Not sure is there any fault with the code or not.

And one more thing, do we need to change the behaviour here https://github.com/VocaDB/vocadb/blob/e5c33b3256ab6e5b29235e1fee13d0177fffc577/VocaDbModel/Service/QueryableExtensions/AlbumForUserQueryableExtensions.cs#L155 as well? (I'm having no picture of the project's structure otz)

**Comment by ycanardeau** [comment]
> do we need to change the behaviour here

As its name `AlbumForUser` (which is an [associative entity](https://en.wikipedia.org/wiki/Associative_entity)) implies, the extension method is used to filter albums in a user's collection. If you want to include albums with no day or month on the user details page as well, you need to change the behavior.

> I'm having no picture of the project's structure otz

In Visual Studio, you can use the "Find All References" feature by pressing [Shift] + [F12].

**Comment by AgFlore** [comment]
> As its name `AlbumForUser` (which is an [associative entity](https://en.wikipedia.org/wiki/Associative_entity)) implies, the extension method is used to filter albums in a user's collection. If you want to include albums with no day or month on the user details page as well, you need to change the behavior.
Oh I see!
Then i think i've been doing correctly. Let's roll the pr out in the beta site to see whether it's working properly.
> > I'm having no picture of the project's structure otz
> In Visual Studio, you can use the "Find All References" feature by pressing [Shift] + [F12].
Thanks! Will try to navigate myself through the project.

**Comment by ycanardeau** [comment]
> Let's roll the pr out in the beta site to see whether it's working properly.

Deployed.

**Comment by ycanardeau** [comment]
Implemented by @AgFlore.
