### ISSUE TITLE
Field for "past members" of a group/circle or label

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#883]
Sometimes, people leave groups/teams. If we implement this option, we can still maintain the fact that certain people belonged to a group/team.
Future confusion could be avoided through this as well. People might ask why a specific artist is mentioned in a specific entry.

Could be useful for the following issue:
![grafik](https://user-images.githubusercontent.com/52045122/120000365-0488a200-bfd3-11eb-9c51-cf2cc93e4521.png)
https://vocadb.net/Ar/84621
Specific members left the circle.

**Comment by ycanardeau** [comment]
We could add either a set of two dates, `BeginDate` and `EndDate` (inspired by MusicBrainz), or a boolean field `HasEnded` (inspired by AniDB) to the `GroupsForArtists` table. If it's just this one case, it's not a good idea to implement this.

References:
- https://musicbrainz.org/doc/Relationships
- https://wiki.musicbrainz.org/User:Kepstin/STYLE-227/Begin_and_End_Dates

**Comment by riipah** [comment]
I think this is relatively common. I'm sure someone can find more examples. That said, I'm also not sure is it worth it. If implemented, probably the dates are too much (they can be mentioned in description, also the situation might be complicated, sometimes the membership can be on-off-on-off).

**Comment by ycanardeau** [comment]
[mentioned](https://discord.com/channels/309072240639737866/797103264655081492/848577939020054608)

**Comment by riipah** [comment]
Not part of this issue, but it might be good idea to prepare to add additional metadata to group membership.

* Group leader: usually group has a leader. This could be included in membership.
* Role in group: sometimes artists perform specific duties in a specific group. For example, an artist might be a music producer, but in a specific group they only do instrumentals (I don't have examples about this, but I'm sure there are those).

**Comment by andreoda** [comment]
I think it could also be useful to specify how long a past member was in a group (length). For example Livetune. 
Reference: https://en.wikipedia.org/wiki/Livetune
>Members:
>Kz (pronounced "K-Zet") (music, lyrics)
>Former member:
>Kajuki P (music, lyrics) (2007-2009)

The year would be enough. Like in this case.

**Comment by riipah** [comment]
As a general note, I would say that adding metadata (such as roles or dates) to membership makes sense if it affects the way other information is displayed. For example, marking someone as the group leader allows highlighting that person in the members listing. I don't know how roles and dates would be shown, but if it's just a detail in the members listing, then it could as well be in the description I guess? No harm adding it to membership metadata, but it might be additional work with little value.

**Comment by andreoda** [comment]
I've encountered more cases by now and it gets kinda annoying that artists remove their groups from their entry. It will only lead to confusion (song entry mentions group, how are they associated?) and in the end: empty group pages.

For now, I think, it would be enough if at least a second field for "past groups" or something similar could be added, just like riipah mentioned in the last comment.
(Thinking about it now, metadata like date could be also too difficult to maintain since sometimes we will not know when a group started or ended exactly.)
