### ISSUE TITLE
Transfer ownership of UtaiteDB's Twitter App

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#890]

**Comment by riipah** [comment]
Form: https://help.twitter.com/en/forms/platform/transfer-api-key

Transfer to: @ycanardeau

**Comment by riipah** [comment]
Submitted form.

>We’ve received your request. We typically respond within a few days, but some cases can take a little longer.

**Comment by riipah** [comment]
>Hello @riipah,
>Thank you for writing in. We have transferred ownership of the app to the designated account.
