### ISSUE TITLE
Move the blog somewhere else or shut it down

### ISSUE THREAD

**Issue by ycanardeau** [VocaDB/vocadb#897]
For security reasons. We have the following options:

1. Move the blog to another server while using the blog.vocadb.net domain.
2. Use a blog hosting service and connect the blog.vocadb.net domain to the blog.
3. Delete the blog.

**Comment by Shiroizu** [comment]
Not sure how much work there is with 1 and 2.

Using twitter in conjunction with https://vocadb.net/discussion might be fine.

**Comment by riipah** [comment]
1. Would probably mean setting up a Linux server with Wordpress. Easy-ish for someone who has the experience with Linux hosting, difficult for anyone else.
2. Is super easy (I had that for a while), but costs money ($ 5-10 per month).

**Comment by ycanardeau** [comment]
Or we could convert the blog to a static site and turn it into read-only mode?

**Comment by riipah** [comment]
If you don't plan on updating it anymore, yeah.

**Comment by andreoda** [comment]
Since the VocaDB blog is gone and the VocaDB wiki will be updated to have more features (https://github.com/VocaDB/Wiki), I am closing this issue.
