### ISSUE TITLE
Friendly (user readable) URLs

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#9]
VocaDB routing supports "friendly" URLs with entry title in the URL, for example http://vocadb.net/S/18410/gift-nor-art. There's even code for generating these URLs based on entry names (EntryUrlFriendlyNameFactory). What needs to be resolved is to make sure these URLs are used everywhere. Those URLs should also be saved to the database or at least cached, to avoid affecting performance too much.

**Comment by dset0x** [comment]
FWIW, we might want to validate that part of the URL before serving.

We probably do not want to serve https://vocadb.net/S/18410/buy-acoustic-guitars-here.

**Comment by riipah** [comment]
The friendly URL would be automatically generated based on song name, you cannot customize it.

**Comment by dset0x** [comment]
I mean when the server receives a request. For example some news websites do the same, but whether you try to access /news/1234/miku-albums-shoplifters-caught or /news/1234/totally-made-up-URI, the server will give you the same page (ignoring the user friendly part).

**Comment by riipah** [comment]
Why would you need to validate it? What does it matter if it's serving the page with wrong friendly URL? Currently for tags it's not doing any validation. It's also complicated because 1) in some cases the friendly URL is not known, only ID, 2) the friendly URL may change if the entry is renamed

**Comment by dset0x** [comment]
> Why would you need to validate it? What does it matter if it's serving the page with wrong friendly URL? Currently for tags it's not doing any validation. I decided not to, because 1) in some cases the friendly URL is not known, only ID, 2) the friendly URL may change if the entry is renamed.

It's just silly or defaming to serve a URL that would imply bad content (whatever that may be), but you definitely have a good point with point (2). That would indeed complicate things way more than necessary.
