### ISSUE TITLE
Cannot use table formatting in the description field of tag pages

### ISSUE THREAD

**Issue by hikaruso** [VocaDB/vocadb#904]
**Website**
VocaDB

**Describe the bug**
If you enter a table in the description field of the tag edit page using Markdown notation, the table will not be displayed on the tag page, but the Markdown string will be displayed as is.

**To Reproduce**
1. Open the tag edit screen.
2. Enter the table in the description field using markdown notation. 
![2021-07-04 (4)](https://user-images.githubusercontent.com/76765993/124381134-caaa6a00-dcfb-11eb-9b03-dfb6b4b6653c.png)

3. Save the page.
4. Check the tag page. 
![2021-07-04 (5)](https://user-images.githubusercontent.com/76765993/124381138-d1d17800-dcfb-11eb-8584-564b5fc2c4fa.png)

**Expected behavior**
Since the table formatting is visible in the preview of the edit page, it should be visible in the tag page as well.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium: 91.0.4472.124

https://vocadb.net/T/8044 (Revision 5)

**Comment by ycanardeau** [comment]
Related to #38.
