### ISSUE TITLE
Increase maximum BPM to 1000

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#910]
Synth V allows 1000 BPM for vocals. Seems reasonable we would allow up to that at least.

[Source](https://discord.com/channels/309072240639737866/666326527197315091/861754128496721930)

I found a [Vocaloid song that has reported BPM 720](https://vocadb.net/S/341595). Currently marked as 360 BPM. I don't know how that works. In any case, it would be simpler for the editor to input the real value 720 and the system can treat it as 360 BPM if necessary, for example for finding similar songs (but this should be a separate issue).

Let's see if 1000 is enough. The value could be changed easily and increased more if necessary.

**Comment by ycanardeau** [comment]
How about 1015 instead of 1000?

Quote from https://en.wikipedia.org/wiki/Thousand_(song):
> "Thousand" was listed in Guinness World Records for having the fastest tempo in beats-per-minute (BPM) of any released single, peaking at approximately 1,015 BPM.

Reference(s):
- [From 9999 BPM To 1 BPM - YouTube](https://www.youtube.com/watch?v=dMRAShGvT1g)

**Comment by riipah** [comment]
That's fine too

**Comment by ycanardeau** [comment]
done

**Comment by riipah** [comment]
Thanks!
