### ISSUE TITLE
Show event category when adding songs/albums to an event entry.

### ISSUE THREAD

**Issue by Untitled39** [VocaDB/vocadb#918]
**Is your feature request related to a problem? Please describe.**
Sometimes, we have multiple events with very similar names, due to this songs/albums are sometimes added to the wrong event entry (for example, a song contest entry can mistakenly be added to a song contest feature event), it can be specially hard for new editors to distinguish which event they should add an entry to.

Examples of event series with similar names:
* [Magical Mirai Song Contest](https://vocadb.net/Es/141) / [Magical Mirai Song Contest Feature](https://vocadb.net/Es/165)
* [Luo Tianyi Birthday](https://vocadb.net/Es/181/luo-tianyis-birthday) / [Luo Tianyi Birthday Party](https://vocadb.net/E/3788/luo-tianyi-2020-birthday-party)
* [The VOCALOID Collection](https://vocadb.net/Es/264) / [The VOCALOID Collection LIVE](https://vocadb.net/Es/265)

**Describe the solution you'd like**
I think a good solution to prevent mistakes could be showing the event category (concert, song contest, etc) at the moment of editing a song/album entry.

**Additional context**
[A small example of my idea made in paint](https://i.imgur.com/lvKgYUO.jpg)
.

**Comment by ycanardeau** [comment]
[mentioned](https://discord.com/channels/309072240639737866/797103264655081492/833254190083473468)

**Comment by ycanardeau** [comment]
This feature is now partially available on the beta site. This will be fully available after all pages are converted to React.
