### ISSUE TITLE
SoundCloud API changes

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#927]
Email from SoundCloud:

----
Dear partner / API user,

If you are not calling `api.soundcloud.com` you can stop reading right here. Otherwise, there are a number of updates that might require actions from your side.

At the beginning of July, we announced security updates to our API, mainly how we deal with auth. Please read a blog post to know more about the changes.

We understand that it’s a lot and might require some time on your side to update the systems. We would appreciate it if you could start working on it ASAP, as some of the changes are live already.

Deprecation of `client_id` and the requirement to provide an `Authorization` header for each request is the biggest update. We are planning to start slowly rolling it out in September. Meaning that some percentage of requests will start failing if the header is not present.

If you have no capacity to update your systems in the following 1-2 months please let us know. We will try to find a solution. We definitely do not want to create a bad experience for users.

For any further questions please do not hesitate to contact us. You can comment on this thread, or create a new ticket.

Best,

Soundcloud Team 

----

This does concern VocaDB, and sounds like it needs changes.

Also documented here: https://developers.soundcloud.com/blog/security-updates-api

**Comment by ycanardeau** [comment]
@riipah Thanks for your info. I've got the following message when I tried to sign up for a new app. Do you happen to have an existing one? I managed to find `CLIENT_ID`, but not `CLIENT_SECRET`.

> Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient.

And quote from https://github.com/soundcloud/api:

> Can I request an API key for a new app?
We're actively exploring on how best to open up public access to our API again. While we're currently not issuing new API keys to 3rd party apps, we're helping improve the systems and tools in place to better serve the already active integrations.

**Comment by riipah** [comment]
I can send them to you.

**Comment by ycanardeau** [comment]
Fixed by #938.
