### ISSUE TITLE
More filters for search: media/source type

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#941]
Currently we only have the option to search for:
- no original media
- no media
and
- only with PVs

I think it would be useful to include the type of media as well. For example:
- NicoNicoVideo
- YouTube
- bilibili
- SoundCloud

Based on the the media types that are currently supported as embeds.

I am not sure though, if it should be "only original media" or if it should include reprints as well as default.

**Comment by Shiroizu** [comment]
> I am not sure though, if it should be "only original media" or if it should include reprints as well as default.

The current API implementation includes reprints as well, so it should probably mirror the same behaviour.

**Comment by andreoda** [comment]
Oh okay. How do I use it? I want to find songs that have no YT PV added.

**Comment by ycanardeau** [comment]
Hmm, I think it's impossible with the current API implementation.

**Comment by Shiroizu** [comment]
If it's a one time thing, you could use the datadump to get the entries with no Youtube PVs.

**Comment by CatgirlFrostmoon** [comment]
Given that this topic got reopened on VocaDB itself, consider this a vote towards PV search functions, once again.

**Comment by ycanardeau** [comment]
[mentioned](https://vocadb.net/discussion/topics/473)
