### ISSUE TITLE
Prefer "original song" entries when searching for original versions on song submit/edit pages

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#949]
When adding/editing derivate works, searching for the original version should prefer showing "original song" -entries first. 

For example, here the original version is shown on bottom of the search results (should be among the first results).

<img width="194" alt="Untitled" src="https://user-images.githubusercontent.com/15908050/130624436-2f85ebee-9566-4149-97f7-131c6026ff7a.png">

**Comment by ycanardeau** [comment]
Available on the [beta site](https://beta.vocadb.net), but does it make sense to prefer original song entries *everywhere*? I wonder if there is some performance penalty. Should we add an option like `preferOriginal` to the song API?

**Comment by CatgirlFrostmoon** [comment]
I think ranking the songs by popularity would help a lot, too -- I always run into issues adding covers of Kanaria's works because of the one-word titles, and sorting the songs by popularity would help a lot.
