### ISSUE TITLE
Bilibili Connector Availablility Low

### ISSUE THREAD

**Issue by AgFlore** [VocaDB/vocadb#955]
Seems their api is blocking requests from vocadb. Affects all scenarios where one's providing a Bilibili PV to the database.

Just `curl https://beta.vocadb.net/api/pvs?pvUrl=https://www.bilibili.com/video/BV1pU4y1771r` (or whatever video you like) and see how often it fails.

The Bilibili api itself seems perfectly functional, at least from my own browser. You can try like `curl https://api.bilibili.com/x/web-interface/view?bvid=BV1pU4y1771r`.

Would like to see diagnostic logs on the server about details of the failure.

**Comment by ycanardeau** [comment]
```
The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
```

 Would [increasing the timeout](https://github.com/VocaDB/vocadb/blob/dc352077711421e5d2c07a196aa427cc401b2841/VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs#L49) fix this problem?

**Comment by AgFlore** [comment]
> ```
> The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
> ```
> 
> Would [increasing the timeout](https://github.com/VocaDB/vocadb/blob/dc352077711421e5d2c07a196aa427cc401b2841/VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs#L49) fix this problem?

I've never encountered requests for Bilibili apis taking that long to respond. Now on vocadb we still expect Bilibili to parse within one second (as we have always been used to); if it does not respond within 10 seconds, then i suspects it would ever respond. 

But by now it seems the only way to try out before us. 

So far I cannot reproduce the issue elsewhere :( 
By what rate is vocadb's server making requests to Bilibili recently? Would it be in any way unreasonably high? 
Or can we measure and log each request the server makes, and check whether there is any pattern for timeout behaviour of the api?

**Comment by ycanardeau** [comment]
> By what rate is vocadb's server making requests to Bilibili recently? Would it be in any way unreasonably high?
> Or can we measure and log each request the server makes, and check whether there is any pattern for timeout behaviour of the api?

@AgFlore Added logging when loading Bilibili URL. Let's see how it goes for a while.
