### ISSUE TITLE
Old search links with missing parameters won't work

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#967]
**Website**
VocaDB

The website uses links that include search parameters:
https://vocadb.net/T/1552/edm "Top artists" is a link to
https://vocadb.net/Search?searchType=Artist&tagId=7526 (does not currently work)

To my understanding, this might be related to the new search URL changes: https://github.com/VocaDB/vocadb/pull/965

**Comment by ycanardeau** [comment]
If we have only one `tagId`, it is considered as `number` rather than `number[]`, which results in failing validation by ajv. I changed the schema, so that ajv allows not only `number[]`, but also `number`.
