### ISSUE TITLE
Search page doesn't respect language setting

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#968]
My language setting on VocaDB is English. However, my browser's preferred language is Finnish. Other pages on VocaDB are in English, but [search page](https://vocadb.net/Search) appears all in Finnish. I would naturally expect that page to be English as well.

Browser: Edge 93
OS: Windows 10

**Comment by ycanardeau** [comment]
Some pages on VocaDB (search, featured song lists, users, discussions and site management pages) have been converted to React, and they were ignoring the interface language setting. I specified the language to use in the i18next options.

**Comment by riipah** [comment]
Okay, thanks!
