### ISSUE TITLE
Clicking tag suggestion in top bar search box doesn't work.

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#969]
1. Type something in the top bar (top of every page) to search. For example "Japanese". Make sure "Tags" is selected.
2. Observe suggestion for "Japanese", which is a tag.
3. Click suggestion.
4. User gets forwarded to search page
5. Observe that filter box on search page is empty
6. Observe that the tab is "Anything", instead of "Tags".
7. Change tab to "Tags". Observe that the search term is lost.

The same also happens when searching with quotation marks.

In step 1: Type something in the top bar (top of every page) to search, with quotation marks. For example "Engrish". Make sure "Anything" is selected.

It's a little hard to figure out the cases. There is definitely more than one. But it doesn't happen with all term suggestions.

Browser: Edge 93
OS: Windows 10

![image](https://user-images.githubusercontent.com/550886/134662646-6d67342b-f88d-4304-931e-5167e5121c13.png)

**Comment by ycanardeau** [comment]
The new implementation validates the query string on the client side every time the URL changes (#965). It seems that validation is failing due to case sensitivity.

**Comment by riipah** [comment]
I think making it case-insensitive would be best, if possible. Otherwise, I guess the server can convert them to normalized format (lowercase)?

**Comment by ycanardeau** [comment]
I ended up converting all property names in the SearchIndexViewModel class to camelCase. Although it's not an elegant way and there is no need to still use the SearchIndexViewModel class, it should be fine for now.
