### ISSUE TITLE
Secure page for logging in

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#97]
Major browsers are marking HTTP insecure for things like logging in. We would like to convert the whole site to HTTPS, but it's not possible due to embeds for sites like NicoNicoDouga. Therefore, we should at least have a page for logging in that's completely HTTPS. The page can't have anything else - no links to the site, because those would lead the user to the (non-functional) HTTPS site.

**Comment by dset0x** [comment]
It should be okay to close this now, right?

**Comment by ycanardeau** [comment]
Quotes from https://github.com/VocaDB/vocadb/pull/701#discussion_r549265904:

> In ASP.NET Core you can make the whole app require SSL, which would be okay and probably simpler, now that it's all using SSL anyway. This attribute is from the time when only certain pages were SSL. Even in development you could use SSL, because IIS Express supports it using self-signed certificate.

So I'd say yes at least for ASP.NET Core.

**Comment by riipah** [comment]
This task is obsolete. The whole website has been HTTPS for a while now, after Nico Nico started supporting HTTPS too.
