### ISSUE TITLE
Error reverting song entry to an earlier version

### ISSUE THREAD

**Issue by kateabr** [VocaDB/vocadb#976]
**Website**
VocaDB

**Describe the bug**
Reverting a song entry to an earlier version causes an error.

**To Reproduce**
1. Go to https://vocadb.net/Song/ViewVersion/1083860
2. Click "Revert to this version", confirm
3. Error

**Additional context**
User that closed the report replaced lyrics and romanization that I corrected and proofread with inaccurate ones, and I have no backups.

*EDIT: the issue with lyrics has been resolved, there is no need to revert the particular entry from my example.*

**Comment by ycanardeau** [comment]
The `URL` and `Source` properties may be null when deserializing the `LyricsForSongContract` class. It seems that the `DefaultValueHandling.Populate` option is not working? Would it be enough to just set default value as empty string?
