### ISSUE TITLE
Make Google Rich snippets for album reviews work

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#99]
I have added [microdata](https://schema.org/docs/gs.html) on VocaDB album reviews, for example [here](http://vocadb.net/Al/427). [Structured data testing tool](https://developers.google.com/structured-data/testing-tool/) finds it, and even reports "all good", yet the reviews don't appear in Google search results. I have no idea what's wrong to be honest. If someone else has an idea, please tell me.

**Comment by bomjacob** [comment]
Seems to work now :)
![image](https://cloud.githubusercontent.com/assets/3002987/18814435/c0072cce-8313-11e6-9206-78f8fa691376.png)

**Comment by riipah** [comment]
Yeah I guess they fixed themselves at some point
